/**
 * Sistema de eventos del Automation Engine (Fase E1). Toda acción importante
 * genera un evento; otras automatizaciones lo consumen (encadenado). Catálogo
 * universal como DATOS — ninguna industria específica.
 */

export const AUTOMATION_EVENTS = {
  CLIENT_REGISTERED: 'cliente.registrado',
  CLIENT_VISIT: 'cliente.visita',
  CLIENT_RENEWED: 'cliente.renovo',
  CLIENT_CANCELLED: 'cliente.cancelo',
  CLIENT_LEVEL_UP: 'cliente.subio_nivel',
  CLIENT_REWARD_OBTAINED: 'cliente.obtuvo_recompensa',
  CLIENT_COUPON_USED: 'cliente.uso_cupon',
  CLIENT_STREAK_REACHED: 'cliente.alcanzo_racha',
  CLIENT_STREAK_LOST: 'cliente.perdio_racha',
  CLIENT_REFERRED_FRIEND: 'cliente.recomendo_amigo',
  CLIENT_MISSION_COMPLETED: 'cliente.completo_mision',
  CLIENT_PURCHASE: 'cliente.compro_servicio',
  // Ciclo de vida temprano (onboarding) — universales, ninguna industria.
  CLIENT_PROFILE_COMPLETED: 'cliente.completo_perfil',
  CLIENT_VERIFIED: 'cliente.verifico_cuenta',
  CLIENT_PREFERENCES_SET: 'cliente.configuro_preferencias',
  CLIENT_CONSENT_GIVEN: 'cliente.acepto_consentimiento',
  CLIENT_FIRST_VISIT: 'cliente.primera_visita',
  CLIENT_ONBOARDING_COMPLETED: 'cliente.completo_onboarding',
  // Conversión / primera compra — universales, ninguna industria.
  CLIENT_FIRST_PURCHASE: 'cliente.primera_compra',
  CLIENT_HIGH_VALUE_PURCHASE: 'cliente.compra_alto_valor',
  CLIENT_PROCESS_ABANDONED: 'cliente.proceso_abandonado',
  CLIENT_FEEDBACK_GIVEN: 'cliente.dio_feedback',
  CLIENT_LOYALTY_ENROLLED: 'cliente.inscrito_fidelizacion',
  // Frecuencia / comportamiento — universales, ninguna industria.
  CLIENT_FREQUENCY_DROP: 'cliente.bajo_frecuencia',
  CLIENT_FREQUENCY_UP: 'cliente.subio_frecuencia',
  CLIENT_FREQUENCY_GOAL: 'cliente.alcanzo_meta_frecuencia',
  CLIENT_HIGH_ACTIVITY: 'cliente.alta_actividad',
  CLIENT_BEHAVIOR_CHANGED: 'cliente.cambio_comportamiento',
  CLIENT_BENEFIT_UNDERUSED: 'cliente.no_usa_beneficios',
  CLIENT_CHURN_RISK: 'cliente.riesgo_abandono',
  // Recuperación / retención — universales, ninguna industria.
  CLIENT_RISK_LEVEL_CHANGED: 'cliente.cambio_nivel_riesgo',
  CLIENT_INACTIVE: 'cliente.inactivo',
  CLIENT_RECOVERED: 'cliente.recuperado',
  CLIENT_CAMPAIGN_IGNORED: 'cliente.ignoro_campana',
  MEMBERSHIP_EXPIRED: 'membresia.vencida',
  BENEFIT_EXPIRING: 'beneficio.por_vencer',
  // Ciclo de vida de la membresía — universales, cualquier modelo.
  MEMBERSHIP_CREATED: 'membresia.creada',
  MEMBERSHIP_ACTIVATED: 'membresia.activada',
  MEMBERSHIP_FIRST_USE: 'membresia.primer_uso',
  MEMBERSHIP_RENEWED: 'membresia.renovada',
  MEMBERSHIP_UPGRADED: 'membresia.upgrade',
  MEMBERSHIP_DOWNGRADED: 'membresia.downgrade',
  MEMBERSHIP_SUSPENDED: 'membresia.suspendida',
  MEMBERSHIP_REACTIVATED: 'membresia.reactivada',
  MEMBERSHIP_CANCELLED: 'membresia.cancelada',
  MEMBERSHIP_EXPIRING: 'membresia.por_vencer',
  // Journey de referidos — universales, cualquier programa.
  REFERRAL_CODE_GENERATED: 'referido.codigo_generado',
  REFERRAL_SHARED: 'referido.invitacion_compartida',
  REFERRAL_REGISTERED: 'referido.invitado_registrado',
  REFERRAL_CONVERTED: 'referido.convirtio',
  REFERRAL_REWARD_PENDING: 'referido.recompensa_pendiente',
  REFERRAL_REWARD_RELEASED: 'referido.recompensa_liberada',
  REFERRAL_REWARD_EXPIRED: 'referido.recompensa_vencida',
  REFERRAL_FRAUD_DETECTED: 'referido.fraude_detectado',
  REFERRAL_REJECTED: 'referido.rechazado',
  REFERRAL_AMBASSADOR_REACHED: 'referido.embajador_detectado',
  // Orquestación de campañas — universales, ninguna industria.
  CAMPAIGN_LAUNCHED: 'campana.lanzada',
  CAMPAIGN_PARTICIPATED: 'campana.participacion',
  CAMPAIGN_CONVERTED: 'campana.conversion',
  CAMPAIGN_PAUSED: 'campana.pausada',
  CAMPAIGN_RESUMED: 'campana.reanudada',
  CAMPAIGN_FINISHED: 'campana.finalizada',
  CAMPAIGN_CHILD_STARTED: 'campana.hija_iniciada',
  // Gamificación conductual — universales, ninguna industria.
  GAMI_MISSION_STARTED: 'gamificacion.mision_iniciada',
  GAMI_STREAK_RECOVERED: 'gamificacion.racha_recuperada',
  GAMI_LEVEL_DOWN: 'gamificacion.bajo_nivel',
  GAMI_BADGE_UNLOCKED: 'gamificacion.insignia_desbloqueada',
  GAMI_RANKING_UPDATED: 'gamificacion.ranking_actualizado',
  GAMI_CHALLENGE_COMPLETED: 'gamificacion.desafio_completado',
  GAMI_COMPETITION_STARTED: 'gamificacion.competencia_iniciada',
  GAMI_COMPETITION_FINISHED: 'gamificacion.competencia_finalizada',
  GAMI_GOAL_REACHED: 'gamificacion.meta_alcanzada',
  GAMI_GROUP_GOAL_REACHED: 'gamificacion.meta_grupal',
  // Decisiones inteligentes / recomendaciones — universales, sin IA.
  DECISION_MADE: 'decision.tomada',
  RECOMMENDATION_READY: 'recomendacion.lista',
  OPPORTUNITY_DETECTED: 'oportunidad.detectada',
  RISK_DETECTED: 'riesgo.detectado',
  NEXT_BEST_ACTION_READY: 'siguiente_accion.lista',
  // Emitidos por el propio motor.
  AUTOMATION_STARTED: 'automatizacion.iniciada',
  AUTOMATION_FINISHED: 'automatizacion.finalizada',
} as const

export type AutomationEventType =
  (typeof AUTOMATION_EVENTS)[keyof typeof AUTOMATION_EVENTS]

export interface AutomationEventDef {
  readonly id: string
  readonly name: string
  readonly description: string
}

export const AUTOMATION_EVENT_CATALOG: readonly AutomationEventDef[] = [
  { id: AUTOMATION_EVENTS.CLIENT_REGISTERED, name: 'Cliente registrado', description: 'Un cliente creó su cuenta.' },
  { id: AUTOMATION_EVENTS.CLIENT_VISIT, name: 'Cliente realizó visita', description: 'El cliente usó el servicio.' },
  { id: AUTOMATION_EVENTS.CLIENT_RENEWED, name: 'Cliente renovó', description: 'El cliente renovó su membresía.' },
  { id: AUTOMATION_EVENTS.CLIENT_CANCELLED, name: 'Cliente canceló', description: 'El cliente canceló su membresía.' },
  { id: AUTOMATION_EVENTS.CLIENT_LEVEL_UP, name: 'Cliente cambió de nivel', description: 'El cliente subió de nivel.' },
  { id: AUTOMATION_EVENTS.CLIENT_REWARD_OBTAINED, name: 'Cliente obtuvo recompensa', description: 'El cliente recibió una recompensa.' },
  { id: AUTOMATION_EVENTS.CLIENT_COUPON_USED, name: 'Cliente utilizó cupón', description: 'El cliente canjeó un cupón.' },
  { id: AUTOMATION_EVENTS.CLIENT_STREAK_REACHED, name: 'Cliente alcanzó una racha', description: 'El cliente logró una racha.' },
  { id: AUTOMATION_EVENTS.CLIENT_STREAK_LOST, name: 'Cliente perdió una racha', description: 'El cliente rompió su racha.' },
  { id: AUTOMATION_EVENTS.CLIENT_REFERRED_FRIEND, name: 'Cliente recomendó un amigo', description: 'El cliente refirió a alguien.' },
  { id: AUTOMATION_EVENTS.CLIENT_MISSION_COMPLETED, name: 'Cliente completó una misión', description: 'El cliente terminó una misión de gamificación.' },
  { id: AUTOMATION_EVENTS.CLIENT_PURCHASE, name: 'Cliente compró un servicio', description: 'El cliente adquirió un servicio.' },
  { id: AUTOMATION_EVENTS.CLIENT_PROFILE_COMPLETED, name: 'Cliente completó su perfil', description: 'El cliente terminó de completar la información de su perfil.' },
  { id: AUTOMATION_EVENTS.CLIENT_VERIFIED, name: 'Cliente verificó su cuenta', description: 'El cliente confirmó su cuenta (correo/teléfono).' },
  { id: AUTOMATION_EVENTS.CLIENT_PREFERENCES_SET, name: 'Cliente configuró preferencias', description: 'El cliente indicó sus preferencias (servicios, sucursal, horarios).' },
  { id: AUTOMATION_EVENTS.CLIENT_CONSENT_GIVEN, name: 'Cliente aceptó consentimiento', description: 'El cliente aceptó términos, políticas o preferencias de comunicación.' },
  { id: AUTOMATION_EVENTS.CLIENT_FIRST_VISIT, name: 'Cliente hizo su primera visita', description: 'El cliente realizó su primera visita/compra tras registrarse.' },
  { id: AUTOMATION_EVENTS.CLIENT_ONBOARDING_COMPLETED, name: 'Cliente completó el onboarding', description: 'El cliente terminó su proceso de activación inicial.' },
  { id: AUTOMATION_EVENTS.CLIENT_FIRST_PURCHASE, name: 'Cliente hizo su primera compra', description: 'El cliente completó su primera compra/consumo.' },
  { id: AUTOMATION_EVENTS.CLIENT_HIGH_VALUE_PURCHASE, name: 'Cliente hizo una compra de alto valor', description: 'El cliente realizó una compra por encima del promedio.' },
  { id: AUTOMATION_EVENTS.CLIENT_PROCESS_ABANDONED, name: 'Cliente abandonó un proceso', description: 'El cliente inició un proceso de compra/membresía y no lo completó.' },
  { id: AUTOMATION_EVENTS.CLIENT_FEEDBACK_GIVEN, name: 'Cliente dejó retroalimentación', description: 'El cliente respondió una encuesta o dejó feedback.' },
  { id: AUTOMATION_EVENTS.CLIENT_LOYALTY_ENROLLED, name: 'Cliente inscrito en fidelización', description: 'El cliente entró a un programa de fidelización.' },
  { id: AUTOMATION_EVENTS.CLIENT_FREQUENCY_DROP, name: 'Cliente bajó su frecuencia', description: 'El tiempo entre visitas/compras del cliente aumentó.' },
  { id: AUTOMATION_EVENTS.CLIENT_FREQUENCY_UP, name: 'Cliente subió su frecuencia', description: 'El cliente superó su frecuencia habitual.' },
  { id: AUTOMATION_EVENTS.CLIENT_FREQUENCY_GOAL, name: 'Cliente alcanzó meta de frecuencia', description: 'El cliente llegó a un objetivo de visitas/compras.' },
  { id: AUTOMATION_EVENTS.CLIENT_HIGH_ACTIVITY, name: 'Cliente con alta actividad', description: 'El cliente concentró varias visitas en poco tiempo.' },
  { id: AUTOMATION_EVENTS.CLIENT_BEHAVIOR_CHANGED, name: 'Cliente cambió su comportamiento', description: 'Cambió el patrón de horario, sucursal o gasto del cliente.' },
  { id: AUTOMATION_EVENTS.CLIENT_BENEFIT_UNDERUSED, name: 'Cliente no aprovecha beneficios', description: 'El cliente usa poco los beneficios disponibles.' },
  { id: AUTOMATION_EVENTS.CLIENT_CHURN_RISK, name: 'Cliente en riesgo de abandono', description: 'El comportamiento del cliente sugiere riesgo de abandono.' },
  { id: AUTOMATION_EVENTS.CLIENT_RISK_LEVEL_CHANGED, name: 'Cliente cambió de nivel de riesgo', description: 'El cliente pasó a otro estado del framework de recuperación.' },
  { id: AUTOMATION_EVENTS.CLIENT_INACTIVE, name: 'Cliente inactivo', description: 'El cliente no compra/visita desde el período configurado.' },
  { id: AUTOMATION_EVENTS.CLIENT_RECOVERED, name: 'Cliente recuperado', description: 'Un cliente en riesgo/inactivo volvió a estar activo.' },
  { id: AUTOMATION_EVENTS.CLIENT_CAMPAIGN_IGNORED, name: 'Cliente ignoró una campaña', description: 'El cliente no interactuó con una campaña dirigida.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_EXPIRED, name: 'Membresía vencida', description: 'La membresía/suscripción del cliente expiró.' },
  { id: AUTOMATION_EVENTS.BENEFIT_EXPIRING, name: 'Beneficio por vencer', description: 'Un beneficio del cliente está próximo a expirar.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_CREATED, name: 'Membresía creada', description: 'Se adquirió/creó una membresía (pendiente de activar).' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_ACTIVATED, name: 'Membresía activada', description: 'La membresía quedó activa y vigente.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_FIRST_USE, name: 'Primer uso de la membresía', description: 'El miembro usó por primera vez su membresía.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_RENEWED, name: 'Membresía renovada', description: 'La membresía se renovó (automática o manual).' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_UPGRADED, name: 'Membresía mejorada (upgrade)', description: 'El miembro subió de plan.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_DOWNGRADED, name: 'Membresía degradada (downgrade)', description: 'El miembro bajó de plan.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_SUSPENDED, name: 'Membresía suspendida', description: 'La membresía se suspendió temporalmente.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_REACTIVATED, name: 'Membresía reactivada', description: 'Una membresía suspendida volvió a activarse.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_CANCELLED, name: 'Membresía cancelada', description: 'El miembro canceló su membresía.' },
  { id: AUTOMATION_EVENTS.MEMBERSHIP_EXPIRING, name: 'Membresía por vencer', description: 'La membresía está próxima a expirar.' },
  { id: AUTOMATION_EVENTS.REFERRAL_CODE_GENERATED, name: 'Código de referido generado', description: 'El cliente obtuvo su código/enlace/QR de referido.' },
  { id: AUTOMATION_EVENTS.REFERRAL_SHARED, name: 'Invitación de referido compartida', description: 'El cliente compartió su invitación por algún canal.' },
  { id: AUTOMATION_EVENTS.REFERRAL_REGISTERED, name: 'Invitado se registró', description: 'Un invitado se registró con el código de referido.' },
  { id: AUTOMATION_EVENTS.REFERRAL_CONVERTED, name: 'Referido convirtió', description: 'El invitado cumplió la condición del programa (ej. primera compra).' },
  { id: AUTOMATION_EVENTS.REFERRAL_REWARD_PENDING, name: 'Recompensa de referido pendiente', description: 'La recompensa está pendiente de validación/liberación.' },
  { id: AUTOMATION_EVENTS.REFERRAL_REWARD_RELEASED, name: 'Recompensa de referido liberada', description: 'Se liberó la recompensa del programa de referidos.' },
  { id: AUTOMATION_EVENTS.REFERRAL_REWARD_EXPIRED, name: 'Recompensa de referido vencida', description: 'La recompensa del referido expiró sin usarse.' },
  { id: AUTOMATION_EVENTS.REFERRAL_FRAUD_DETECTED, name: 'Fraude de referido detectado', description: 'El antifraude marcó un referido como sospechoso.' },
  { id: AUTOMATION_EVENTS.REFERRAL_REJECTED, name: 'Referido rechazado', description: 'Un referido fue rechazado por reglas/antifraude.' },
  { id: AUTOMATION_EVENTS.REFERRAL_AMBASSADOR_REACHED, name: 'Embajador detectado', description: 'Un cliente alcanzó el desempeño para ser embajador.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_LAUNCHED, name: 'Campaña lanzada', description: 'Se activó una campaña orquestada.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_PARTICIPATED, name: 'Participación en campaña', description: 'Un cliente participó en una campaña.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_CONVERTED, name: 'Conversión de campaña', description: 'Un cliente convirtió dentro de una campaña.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_PAUSED, name: 'Campaña pausada', description: 'Se pausó una campaña.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_RESUMED, name: 'Campaña reanudada', description: 'Se reanudó una campaña pausada.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_FINISHED, name: 'Campaña finalizada', description: 'Una campaña terminó su ejecución.' },
  { id: AUTOMATION_EVENTS.CAMPAIGN_CHILD_STARTED, name: 'Campaña hija iniciada', description: 'Una campaña disparó una campaña hija/derivada.' },
  { id: AUTOMATION_EVENTS.GAMI_MISSION_STARTED, name: 'Misión iniciada', description: 'Se asignó/inició una misión al cliente.' },
  { id: AUTOMATION_EVENTS.GAMI_STREAK_RECOVERED, name: 'Racha recuperada', description: 'El cliente recuperó una racha perdida.' },
  { id: AUTOMATION_EVENTS.GAMI_LEVEL_DOWN, name: 'Descenso de nivel', description: 'El cliente bajó de nivel por inactividad/reglas.' },
  { id: AUTOMATION_EVENTS.GAMI_BADGE_UNLOCKED, name: 'Insignia desbloqueada', description: 'El cliente desbloqueó una insignia/logro.' },
  { id: AUTOMATION_EVENTS.GAMI_RANKING_UPDATED, name: 'Ranking actualizado', description: 'Se actualizó el ranking de gamificación.' },
  { id: AUTOMATION_EVENTS.GAMI_CHALLENGE_COMPLETED, name: 'Desafío completado', description: 'El cliente completó un desafío.' },
  { id: AUTOMATION_EVENTS.GAMI_COMPETITION_STARTED, name: 'Competencia iniciada', description: 'Comenzó una competencia de gamificación.' },
  { id: AUTOMATION_EVENTS.GAMI_COMPETITION_FINISHED, name: 'Competencia finalizada', description: 'Terminó una competencia y se premió a los ganadores.' },
  { id: AUTOMATION_EVENTS.GAMI_GOAL_REACHED, name: 'Meta alcanzada', description: 'El cliente alcanzó una meta de gamificación.' },
  { id: AUTOMATION_EVENTS.GAMI_GROUP_GOAL_REACHED, name: 'Meta grupal alcanzada', description: 'Un grupo/equipo alcanzó una meta colectiva.' },
  { id: AUTOMATION_EVENTS.DECISION_MADE, name: 'Decisión tomada', description: 'El Decision Engine produjo una decisión (no ejecuta acciones).' },
  { id: AUTOMATION_EVENTS.RECOMMENDATION_READY, name: 'Recomendación lista', description: 'El Recommendation Engine produjo una recomendación para el Action Engine.' },
  { id: AUTOMATION_EVENTS.OPPORTUNITY_DETECTED, name: 'Oportunidad detectada', description: 'Se detectó una oportunidad (VIP, upgrade, programa especial).' },
  { id: AUTOMATION_EVENTS.RISK_DETECTED, name: 'Riesgo detectado', description: 'Se detectó un riesgo (abandono, no renovación).' },
  { id: AUTOMATION_EVENTS.NEXT_BEST_ACTION_READY, name: 'Siguiente mejor acción lista', description: 'El Decision Engine determinó la siguiente mejor acción.' },
  { id: AUTOMATION_EVENTS.AUTOMATION_STARTED, name: 'Automatización iniciada', description: 'Comenzó una ejecución.' },
  { id: AUTOMATION_EVENTS.AUTOMATION_FINISHED, name: 'Automatización finalizada', description: 'Terminó una ejecución.' },
]
