/**
 * Car Wash Membership Strategy Library (Fase F1.1).
 *
 * Catálogo profesional de MODELOS de membresía documentados según el estándar
 * F1.1 (24 campos: problema, cuándo usar/no, ventajas, riesgos, KPIs, integración
 * con motores…). Cada estrategia es un patrón reutilizable, no un plan concreto,
 * y apunta a sus VARIANTES instalables (`MembershipTemplate` en `carwash.ts`).
 *
 * Datos, no lógica: la especificidad de Car Wash vive aquí como configuración.
 * El Membership Engine y los demás motores no cambian.
 */

import type { MembershipPlanType } from '../domain/types'
import type { MembershipStrategy } from './strategy-types'
import type { MembershipObjective, MembershipAudience } from './taxonomy'
import type { MembershipTemplate } from './types'
import { getCarwashTemplate } from './carwash'

export const CARWASH_MEMBERSHIP_STRATEGIES: readonly MembershipStrategy[] = [
  {
    id: 'carwash.membership.unlimited',
    industry: 'carwash',
    model: 'UNLIMITED',
    name: 'Unlimited Wash Membership',
    description: 'Lavados ilimitados por una cuota fija mensual; el modelo de suscripción estándar de la industria Car Wash.',
    objective: ['retencion', 'frecuencia', 'fidelizacion'],
    audience: ['individual', 'frecuentes'],
    problemSolved: 'Ingresos impredecibles y baja recurrencia: convierte pagos por visita en una cuota recurrente predecible.',
    whenToUse: 'Cuando el costo marginal por lavado es bajo y se busca maximizar frecuencia y flujo recurrente.',
    whenNotToUse: 'Cuando el costo por servicio es alto (detailing) o la capacidad operativa no soporta uso intensivo.',
    advantages: ['Ingreso recurrente predecible', 'Alta frecuencia de visita', 'Fideliza por hábito', 'Simple de comunicar'],
    disadvantages: ['Riesgo de sobreuso', 'Margen sensible al costo por lavado', 'Requiere control de abuso'],
    risks: ['Miembros de alto uso erosionan margen', 'Colas en horas pico', 'Compartir cuenta entre vehículos'],
    complexity: 'baja',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'benefit'],
    automationPlaybooks: ['recordatorio_renovacion', 'reactivacion_inactivos', 'aviso_por_vencer'],
    compatibleBenefits: ['descuento_detailing_10', 'linea_rapida', 'puntos_dobles'],
    compatiblePromotions: ['primer_mes_descuento', 'referido_gana'],
    compatibleCampaigns: ['captacion_suscripcion', 'winback_vencidos'],
    compatibleGamification: ['racha_visitas', 'nivel_por_frecuencia'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'retencion', 'churn', 'ltv'],
    bestPractices: ['Limitar a 1 lavado/día con intervalo mínimo', 'Segmentar por servicio para proteger margen', 'Renovación automática con aviso previo'],
    commonMistakes: ['No poner límite diario', 'Incluir detailing en el ilimitado', 'No medir uso por miembro'],
    variantKeys: ['carwash.unlimited_basic', 'carwash.unlimited_premium', 'carwash.unlimited_wash_vacuum', 'carwash.unlimited_wash_wax', 'carwash.unlimited_complete', 'carwash.unlimited_vip'],
    version: '1.0.0',
    technicalNotes: 'Enforcement vía UsageTracker (maxPerPeriod + minIntervalMinutes). Reglas de abuso como BEL en config.limits.customRules.',
  },
  {
    id: 'carwash.membership.credits',
    industry: 'carwash',
    model: 'CREDITS',
    name: 'Wash Credits Membership',
    description: 'Cuota mensual que otorga una cantidad fija de créditos o lavados canjeables; controla el consumo y protege el margen frente al modelo ilimitado.',
    objective: ['retencion', 'frecuencia', 'ticket_promedio', 'fidelizacion'],
    audience: ['individual', 'frecuentes', 'nuevos'],
    problemSolved: 'Sobreuso y erosion de margen del ilimitado: fija el consumo con un banco de créditos predecible por costo y por visita.',
    whenToUse: 'Cuando el costo por servicio es medio-alto o se busca predecir consumo y proteger margen sin renunciar a la recurrencia.',
    whenNotToUse: 'Cuando se quiere maximizar frecuencia de hábito puro y el costo marginal por lavado es muy bajo (ahí conviene ilimitado).',
    advantages: ['Consumo predecible y margen protegido', 'Permite escalonar paquetes por volumen', 'Fomenta el canje y la visita planificada', 'Facilita upselling a paquetes mayores'],
    disadvantages: ['Menos "hábito" que el ilimitado', 'Gestión de créditos no usados (rollover/caducidad)', 'Comunicación más compleja que cuota plana'],
    risks: ['Acumulación de créditos y pasivo diferido', 'Percepción de perder créditos genera churn', 'Canje concentrado en fin de periodo satura capacidad'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'benefit', 'reward'],
    automationPlaybooks: ['recordatorio_renovacion', 'aviso_creditos_por_vencer', 'sugerencia_upgrade_paquete', 'reactivacion_inactivos'],
    compatibleBenefits: ['rollover_creditos', 'creditos_bonus_renovacion', 'canje_detailing_con_credito', 'linea_rapida'],
    compatiblePromotions: ['creditos_extra_primer_mes', 'referido_gana_creditos', 'paquete_anual_descuento'],
    compatibleCampaigns: ['captacion_paquete_creditos', 'winback_creditos_caducados'],
    compatibleGamification: ['bonus_por_canje', 'nivel_por_paquete'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'tasa_renovacion', 'churn', 'ltv'],
    bestPractices: ['Definir política clara de caducidad y rollover parcial', 'Escalonar paquetes (basic/premium/max) por costo unitario decreciente', 'Alertar créditos por vencer para inducir visita', 'Permitir canje flexible entre servicios según valor'],
    commonMistakes: ['Créditos que caducan sin aviso previo', 'No diferenciar valor de crédito por tipo de servicio', 'Paquetes sin incentivo de volumen real', 'Ignorar el pasivo de créditos acumulados'],
    variantKeys: ['carwash.credits_basic', 'carwash.credits_premium', 'carwash.credits_max'],
    version: '1.0.0',
    technicalNotes: 'UsageTracker descuenta del saldo (config.credits) por cada canje; caducidad y rollover se modelan como BEL rules en config.limits.customRules con jobs de renovación.',
  },
  {
    id: 'carwash.membership.hybrid',
    industry: 'carwash',
    model: 'HYBRID',
    name: 'Hybrid Membership',
    description: 'Combina un banco de créditos o lavados incluidos con beneficios y descuentos permanentes sobre servicios adicionales; equilibra recurrencia y ticket promedio.',
    objective: ['retencion', 'ticket_promedio', 'fidelizacion', 'upselling'],
    audience: ['individual', 'frecuentes', 'vip'],
    problemSolved: 'Rigidez de un modelo único: mezcla consumo incluido con incentivos de descuento para elevar ticket y cubrir servicios premium fuera del banco.',
    whenToUse: 'Cuando el catálogo tiene servicios de valor dispar (lavado básico + detailing) y se busca recurrencia base más upselling continuo.',
    whenNotToUse: 'Cuando se necesita máxima simplicidad de comunicación o el catálogo es homogéneo y de bajo costo.',
    advantages: ['Base recurrente + upsell con descuento', 'Flexible ante catálogo heterogéneo', 'Eleva ticket promedio por visita', 'Percepción de valor superior'],
    disadvantages: ['Mayor complejidad de reglas y comunicación', 'Requiere buen tooling de beneficios', 'Riesgo de canibalizar margen con descuentos'],
    risks: ['Descuentos mal calibrados erosionan margen premium', 'Confusión del cliente sobre qué incluye', 'Difícil de auditar sin motor de beneficios sólido'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    enginesUsed: ['membership', 'benefit', 'promotion', 'rule', 'action', 'automation', 'reward'],
    automationPlaybooks: ['recordatorio_renovacion', 'sugerencia_upsell_detailing', 'aviso_beneficio_no_usado', 'reactivacion_inactivos'],
    compatibleBenefits: ['descuento_detailing_20', 'lavado_incluido_mensual', 'linea_rapida', 'proteccion_lluvia', 'puntos_dobles'],
    compatiblePromotions: ['primer_mes_descuento', 'upgrade_gratis_temporada', 'referido_gana'],
    compatibleCampaigns: ['captacion_suscripcion', 'campana_upselling_premium', 'winback_vencidos'],
    compatibleGamification: ['nivel_por_gasto', 'racha_visitas', 'retos_de_servicio'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'retencion', 'churn', 'ltv', 'tasa_renovacion'],
    bestPractices: ['Definir claramente qué es incluido vs descontado', 'Calibrar descuentos para proteger margen de premium', 'Usar el motor de beneficios para reglas por servicio', 'Comunicar el valor total percibido del combo'],
    commonMistakes: ['Descuentos que canibalizan servicios rentables', 'Reglas ambiguas sobre inclusiones', 'No medir uso separado de créditos y beneficios', 'Sobrecargar el plan con demasiados beneficios'],
    variantKeys: ['carwash.hybrid'],
    version: '1.0.0',
    technicalNotes: 'UsageTracker gestiona el banco incluido (config.limits) mientras el Benefit Engine aplica descuentos permanentes como BEL rules; ambos se combinan en la evaluación de la transacción.',
  },
  {
    id: 'carwash.membership.tier',
    industry: 'carwash',
    model: 'TIER',
    name: 'Tiered Membership',
    description: 'Estructura de niveles escalonados (Silver/Gold/Platinum) con beneficios crecientes por precio; segmenta la disposición a pagar y habilita upgrades.',
    objective: ['retencion', 'ticket_promedio', 'fidelizacion', 'upselling'],
    audience: ['individual', 'frecuentes', 'vip'],
    problemSolved: 'Un solo plan no captura la disposición a pagar: los niveles segmentan clientes y crean una ruta natural de upgrade y aspiracional.',
    whenToUse: 'Cuando existe diversidad clara de necesidades y presupuestos y se quiere maximizar ingreso por segmentación y upselling.',
    whenNotToUse: 'Cuando la base es pequeña u homogénea; demasiados niveles generan parálisis de decisión y complejidad operativa.',
    advantages: ['Segmenta disposición a pagar', 'Ruta clara de upgrade', 'Nivel premium eleva ticket', 'Efecto aspiracional y de estatus'],
    disadvantages: ['Más complejo de gestionar y comunicar', 'Riesgo de canibalización entre niveles', 'Requiere diferenciación real de valor'],
    risks: ['Niveles poco diferenciados confunden', 'Downgrade masivo si el valor no se percibe', 'Costo de servir Platinum supera su margen'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    enginesUsed: ['membership', 'benefit', 'rule', 'action', 'automation', 'reward', 'gamification'],
    automationPlaybooks: ['recordatorio_renovacion', 'oferta_upgrade_nivel', 'aviso_beneficio_por_nivel', 'retencion_pre_downgrade'],
    compatibleBenefits: ['linea_rapida_prioritaria', 'detailing_incluido_platinum', 'lavados_ilimitados_gold', 'proteccion_ceramica', 'atencion_vip'],
    compatiblePromotions: ['upgrade_sin_costo_prueba', 'primer_mes_gold_descuento', 'referido_sube_nivel'],
    compatibleCampaigns: ['captacion_por_nivel', 'campana_upgrade_silver_gold', 'winback_vencidos'],
    compatibleGamification: ['ascenso_de_nivel', 'estatus_por_antiguedad', 'beneficios_desbloqueables'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'retencion', 'churn', 'ltv', 'tasa_renovacion'],
    bestPractices: ['Diferenciar valor real y visible entre niveles', 'Limitar a 3 niveles para evitar parálisis', 'Diseñar el nivel medio como ancla de conversión', 'Automatizar ofertas de upgrade por comportamiento'],
    commonMistakes: ['Niveles con diferencias marginales', 'Sobrecomprometer beneficios en Platinum', 'No incentivar el salto de nivel', 'Precios sin lógica de anclaje'],
    variantKeys: ['carwash.tier_silver', 'carwash.tier_gold', 'carwash.tier_platinum'],
    version: '1.0.0',
    technicalNotes: 'Cada nivel es una config de membership con sus config.limits y beneficios; los upgrades/downgrades cambian el tier activo (service.changePlan) y el Benefit Engine resuelve prestaciones vía BEL rules por nivel.',
  },
  {
    id: 'carwash.membership.family',
    industry: 'carwash',
    model: 'FAMILY',
    name: 'Family Membership',
    description: 'Una sola cuota cubre varios vehículos de un mismo hogar bajo límites compartidos o por vehículo; aumenta el valor del hogar y la retención.',
    objective: ['retencion', 'frecuencia', 'fidelizacion', 'ticket_promedio'],
    audience: ['familias', 'individual', 'frecuentes'],
    problemSolved: 'Hogares con múltiples autos pagan por separado o no se suscriben: un plan multivehículo captura todo el gasto del hogar con conveniencia.',
    whenToUse: 'En mercados con alta penetración de segundo vehículo por hogar y cuando se busca elevar el valor y la pegajosidad por hogar.',
    whenNotToUse: 'Cuando predomina el vehículo único o no hay control para evitar que se comparta la membresía fuera del hogar.',
    advantages: ['Mayor valor y retención por hogar', 'Conveniencia que reduce churn', 'Eleva ingreso por cuenta', 'Barrera de salida por múltiples vehículos'],
    disadvantages: ['Riesgo de compartir fuera del hogar', 'Control de vehículos y placas más complejo', 'Definir límites compartidos vs por vehículo'],
    risks: ['Abuso por vehículos no registrados', 'Sobreuso agregado en horas pico', 'Disputas sobre cupos entre miembros del hogar'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'motocicleta'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'benefit'],
    automationPlaybooks: ['recordatorio_renovacion', 'alta_vehiculo_adicional', 'aviso_por_vencer', 'reactivacion_inactivos'],
    compatibleBenefits: ['vehiculo_adicional_descuento', 'linea_rapida', 'lavado_cumpleanos', 'puntos_dobles'],
    compatiblePromotions: ['segundo_vehiculo_gratis_mes', 'referido_familiar', 'primer_mes_descuento'],
    compatibleCampaigns: ['captacion_familias', 'campana_multivehiculo', 'winback_vencidos'],
    compatibleGamification: ['racha_familiar', 'meta_de_hogar'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'retencion', 'churn', 'ltv', 'tasa_renovacion'],
    bestPractices: ['Registrar vehículos por placa y limitar altas/bajas', 'Definir límites por vehículo para evitar sobreuso', 'Precio incremental por vehículo adicional', 'Verificar pertenencia al hogar en el alta'],
    commonMistakes: ['No limitar el número de vehículos', 'Permitir cambios de placa ilimitados', 'Ignorar el uso agregado del hogar', 'No auditar reparto entre vehículos'],
    variantKeys: ['carwash.family', 'carwash.family_premium'],
    version: '1.0.0',
    technicalNotes: 'La membresía agrupa múltiples vehículos (config.limits.maxVehicles) con UsageTracker por vehículo o compartido; reglas anti-abuso por placa se modelan como BEL rules.',
  },
  {
    id: 'carwash.membership.fleet',
    industry: 'carwash',
    model: 'FLEET',
    name: 'Fleet Membership',
    description: 'Programa B2B para empresas con flota: múltiples vehículos, facturación consolidada y tarifas por volumen con reporting de uso; enfocado en retención corporativa.',
    objective: ['retencion', 'frecuencia', 'fidelizacion', 'captacion'],
    audience: ['empresas', 'flotas'],
    problemSolved: 'Empresas con muchos vehículos necesitan control de gasto, facturación única y tarifas por volumen que el plan individual no ofrece.',
    whenToUse: 'Para captar clientes corporativos (rent-a-car, logística, taxis) con flotas que requieren consolidación, reporting y precios escalonados.',
    whenNotToUse: 'Cuando no existe demanda B2B local o no se dispone de capacidad operativa y administrativa para servir volumen y facturación empresarial.',
    advantages: ['Volumen y flujo recurrente alto', 'Facturación consolidada B2B', 'Contratos de mayor permanencia', 'Reporting de uso por vehículo/centro de costo'],
    disadvantages: ['Ciclo de venta y negociación más largo', 'Requiere reporting y facturación robustos', 'Márgenes presionados por descuento de volumen'],
    risks: ['Concentración de ingresos en pocos clientes', 'Sobreuso en horas pico satura capacidad', 'Impago o morosidad corporativa', 'Dependencia de un contrato grande'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'benefit', 'analytics'],
    automationPlaybooks: ['renovacion_contrato_flota', 'reporte_uso_mensual', 'alerta_sobreuso_flota', 'recordatorio_facturacion'],
    compatibleBenefits: ['tarifa_por_volumen', 'facturacion_consolidada', 'linea_prioritaria_flota', 'gestor_de_cuenta'],
    compatiblePromotions: ['descuento_volumen_flota', 'periodo_prueba_corporativo', 'referido_empresa'],
    compatibleCampaigns: ['captacion_b2b', 'renovacion_contratos', 'expansion_flota'],
    compatibleGamification: ['ranking_por_centro_costo', 'meta_de_flota'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'retencion', 'churn', 'ltv', 'tasa_renovacion'],
    bestPractices: ['Tarifas escalonadas por número de vehículos', 'Reporting de uso por vehículo y centro de costo', 'Asignar gestor de cuenta para retención', 'Contratos con permanencia y SLA de capacidad'],
    commonMistakes: ['Descuentos de volumen que borran el margen', 'No entregar reporting de uso', 'Ignorar el impacto en capacidad en horas pico', 'Depender de un único gran contrato'],
    variantKeys: ['carwash.fleet', 'carwash.fleet_small'],
    version: '1.0.0',
    technicalNotes: 'La cuenta corporativa agrupa N vehículos con UsageTracker agregado y por unidad; tarifas por volumen y facturación consolidada se resuelven vía BEL rules en config.limits y el Analytics Engine genera el reporting.',
  },
  {
    id: 'carwash.membership.corporate',
    industry: 'carwash',
    model: 'CORPORATE',
    name: 'Corporate Membership',
    description: 'La empresa paga una membresía de lavado como beneficio para sus empleados o flota; contratos B2B con facturación mensual consolidada.',
    objective: ['captacion', 'retencion', 'fidelizacion'],
    audience: ['empresas', 'flotas', 'vip'],
    problemSolved: 'Baja utilización en horas valle y falta de volumen predecible: asegura demanda recurrente mediante contratos corporativos con pago centralizado.',
    whenToUse: 'Cuando existen empresas cercanas con flotas o interés en beneficios para empleados y se busca ocupar capacidad ociosa entre semana.',
    whenNotToUse: 'Cuando no hay tejido empresarial en la zona o la operación no puede emitir facturación B2B ni gestionar cuentas por cobrar.',
    advantages: ['Volumen predecible y facturación consolidada', 'Llena horas valle entre semana', 'Ticket contractual estable con menor rotacion'],
    disadvantages: ['Ciclo de venta largo y consultivo', 'Requiere gestión de cuentas por cobrar', 'Dependencia de pocos clientes grandes'],
    risks: ['Concentración de ingresos en un contrato', 'Impago o mora corporativa', 'Uso pico simultáneo de flota satura estaciones'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'benefit', 'analytics', 'decision'],
    automationPlaybooks: ['facturacion_mensual_corporativa', 'onboarding_empresa', 'reporte_uso_flota'],
    compatibleBenefits: ['tarifa_corporativa', 'linea_rapida', 'facturacion_consolidada'],
    compatiblePromotions: ['descuento_por_volumen', 'prueba_flota_gratis'],
    compatibleCampaigns: ['captacion_b2b', 'renovacion_contratos'],
    compatibleGamification: ['ranking_uso_flota'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'retencion', 'tasa_renovacion', 'ltv'],
    bestPractices: ['Definir cupos por vehículo y validar por patente/empleado', 'Contratos con renovación anual y SLA de servicio', 'Reportes de uso mensual al responsable de cuenta'],
    commonMistakes: ['No limitar uso por vehículo generando abuso', 'Descuentos por volumen que erosionan margen', 'No formalizar términos de pago y mora'],
    variantKeys: ['carwash.corporate'],
    version: '1.0.0',
    technicalNotes: 'Vinculación de vehículos/empleados vía config.segments; facturación por Automation Engine (playbook facturacion_mensual_corporativa). Cupos y validación como reglas en config.limits.',
  },
  {
    id: 'carwash.membership.seasonal',
    industry: 'carwash',
    model: 'SEASONAL',
    name: 'Seasonal Membership',
    description: 'Membresía de temporada con duración fija (verano, época de lluvias, invierno) que agrupa lavados durante un periodo determinado.',
    objective: ['captacion', 'frecuencia', 'recuperacion'],
    audience: ['individual', 'nuevos', 'frecuentes'],
    problemSolved: 'Estacionalidad de la demanda: captura ingresos concentrados en periodos de alta necesidad (barro por lluvia, polvo por verano) sin comprometer al cliente todo el año.',
    whenToUse: 'Cuando la demanda tiene picos climáticos claros y se quiere convertir esa necesidad temporal en un paquete prepago.',
    whenNotToUse: 'Cuando el clima es estable todo el año o se busca recurrencia permanente en lugar de ingresos por temporada.',
    advantages: ['Ingreso anticipado en el pico de demanda', 'Baja fricción de compromiso para el cliente', 'Puerta de entrada hacia membresías anuales'],
    disadvantages: ['Ingresos concentrados y no recurrentes', 'Requiere recaptación al cerrar la temporada', 'Ociosidad fuera de temporada'],
    risks: ['Sobreventa frente a clima impredecible', 'Alta caída al terminar la temporada', 'Percepción de vencimiento como pérdida de valor'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'promotion', 'campaign'],
    automationPlaybooks: ['recordatorio_fin_temporada', 'conversion_a_anual', 'lanzamiento_temporada'],
    compatibleBenefits: ['lavados_prepagados', 'precio_congelado_temporada'],
    compatiblePromotions: ['preventa_temporada', 'upgrade_a_anual'],
    compatibleCampaigns: ['captacion_temporada', 'winback_fin_temporada'],
    compatibleGamification: ['reto_temporada', 'sello_por_visita'],
    kpis: ['uso_promedio', 'visitas_promedio', 'rentabilidad_por_miembro', 'tasa_renovacion', 'churn'],
    bestPractices: ['Definir ventana de vigencia clara con fecha de inicio y fin', 'Ofrecer conversión a plan anual antes del vencimiento', 'Dimensionar cupos según capacidad para no saturar el pico'],
    commonMistakes: ['No planificar la recaptación al cierre', 'Vender lavados ilimitados en temporada de alta demanda', 'No comunicar la fecha de vencimiento con anticipación'],
    variantKeys: ['carwash.seasonal'],
    version: '1.0.0',
    technicalNotes: 'Vigencia fija vía durationDays/periodicity SEASONAL; expiración y conversión gestionadas por Automation Engine. Bolsa de lavados como límite consumible en config.limits.',
  },
  {
    id: 'carwash.membership.premium',
    industry: 'carwash',
    model: 'PREMIUM',
    name: 'Premium Service Membership',
    description: 'Membresía de alto valor centrada en detailing, protección de pintura y cuidado especializado para vehículos de alta gama.',
    objective: ['ticket_promedio', 'fidelizacion', 'upselling'],
    audience: ['vip', 'individual', 'frecuentes'],
    problemSolved: 'Margen bajo del lavado básico y ausencia de propuesta para clientes exigentes: monetiza servicios premium recurrentes con alto valor percibido.',
    whenToUse: 'Cuando existe una base de clientes con vehículos de lujo o alta gama dispuesta a pagar por detailing y protección periódica.',
    whenNotToUse: 'Cuando la demanda es sensible al precio o la operación no cuenta con personal e insumos para detailing de calidad.',
    advantages: ['Ticket promedio elevado y mejor margen', 'Alta fidelización por servicio especializado', 'Diferenciación frente a lavado de commodity'],
    disadvantages: ['Costo por servicio alto y mano de obra especializada', 'Menor volumen y base de clientes acotada', 'Expectativas de calidad muy exigentes'],
    risks: ['Rotación de personal técnico calificado', 'Daño a vehículo de lujo genera reclamos costosos', 'Sobrepromesa de resultados de protección'],
    complexity: 'alta',
    compatibleServices: ['lavado_premium', 'detailing', 'lavado_interior', 'lavado_exterior'],
    compatibleVehicles: ['lujo', 'sedan', 'suv'],
    enginesUsed: ['membership', 'benefit', 'rule', 'action', 'automation', 'reward', 'analytics'],
    automationPlaybooks: ['agenda_detailing_periodico', 'seguimiento_postservicio', 'recordatorio_proteccion'],
    compatibleBenefits: ['detailing_trimestral', 'proteccion_ceramica', 'concierge_vip', 'linea_rapida'],
    compatiblePromotions: ['upgrade_premium', 'primer_detailing_descuento'],
    compatibleCampaigns: ['captacion_vip', 'fidelizacion_lujo'],
    compatibleGamification: ['nivel_vip', 'recompensa_por_antiguedad'],
    kpis: ['rentabilidad_por_miembro', 'ltv', 'uso_promedio', 'retencion', 'tasa_renovacion'],
    bestPractices: ['Agendar servicios por cita para controlar calidad y tiempos', 'Documentar estado del vehículo antes de cada servicio', 'Incluir beneficios exclusivos que refuercen el estatus'],
    commonMistakes: ['Incluir detailing en un esquema ilimitado', 'No documentar el vehículo y exponerse a reclamos', 'Diluir la marca premium con descuentos agresivos'],
    variantKeys: ['carwash.premium_service', 'carwash.premium_detailing'],
    version: '1.0.0',
    technicalNotes: 'Beneficios agendables por cita gestionados vía Benefit Engine + Automation Engine (agenda_detailing_periodico). Sin ilimitado en config.limits; créditos de detailing por periodo.',
  },
  {
    id: 'carwash.membership.maintenance',
    industry: 'carwash',
    model: 'MAINTENANCE',
    name: 'Maintenance Membership',
    description: 'Membresía de cuidado programado y recurrente que combina lavados e interior en un calendario fijo de mantenimiento del vehículo.',
    objective: ['retencion', 'frecuencia', 'fidelizacion'],
    audience: ['individual', 'familias', 'frecuentes'],
    problemSolved: 'Falta de hábito y visitas irregulares: instala una rutina de cuidado programado que estabiliza la frecuencia y el ingreso recurrente.',
    whenToUse: 'Cuando se busca convertir clientes ocasionales en usuarios de rutina con un plan de cuidado periódico predecible.',
    whenNotToUse: 'Cuando el cliente prefiere flexibilidad total o la demanda es puramente impulsiva sin patrón de mantenimiento.',
    advantages: ['Ingreso recurrente y frecuencia estable', 'Facilita planificación de capacidad', 'Refuerza el hábito de cuidado del vehículo'],
    disadvantages: ['Menos atractivo para usuarios de uso intensivo', 'Requiere buen sistema de agenda y recordatorios', 'Percepción de rigidez frente a planes ilimitados'],
    risks: ['Cancelación si el cliente percibe visitas no usadas', 'Descoordinación de agenda genera colas', 'Erosión de margen si se incluye interior en cada visita'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'motocicleta'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'benefit', 'reward'],
    automationPlaybooks: ['recordatorio_cita_programada', 'renovacion_automatica', 'reactivacion_visita_perdida'],
    compatibleBenefits: ['plan_cuidado_mensual', 'interior_incluido_mensual', 'linea_rapida'],
    compatiblePromotions: ['primer_mes_descuento', 'referido_gana'],
    compatibleCampaigns: ['captacion_rutina', 'winback_inactivos'],
    compatibleGamification: ['racha_visitas', 'recompensa_por_constancia'],
    kpis: ['visitas_promedio', 'uso_promedio', 'retencion', 'churn', 'tasa_renovacion', 'rentabilidad_por_miembro'],
    bestPractices: ['Definir cadencia clara (ej. 4 exteriores + 1 interior al mes)', 'Recordatorios automáticos de cita para maximizar uso', 'Renovación automática con aviso previo'],
    commonMistakes: ['Incluir interior ilimitado y erosionar margen', 'No enviar recordatorios y provocar visitas no usadas', 'Cadencia confusa que el cliente no entiende'],
    variantKeys: ['carwash.maintenance'],
    version: '1.0.0',
    technicalNotes: 'Cadencia y cupos por periodo en config.limits (maxPerPeriod por tipo de servicio); recordatorios y renovación vía Automation Engine. Uso rastreado por UsageTracker para detectar visitas no consumidas.',
  },
  {
    id: 'carwash.membership.pay_per_visit',
    industry: 'carwash',
    model: 'PAY_PER_VISIT',
    name: 'Pay Per Visit Membership',
    description: 'Membresía sin cuota mensual: el cliente se afilia gratis y accede a precio preferencial y beneficios pagando por cada visita.',
    objective: ['captacion', 'retencion', 'ticket_promedio'],
    audience: ['nuevos', 'individual', 'frecuentes'],
    problemSolved: 'Resistencia al compromiso de una cuota fija: capta clientes sin barrera de entrada y los fideliza mediante precio preferencial y datos de visita.',
    whenToUse: 'Cuando la frecuencia es baja o impredecible y se busca capturar y fidelizar sin la fricción de una suscripción mensual.',
    whenNotToUse: 'Cuando se busca ingreso recurrente predecible o el modelo de negocio depende de cuotas mensuales garantizadas.',
    advantages: ['Sin barrera de entrada, capta muchos afiliados', 'Genera base de datos para marketing y upselling', 'Sin riesgo de sobreuso ni cuota no rentabilizada'],
    disadvantages: ['Ingreso no recurrente ni predecible', 'Menor fidelización que una suscripción de pago', 'Requiere estímulos constantes para generar visitas'],
    risks: ['Afiliados inactivos que nunca vuelven', 'Descuento preferencial sin lograr recurrencia', 'Canibalización de clientes que pagarían tarifa plena'],
    complexity: 'baja',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van', 'camion_ligero', 'lujo'],
    enginesUsed: ['membership', 'rule', 'action', 'benefit', 'promotion', 'reward', 'referral', 'automation'],
    automationPlaybooks: ['reactivacion_inactivos', 'nudge_segunda_visita', 'upsell_a_suscripcion'],
    compatibleBenefits: ['precio_preferencial', 'acumulacion_puntos', 'linea_rapida'],
    compatiblePromotions: ['afiliacion_gratis', 'referido_gana', 'quinta_visita_gratis'],
    compatibleCampaigns: ['captacion_afiliados', 'winback_inactivos', 'conversion_a_suscripcion'],
    compatibleGamification: ['puntos_por_visita', 'recompensa_por_frecuencia'],
    kpis: ['visitas_promedio', 'churn', 'ltv', 'rentabilidad_por_miembro', 'retencion'],
    bestPractices: ['Usar la afiliación gratuita para capturar datos y consentimiento de marketing', 'Estimular la segunda visita con incentivo inmediato', 'Ofrecer conversión a suscripción a los afiliados más frecuentes'],
    commonMistakes: ['Dar descuento preferencial sin capturar datos ni fomentar retorno', 'No diferenciar el precio del cliente sin afiliar', 'Descuidar la reactivación de afiliados inactivos'],
    variantKeys: ['carwash.pay_per_visit'],
    version: '1.0.0',
    technicalNotes: 'Sin cuota recurrente: periodicity NONE; precio preferencial aplicado por Benefit Engine en cada transacción. Segmentación por frecuencia vía Analytics Engine para disparar upsell_a_suscripcion.',
  },
  {
    id: 'carwash.membership.loyalty',
    industry: 'carwash',
    model: 'LOYALTY',
    name: 'Loyalty Membership',
    description: 'Programa de fidelización por acumulación: cada N lavados pagados, el cliente obtiene uno gratis; sin cuota recurrente.',
    objective: ['fidelizacion', 'frecuencia', 'retencion'],
    audience: ['individual', 'frecuentes', 'nuevos'],
    problemSolved: 'Baja repetición de visitas: crea un incentivo de retorno acumulable sin comprometer al cliente con un pago fijo mensual.',
    whenToUse: 'Cuando se busca aumentar frecuencia con baja fricción de entrada y sin obligar a suscripción recurrente.',
    whenNotToUse: 'Cuando se necesita ingreso recurrente predecible o cuando el margen no soporta lavados gratis periódicos.',
    advantages: ['Baja fricción de adhesión', 'Incentivo claro al retorno', 'Fácil de comunicar', 'No requiere compromiso de pago fijo'],
    disadvantages: ['No genera ingreso recurrente', 'Recompensa a clientes que ya venían', 'Efecto limitado sobre ticket promedio'],
    risks: ['Canibalización de visitas ya habituales', 'Fraude por acumulación indebida', 'Costo del lavado gratis erosiona margen si mal calibrado'],
    complexity: 'baja',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    enginesUsed: ['reward', 'rule', 'action', 'membership', 'automation'],
    automationPlaybooks: ['recordatorio_proximo_premio', 'reactivacion_inactivos'],
    compatibleBenefits: ['lavado_gratis_acumulado', 'linea_rapida'],
    compatiblePromotions: ['doble_sello_fin_semana', 'referido_gana'],
    compatibleCampaigns: ['captacion_fidelizacion', 'winback_inactivos'],
    compatibleGamification: ['tarjeta_sellos', 'racha_visitas'],
    kpis: ['visitas_promedio', 'retencion', 'churn', 'ltv', 'uso_promedio'],
    bestPractices: ['Definir umbral N según margen por lavado', 'Comunicar el progreso hacia el premio en cada visita', 'Fijar caducidad de sellos para incentivar frecuencia'],
    commonMistakes: ['Umbral demasiado bajo que regala margen', 'No controlar fraude de acumulación', 'No recordar al cliente su progreso'],
    variantKeys: ['carwash.loyalty'],
    version: '1.0.0',
    technicalNotes: 'Acumulación gestionada por Reward Engine (contador de visitas + trigger de recompensa al alcanzar N); sin cobro recurrente en Membership Engine.',
  },
  {
    id: 'carwash.membership.prepaid',
    industry: 'carwash',
    model: 'PREPAID',
    name: 'Prepaid Membership',
    description: 'El cliente paga varios meses por adelantado y recibe meses adicionales gratis; anticipa ingreso y asegura permanencia.',
    objective: ['retencion', 'fidelizacion', 'ticket_promedio'],
    audience: ['individual', 'frecuentes', 'familias'],
    problemSolved: 'Flujo de caja irregular y baja permanencia: adelanta ingreso y bloquea al cliente durante el periodo prepagado.',
    whenToUse: 'Cuando se busca capital de trabajo por adelantado y asegurar permanencia de clientes ya convencidos.',
    whenNotToUse: 'Cuando el cliente es nuevo y aún no confía en el servicio, o cuando la regulación limita cobros anticipados.',
    advantages: ['Ingreso adelantado y flujo de caja', 'Alta permanencia durante el periodo', 'Reduce churn a corto plazo', 'Incentivo de ahorro percibido'],
    disadvantages: ['Descuento reduce margen unitario', 'Pasivo por servicio no entregado', 'Menor flexibilidad para el cliente'],
    risks: ['Obligación de servicio futuro si cierra o cambia precios', 'Reembolsos y disputas', 'Sobreuso concentrado en meses gratis'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    enginesUsed: ['membership', 'rule', 'action', 'benefit', 'automation'],
    automationPlaybooks: ['recordatorio_vencimiento_prepago', 'oferta_renovacion_anticipada'],
    compatibleBenefits: ['meses_gratis_prepago', 'descuento_detailing_10'],
    compatiblePromotions: ['paga_10_lleva_12', 'upgrade_plan_anual'],
    compatibleCampaigns: ['captacion_prepago', 'renovacion_anticipada'],
    compatibleGamification: ['nivel_por_antiguedad', 'racha_visitas'],
    kpis: ['tasa_renovacion', 'retencion', 'ltv', 'rentabilidad_por_miembro', 'churn'],
    bestPractices: ['Calibrar meses gratis según margen y costo de capital', 'Ofrecer renovación anticipada antes del vencimiento', 'Registrar el prepago como pasivo diferido'],
    commonMistakes: ['Regalar demasiados meses y perder margen', 'No provisionar el servicio pendiente', 'No avisar el vencimiento con anticipación'],
    variantKeys: ['carwash.prepaid'],
    version: '1.0.0',
    technicalNotes: 'Membership Engine registra el prepago vía config.renewal.prepaidMonths/freeMonths; Benefit Engine libera los meses gratis al completar el pago anticipado.',
  },
  {
    id: 'carwash.membership.vip',
    industry: 'carwash',
    model: 'VIP',
    name: 'VIP Membership',
    description: 'Membresía premium de experiencia exclusiva: prioridad en fila, regalos, eventos y atención concierge por una cuota alta.',
    objective: ['fidelizacion', 'ticket_promedio', 'upselling', 'retencion'],
    audience: ['vip', 'individual', 'empresas'],
    problemSolved: 'Falta de diferenciación y baja monetización del segmento de alto valor: crea una oferta premium con margen elevado.',
    whenToUse: 'Cuando existe un segmento dispuesto a pagar por exclusividad, rapidez y trato preferente.',
    whenNotToUse: 'Cuando la base de clientes es sensible al precio o la operación no puede sostener servicio diferenciado.',
    advantages: ['Alto margen por miembro', 'Fideliza al segmento de mayor valor', 'Diferenciación de marca', 'Habilita upselling de detailing y extras'],
    disadvantages: ['Base de miembros pequeña', 'Costo operativo de beneficios y concierge', 'Exige consistencia de servicio premium'],
    risks: ['Incumplir la promesa de exclusividad daña la marca', 'Beneficios costosos erosionan margen', 'Dependencia de pocos miembros de alto valor'],
    complexity: 'alta',
    compatibleServices: ['lavado_premium', 'detailing', 'lavado_interior', 'aspirado', 'lavado_exterior'],
    compatibleVehicles: ['lujo', 'suv', 'sedan', 'pickup'],
    enginesUsed: ['membership', 'benefit', 'reward', 'rule', 'action', 'automation', 'analytics'],
    automationPlaybooks: ['bienvenida_concierge_vip', 'invitacion_eventos_exclusivos'],
    compatibleBenefits: ['linea_rapida_prioritaria', 'detailing_cortesia', 'regalo_bienvenida_vip'],
    compatiblePromotions: ['upgrade_a_platinum', 'invitado_vip_gratis'],
    compatibleCampaigns: ['captacion_alto_valor', 'reactivacion_vip'],
    compatibleGamification: ['nivel_vip_platinum', 'beneficios_por_estatus'],
    kpis: ['rentabilidad_por_miembro', 'ltv', 'retencion', 'tasa_renovacion', 'churn'],
    bestPractices: ['Garantizar prioridad real en horas pico', 'Sorprender con beneficios no anunciados', 'Asignar contacto concierge dedicado', 'Segmentar niveles VIP y Platinum'],
    commonMistakes: ['Prometer exclusividad sin capacidad operativa', 'Diluir el VIP con demasiados miembros', 'No medir rentabilidad real por miembro'],
    variantKeys: ['carwash.vip', 'carwash.vip_platinum'],
    version: '1.0.0',
    technicalNotes: 'Benefit Engine gestiona beneficios diferenciados por nivel (VIP/Platinum); Analytics Engine monitorea rentabilidad y uso por miembro de alto valor.',
  },
  {
    id: 'carwash.membership.rewards',
    industry: 'carwash',
    model: 'REWARDS',
    name: 'Membership + Rewards',
    description: 'Membresía con capa de gamificación: XP, puntos dobles, misiones y niveles que premian frecuencia y comportamiento.',
    objective: ['frecuencia', 'fidelizacion', 'upselling', 'retencion'],
    audience: ['individual', 'frecuentes', 'nuevos', 'familias'],
    problemSolved: 'Estancamiento del uso y baja interacción: usa mecánicas de juego para elevar frecuencia y gasto por visita.',
    whenToUse: 'Cuando se busca aumentar engagement y frecuencia en una base activa mediante recompensas dinámicas.',
    whenNotToUse: 'Cuando el público no responde a mecánicas de juego o cuando la operación no puede sostener recompensas variables.',
    advantages: ['Aumenta frecuencia y engagement', 'Habilita upselling vía misiones', 'Datos ricos de comportamiento', 'Diferenciación de experiencia'],
    disadvantages: ['Mayor complejidad técnica', 'Costo de recompensas y puntos', 'Requiere contenido y misiones frescas'],
    risks: ['Inflación de puntos que erosiona margen', 'Fatiga de gamificación si no se renueva', 'Explotación de misiones por usuarios avanzados'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    enginesUsed: ['gamification', 'reward', 'membership', 'rule', 'action', 'automation', 'analytics'],
    automationPlaybooks: ['mision_semanal_automatica', 'recordatorio_puntos_por_vencer'],
    compatibleBenefits: ['puntos_dobles', 'canje_por_detailing'],
    compatiblePromotions: ['xp_x2_fin_semana', 'mision_referido'],
    compatibleCampaigns: ['captacion_gamificada', 'reactivacion_por_mision'],
    compatibleGamification: ['niveles_xp', 'misiones_semanales', 'tabla_posiciones'],
    kpis: ['uso_promedio', 'visitas_promedio', 'retencion', 'ltv', 'churn'],
    bestPractices: ['Calibrar economía de puntos para proteger margen', 'Renovar misiones periódicamente', 'Ligar recompensas a servicios de mayor margen', 'Fijar caducidad de puntos'],
    commonMistakes: ['Emitir puntos sin control de pasivo', 'No renovar misiones y generar fatiga', 'Recompensas sin relación con rentabilidad'],
    variantKeys: ['carwash.rewards'],
    version: '1.0.0',
    technicalNotes: 'Gamification Engine gestiona XP/niveles/misiones y Reward Engine liquida canjes; Analytics Engine controla la economía de puntos como pasivo.',
  },
  {
    id: 'carwash.membership.trial',
    industry: 'carwash',
    model: 'TRIAL',
    name: 'Trial Membership',
    description: 'Prueba corta a precio simbólico que permite experimentar la membresía y convertir clientes nuevos a planes recurrentes.',
    objective: ['captacion', 'retencion', 'frecuencia'],
    audience: ['nuevos', 'individual', 'familias'],
    problemSolved: 'Fricción de adquisición: reduce la barrera de entrada para que clientes nuevos prueben la suscripción antes de comprometerse.',
    whenToUse: 'Cuando se busca convertir clientes nuevos o de pago por visita hacia un plan recurrente completo.',
    whenNotToUse: 'Cuando la base ya es mayoritariamente suscriptora o cuando el costo del periodo de prueba no se recupera con la conversión.',
    advantages: ['Baja barrera de entrada', 'Genera hábito antes de la conversión', 'Mide intención real de compra', 'Alimenta el embudo de suscripción'],
    disadvantages: ['Margen negativo durante la prueba', 'Riesgo de cazadores de ofertas', 'Conversión incierta si mal diseñado'],
    risks: ['Baja conversión post-prueba', 'Abuso repetido de pruebas', 'Sobreuso durante el periodo simbólico'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    enginesUsed: ['membership', 'promotion', 'rule', 'action', 'automation', 'campaign'],
    automationPlaybooks: ['secuencia_conversion_trial', 'recordatorio_fin_de_prueba'],
    compatibleBenefits: ['primer_mes_simbolico', 'linea_rapida'],
    compatiblePromotions: ['prueba_7_dias', 'convierte_y_ahorra'],
    compatibleCampaigns: ['captacion_trial', 'conversion_post_prueba'],
    compatibleGamification: ['racha_visitas', 'nivel_por_frecuencia'],
    kpis: ['tasa_renovacion', 'retencion', 'churn', 'ltv', 'uso_promedio'],
    bestPractices: ['Definir duración corta con valor claro', 'Automatizar la secuencia de conversión antes del vencimiento', 'Limitar una prueba por cliente/vehículo', 'Pedir método de pago para conversión automática'],
    commonMistakes: ['Prueba demasiado larga o gratuita total', 'No tener flujo de conversión definido', 'Permitir pruebas repetidas por el mismo cliente'],
    variantKeys: ['carwash.trial'],
    version: '1.0.0',
    technicalNotes: 'Membership Engine crea plan temporal (periodicity ONE_TIME, durationDays) con conversión automática vía Promotion/Campaign Engine al vencer; enforcement de una prueba por identidad de vehículo.',
  },
  {
    id: 'carwash.membership.student',
    industry: 'carwash',
    model: 'STUDENT',
    name: 'Student Membership',
    description: 'Membresía con tarifa reducida para estudiantes verificados; capta un segmento sensible al precio con alto potencial de hábito a largo plazo.',
    objective: ['captacion', 'fidelizacion', 'frecuencia'],
    audience: ['individual', 'nuevos', 'frecuentes'],
    problemSolved: 'Baja penetración en el segmento joven con presupuesto limitado: ofrece un precio de entrada accesible sin canibalizar tarifas plenas.',
    whenToUse: 'Cuando existe un campus o comunidad estudiantil cercana y se busca construir base de clientes jóvenes fieles.',
    whenNotToUse: 'Cuando no hay forma fiable de verificar la condición de estudiante o el descuento erosiona el margen sin generar volumen.',
    advantages: ['Capta segmento joven de bajo costo de adquisición', 'Construye hábito temprano y LTV futuro', 'Diferenciador de marca en zonas universitarias'],
    disadvantages: ['Ticket promedio bajo', 'Estacionalidad por calendario académico', 'Requiere proceso de verificación'],
    risks: ['Fraude por credenciales caducadas o falsas', 'Migración masiva de tarifa plena a tarifa estudiante', 'Abandono al finalizar los estudios'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado'],
    compatibleVehicles: ['sedan', 'motocicleta', 'suv'],
    enginesUsed: ['membership', 'rule', 'benefit', 'automation', 'campaign'],
    automationPlaybooks: ['verificacion_estudiante_anual', 'reactivacion_inicio_semestre'],
    compatibleBenefits: ['descuento_estudiante_20', 'aspirado_gratis_semanal'],
    compatiblePromotions: ['inscripcion_inicio_curso', 'referido_campus'],
    compatibleCampaigns: ['captacion_universitaria', 'winback_vacaciones'],
    compatibleGamification: ['racha_visitas', 'nivel_por_frecuencia'],
    kpis: ['uso_promedio', 'retencion', 'churn', 'ltv', 'rentabilidad_por_miembro'],
    bestPractices: ['Verificar condición de estudiante cada ciclo académico', 'Limitar el descuento a servicios base, no a premium', 'Diseñar ruta de conversión a plan pleno al graduarse'],
    commonMistakes: ['No revalidar la credencial y mantener el descuento indefinidamente', 'Aplicar el descuento a detailing de alto costo', 'Ignorar la estacionalidad y sobredimensionar capacidad'],
    variantKeys: ['carwash.student'],
    version: '1.0.0',
    technicalNotes: 'Verificación vía config.restrictions con expiración anual (Rule Engine); descuento aplicado por Benefit Engine condicionado a segmento verificado.',
  },
  {
    id: 'carwash.membership.driver',
    industry: 'carwash',
    model: 'DRIVER',
    name: 'Driver Membership',
    description: 'Membresía para conductores profesionales (taxi, rideshare, delivery) con muy alta frecuencia de lavado y necesidad de rapidez operativa.',
    objective: ['retencion', 'frecuencia', 'fidelizacion'],
    audience: ['individual', 'frecuentes', 'empresas'],
    problemSolved: 'Los conductores profesionales necesitan lavar a diario con mínimo tiempo de espera: convierte esa demanda intensiva en ingreso recurrente y previsible.',
    whenToUse: 'Cuando hay demanda de conductores profesionales y la capacidad instalada soporta uso diario en línea rápida.',
    whenNotToUse: 'Cuando el costo marginal por lavado es alto o la capacidad en horas pico no absorbe el uso intensivo sin degradar el servicio.',
    advantages: ['Ingreso recurrente de altísima frecuencia', 'Fideliza por dependencia operativa', 'Ocupa capacidad en horas valle'],
    disadvantages: ['Alto riesgo de erosión de margen por sobreuso', 'Desgaste de equipos por volumen', 'Presión sobre tiempos de espera'],
    risks: ['Miembros de uso extremo vuelven no rentable la cuota', 'Congestión en horas pico', 'Rotación alta ligada a la actividad del conductor'],
    complexity: 'media',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado'],
    compatibleVehicles: ['sedan', 'suv', 'van'],
    enginesUsed: ['membership', 'rule', 'action', 'automation', 'analytics'],
    automationPlaybooks: ['alerta_sobreuso_conductor', 'recordatorio_renovacion'],
    compatibleBenefits: ['linea_rapida', 'aspirado_ilimitado'],
    compatiblePromotions: ['primer_mes_descuento', 'referido_gremio'],
    compatibleCampaigns: ['captacion_flotas_rideshare', 'winback_vencidos'],
    compatibleGamification: ['racha_visitas', 'nivel_por_frecuencia'],
    kpis: ['uso_promedio', 'rentabilidad_por_miembro', 'visitas_promedio', 'churn', 'ltv'],
    bestPractices: ['Definir cuota sobre el costo marginal real del uso intensivo', 'Ofrecer línea rápida dedicada para conductores', 'Monitorear uso por miembro con analytics para detectar sobreuso'],
    commonMistakes: ['Fijar la cuota como un usuario ocasional', 'No dimensionar capacidad para el uso diario', 'Incluir servicios premium de alto costo en la cuota base'],
    variantKeys: ['carwash.driver'],
    version: '1.0.0',
    technicalNotes: 'Enforcement vía UsageTracker con maxPerPeriod alto y minIntervalMinutes; Analytics Engine emite alerta cuando el costo por miembro supera umbral de rentabilidad.',
  },
  {
    id: 'carwash.membership.subscription_box',
    industry: 'carwash',
    model: 'SUBSCRIPTION_BOX',
    name: 'Wash Subscription Box',
    description: 'Caja mensual que combina lavados con productos físicos de cuidado del vehículo; eleva el ticket promedio y refuerza la percepción de valor.',
    objective: ['ticket_promedio', 'upselling', 'fidelizacion'],
    audience: ['individual', 'vip', 'frecuentes'],
    problemSolved: 'La cuota de lavado sola tiene valor percibido plano: añadir productos tangibles cada mes justifica un precio superior y sorprende al miembro.',
    whenToUse: 'Cuando se busca subir el ticket promedio y diferenciarse con una experiencia curada de productos de detailing.',
    whenNotToUse: 'Cuando no existe logística de inventario y cumplimiento, o el margen de los productos no sostiene el costo de la caja.',
    advantages: ['Incrementa el ticket promedio', 'Genera efecto sorpresa y engagement mensual', 'Diferenciación fuerte frente a lavado plano'],
    disadvantages: ['Complejidad logística e inventario', 'Margen sensible al costo de los productos', 'Riesgo de sobrantes o roturas de stock'],
    risks: ['Fatiga si el contenido se vuelve repetitivo', 'Costos de cumplimiento superan el valor de la cuota', 'Cancelaciones si la caja no cumple expectativas'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_premium', 'detailing', 'lavado_interior'],
    compatibleVehicles: ['sedan', 'suv', 'lujo', 'pickup'],
    enginesUsed: ['membership', 'benefit', 'reward', 'automation', 'campaign'],
    automationPlaybooks: ['despacho_caja_mensual', 'aviso_contenido_nuevo'],
    compatibleBenefits: ['producto_cuidado_mensual', 'descuento_detailing_10'],
    compatiblePromotions: ['caja_bienvenida_edicion', 'referido_gana'],
    compatibleCampaigns: ['captacion_suscripcion', 'lanzamiento_edicion_limitada'],
    compatibleGamification: ['coleccion_productos', 'nivel_por_antiguedad'],
    kpis: ['rentabilidad_por_miembro', 'retencion', 'churn', 'ltv', 'tasa_renovacion'],
    bestPractices: ['Rotar el contenido de la caja para evitar fatiga', 'Calcular la cuota sobre costo de producto más cumplimiento', 'Comunicar el valor de la caja con anticipación cada mes'],
    commonMistakes: ['Repetir el mismo producto y perder el efecto sorpresa', 'Subestimar costos logísticos y de inventario', 'Prometer contenido premium sin margen que lo sostenga'],
    variantKeys: ['carwash.subscription_box'],
    version: '1.0.0',
    technicalNotes: 'Reward Engine gestiona el catálogo mensual de productos; Automation dispara el playbook de despacho ligado al ciclo de facturación del Membership Engine.',
  },
  {
    id: 'carwash.membership.custom',
    industry: 'carwash',
    model: 'CUSTOM',
    name: 'Custom Membership Builder',
    description: 'Plan configurable donde el cliente o la empresa arma su propia membresía; el precio se calcula dinámicamente según los servicios y frecuencia elegidos.',
    objective: ['captacion', 'upselling', 'retencion'],
    audience: ['empresas', 'flotas', 'vip', 'individual'],
    problemSolved: 'Los planes rígidos no encajan con necesidades heterogéneas: permite armar una membresía a medida y capturar disposición a pagar por configuración.',
    whenToUse: 'Cuando la base tiene necesidades muy diversas (empresas, flotas, VIP) y se dispone de un motor de precios por configuración.',
    whenNotToUse: 'Cuando la demanda es homogénea y planes fijos bastan, o falta capacidad para gobernar la complejidad de configuraciones.',
    advantages: ['Máxima flexibilidad y ajuste a cada cliente', 'Captura disposición a pagar por upselling modular', 'Atractivo para empresas y flotas con requisitos propios'],
    disadvantages: ['Alta complejidad de configuración y precio', 'Difícil de comunicar y comparar', 'Riesgo de configuraciones no rentables'],
    risks: ['El motor de precios permite combinaciones que erosionan margen', 'Parálisis por exceso de opciones', 'Soporte y mantenimiento costosos'],
    complexity: 'alta',
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero', 'lujo'],
    enginesUsed: ['membership', 'rule', 'decision', 'template', 'analytics'],
    automationPlaybooks: ['cotizacion_configurador', 'revision_rentabilidad_config'],
    compatibleBenefits: ['descuento_por_volumen', 'linea_rapida'],
    compatiblePromotions: ['descuento_flota', 'referido_empresarial'],
    compatibleCampaigns: ['captacion_empresas', 'captacion_flotas'],
    compatibleGamification: ['nivel_por_frecuencia', 'metas_flota'],
    kpis: ['rentabilidad_por_miembro', 'uso_promedio', 'retencion', 'ltv', 'tasa_renovacion'],
    bestPractices: ['Definir límites y pisos de precio en el configurador', 'Ofrecer plantillas base como punto de partida', 'Validar rentabilidad de cada configuración con analytics antes de activarla'],
    commonMistakes: ['Dar libertad total sin topes que protejan el margen', 'Sobrecargar de opciones y paralizar la decisión', 'No versionar ni auditar las configuraciones generadas'],
    variantKeys: ['carwash.custom_builder'],
    version: '1.0.0',
    technicalNotes: 'Decision Engine calcula el precio por configuración con reglas de piso/tope; cada configuración válida se materializa como MembershipTemplate versionado.',
  },
]

// ── Índices y descubrimiento ────────────────────────────────────────────────

const BY_ID = new Map(CARWASH_MEMBERSHIP_STRATEGIES.map((s) => [s.id, s]))
const BY_MODEL = new Map(CARWASH_MEMBERSHIP_STRATEGIES.map((s) => [s.model, s]))

export function getMembershipStrategy(id: string): MembershipStrategy | undefined {
  return BY_ID.get(id)
}

/** Estrategia que documenta un modelo comercial. */
export function membershipStrategyForModel(
  model: MembershipPlanType,
): MembershipStrategy | undefined {
  return BY_MODEL.get(model)
}

/** Resuelve las variantes instalables (MembershipTemplate) de una estrategia. */
export function strategyVariants(strategy: MembershipStrategy): readonly MembershipTemplate[] {
  return strategy.variantKeys
    .map((k) => getCarwashTemplate(k))
    .filter((t): t is MembershipTemplate => t !== undefined)
}

/** Estrategias que persiguen un objetivo comercial. */
export function membershipStrategiesByObjective(
  objective: MembershipObjective,
): readonly MembershipStrategy[] {
  return CARWASH_MEMBERSHIP_STRATEGIES.filter((s) => s.objective.includes(objective))
}

/** Estrategias dirigidas a un público objetivo. */
export function membershipStrategiesByAudience(
  audience: MembershipAudience,
): readonly MembershipStrategy[] {
  return CARWASH_MEMBERSHIP_STRATEGIES.filter((s) => s.audience.includes(audience))
}
