/**
 * Biblioteca de Automation Playbooks de CAMPAÑAS (Fase E1.8). No es un sistema de
 * notificaciones: es un CAMPAIGN ORCHESTRATION FRAMEWORK. Cada campaña coordina
 * VARIOS motores de MembeGo (Promotion, Membership, Benefit, Reward, Referral,
 * Gamification, Automation, Analytics) para ejecutar una estrategia comercial
 * completa: evento → Rule Engine → segmentación → selección de estrategia →
 * promociones/beneficios/recompensas/puntos/misiones/cupones/automatizaciones/
 * campañas hijas → notificaciones → medición → optimización.
 *
 * La orquestación se hace siempre por eventos, reglas y acciones reutilizables
 * (Action Engine `INVOKE_MODULE`/`RUN_WORKFLOW`/`CREATE_EVENT`), nunca con lógica
 * aislada. Estrategias probadas de orquestación (Braze Canvas/Salesforce Journey/
 * Klaviyo Flows) convertidas en playbooks UNIVERSALES instalables sobre el
 * Automation Engine (E1). Car Wash es solo la primera industria que las usa.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa (25 apartados, incl. "Membresías compatibles" y "Gamificación
 * compatible"). Nada hardcodeado por industria: todo por variable/código.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I, MEMBERSHIP_MODELS as M } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL
const ANY = M.ANY

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'triggers', 'reglas', 'segmentos', 'fechas', 'horarios',
  'duracion', 'prioridad', 'presupuesto', 'variables', 'beneficios', 'promociones',
  'membresias', 'canales', 'idioma', 'sucursales', 'limites',
] as const

// KPIs típicos de campañas orquestadas.
const CAMP_KPIS = [
  'participacion', 'conversion', 'beneficios_utilizados', 'ingresos', 'roi',
  'coste', 'alcance', 'ticket_promedio', 'segmentos_impactados', 'motores_activados',
  'tasa_apertura', 'tasa_clic',
] as const

// Mecánicas de gamificación reutilizables (referencia, no hardcode).
const GAMI = ['puntos', 'xp', 'niveles', 'misiones', 'rachas', 'insignias', 'ranking'] as const

/** Helper: completa los apartados comunes de un playbook de campaña. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines' | 'compatibleGamification'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable' | 'compatibleGamification'>>,
): AutomationPlaybook {
  return {
    category: 'campanas',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? CAMP_KPIS,
    engines: p.engines ?? ['rule', 'action', 'campaign', 'analytics'],
    compatibleGamification: p.compatibleGamification ?? [...GAMI],
    ...p,
  }
}

export const CAMPAIGN_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'CAMP-001',
    name: 'Campaña de bienvenida orquestada',
    objective: 'Activar a nuevos clientes coordinando beneficio + puntos + automatización.',
    problem: 'Una sola notificación de bienvenida no maximiza la activación.',
    whenToUse: 'Al ingresar clientes nuevos a la campaña de bienvenida.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Cliente nuevo en el segmento de bienvenida'],
    variables: ['cliente.nombre', 'empresa.nombre'],
    engines: ['rule', 'action', 'campaign', 'benefit', 'reward', 'analytics'],
    flow: ['Ingresa el cliente', 'Se segmenta como nuevo', 'Se entrega beneficio + puntos', 'Se lanza la automatización de onboarding', 'Se mide'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.RUN_WORKFLOW],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_CONVERTED],
    exceptions: ['Cliente no nuevo', 'Presupuesto agotado'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'niveles'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['WELCOME'],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Campaign Engine', 'Benefit/Reward Engine'],
    compatibleTemplates: ['universal.bienvenida'],
    examples: ['Nuevo cliente → beneficio + 50 pts + inicia serie de onboarding'],
    notes: 'Orquesta 3 motores en un solo paso; la automatización de onboarding es una campaña hija.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre', 'empresa.nombre'],
      channels: ['push', 'email'],
      priority: 8,
      steps: [
        {
          label: 'Orquestar bienvenida',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' } },
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 50 } },
            { type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.ONB-001' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-002',
    name: 'Campaña estacional (multi-motor)',
    objective: 'Ejecutar una campaña de temporada coordinando promoción + gamificación.',
    problem: 'Las campañas estacionales de un solo canal rinden por debajo de su potencial.',
    whenToUse: 'En temporadas relevantes para el negocio.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado por temporada'],
    conditions: ['Temporada activa', 'Segmento objetivo definido'],
    variables: ['cliente.nombre', 'temporada.nombre'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'gamification', 'analytics'],
    flow: ['Llega la temporada', 'Se crea la promoción de temporada', 'Se lanza una misión de gamificación', 'Se comunica', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración de la temporada (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_FINISHED],
    exceptions: ['Fuera de temporada', 'Sin segmento'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['misiones', 'puntos', 'ranking'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['SEASONAL'],
    compatibleCampaigns: ['estacional'],
    dependencies: ['Campaign/Promotion/Gamification Engine'],
    compatibleTemplates: [],
    examples: ['Temporada de lluvias: promo + misión “3 lavados este mes”'],
    notes: 'Combina Promotion y Gamification en una misma campaña estacional.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 1 * *', params: { season: 'editable' } },
      variables: ['cliente.nombre', 'temporada.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Orquestar temporada',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_seasonal' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'start_mission' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Campaña de {{temporada.nombre}}', body: '{{cliente.nombre}}, participa y gana esta temporada.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-003',
    name: 'Campaña de cumpleaños',
    objective: 'Celebrar el cumpleaños con beneficio + puntos y medir conversión.',
    problem: 'El cumpleaños es una gran ocasión de venta que suele desaprovecharse.',
    whenToUse: 'En la fecha de cumpleaños del cliente.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Fecha: cumpleaños'],
    conditions: ['Fecha de nacimiento registrada'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'benefit', 'reward', 'analytics'],
    flow: ['Llega el cumpleaños', 'Se entrega un beneficio + puntos', 'Se felicita', 'Se mide la conversión'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Sin fecha de nacimiento'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-004', 'CAR-001'],
    compatiblePromotions: ['BIRTHDAY'],
    compatibleCampaigns: ['estacional'],
    dependencies: ['Fecha del cliente', 'Benefit/Reward Engine'],
    compatibleTemplates: ['universal.cumpleanos'],
    examples: ['“¡Feliz cumpleaños! Un lavado gratis + puntos dobles”'],
    notes: 'Reutiliza la plantilla universal de cumpleaños coordinando beneficio y puntos.',
    config: {
      trigger: { type: 'DATE', params: { field: 'fechaNacimiento' } },
      variables: ['cliente.nombre'],
      channels: ['push', 'email', 'whatsapp'],
      steps: [
        {
          label: 'Celebrar',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' } },
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 100 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Feliz cumpleaños, {{cliente.nombre}}!', body: 'Un regalo para celebrar tu día.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-004',
    name: 'Campaña por aniversario del cliente',
    objective: 'Reconocer el aniversario de relación y reforzar la lealtad.',
    problem: 'La antigüedad del cliente no se celebra ni se aprovecha comercialmente.',
    whenToUse: 'En el aniversario del registro o primera compra del cliente.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Fecha: aniversario del cliente'],
    conditions: ['Aniversario alcanzado'],
    variables: ['cliente.nombre', 'cliente.aniosActivo'],
    engines: ['rule', 'action', 'campaign', 'benefit', 'reward', 'analytics'],
    flow: ['Llega el aniversario', 'Se entrega beneficio de fidelidad', 'Se agradece', 'Se mide'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Sin fecha de aniversario'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'niveles'],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['ANNIVERSARY'],
    compatibleCampaigns: ['fidelizacion'],
    dependencies: ['Fecha de aniversario', 'Benefit Engine'],
    compatibleTemplates: [],
    examples: ['“1 año con nosotros: gracias, aquí tienes un regalo”'],
    notes: 'El hito de aniversario es editable; escalable por años de permanencia.',
    config: {
      trigger: { type: 'DATE', params: { field: 'aniversarioCliente' } },
      variables: ['cliente.nombre', 'cliente.aniosActivo'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Celebrar aniversario',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡{{cliente.aniosActivo}} año(s) juntos, {{cliente.nombre}}!', body: 'Gracias por tu confianza. Un regalo para ti.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-005',
    name: 'Campaña por clima',
    objective: 'Disparar campañas según condiciones climáticas relevantes.',
    problem: 'No aprovechar el clima pierde demanda natural (ej. lluvia/calor).',
    whenToUse: 'Cuando el clima cumple una condición configurada.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (chequeo de clima)'],
    conditions: ['Condición climática objetivo (via INVOKE_MODULE)'],
    variables: ['cliente.nombre', 'clima.condicion', 'cliente.sucursal'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'analytics'],
    flow: ['Se consulta el clima', 'Si cumple la condición, se lanza promo relevante', 'Se comunica al segmento local', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Chequeo periódico (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.AUTOMATION_FINISHED],
    exceptions: ['Datos de clima no disponibles', 'Condición no cumplida'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['WEATHER'],
    compatibleCampaigns: ['estacional', 'local'],
    dependencies: ['Fuente de clima (integrable vía INVOKE_MODULE)'],
    compatibleTemplates: [],
    examples: ['Car Wash: después de lluvia → promo de lavado', 'Restaurante: ola de calor → bebidas'],
    notes: 'La fuente de clima se integra por INVOKE_MODULE sin cambiar el motor.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 8 * * *' },
      variables: ['cliente.nombre', 'clima.condicion'],
      channels: ['push'],
      steps: [
        {
          label: 'Campaña por clima',
          condition: 'clima.condicion == "post_lluvia"',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_weather_promo' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'El clima es perfecto, {{cliente.nombre}}', body: 'Aprovecha nuestra promo de hoy.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-006',
    name: 'Campaña por ubicación (geosegmentada)',
    objective: 'Lanzar campañas dirigidas a clientes de una sucursal/zona.',
    problem: 'Las campañas globales pierden relevancia local.',
    whenToUse: 'Para promociones o eventos de una sucursal específica.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: clientes de una sucursal/zona'],
    conditions: ['Cliente asociado a la sucursal objetivo'],
    variables: ['cliente.nombre', 'cliente.sucursal'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'analytics'],
    flow: ['Se selecciona el segmento por sucursal', 'Se lanza la promo local', 'Se comunica', 'Se mide por sucursal'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED],
    exceptions: ['Sin sucursal asignada'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['LOCAL'],
    compatibleCampaigns: ['local'],
    dependencies: ['Segmentación por sucursal'],
    compatibleTemplates: [],
    examples: ['“Solo en la sucursal Centro: 2x1 este viernes”'],
    notes: 'La sucursal es una variable de segmento; útil para aperturas y eventos locales.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'sucursal_objetivo' } },
      variables: ['cliente.nombre', 'cliente.sucursal'],
      channels: ['push', 'whatsapp'],
      steps: [
        {
          label: 'Campaña local',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_local_promo' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Novedad en tu sucursal, {{cliente.nombre}}', body: 'Promo especial en {{cliente.sucursal}}.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-007',
    name: 'Campaña por comportamiento',
    objective: 'Orquestar una campaña según el comportamiento reciente del cliente.',
    problem: 'Las campañas no personalizadas por conducta convierten poco.',
    whenToUse: 'Cuando el comportamiento del cliente cambia o cruza un umbral.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: cambio de comportamiento'],
    conditions: ['Segmento conductual objetivo (Rule Engine)'],
    variables: ['cliente.nombre', 'cliente.segmento'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'benefit', 'analytics'],
    flow: ['Se detecta el comportamiento', 'Se selecciona la estrategia', 'Se ejecuta la oferta adecuada', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_CONVERTED],
    exceptions: ['Sin datos de comportamiento'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'misiones'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['PERSONALIZED'],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Analytics con segmentos conductuales'],
    compatibleTemplates: [],
    examples: ['Sube el gasto → campaña premium; baja la frecuencia → campaña de retención'],
    notes: 'La selección de estrategia se apoya en Analytics; la campaña orquesta la respuesta.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_BEHAVIOR_CHANGED },
      variables: ['cliente.nombre', 'cliente.segmento'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Orquestar por comportamiento',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'analytics', action: 'select_campaign_strategy' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: '{{campana.beneficio}}' } },
          ],
          chain: { event: EV.CAMPAIGN_CONVERTED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-008',
    name: 'Campaña por inactividad (recuperación orquestada)',
    objective: 'Recuperar inactivos coordinando beneficio + promo + automatización.',
    problem: 'La recuperación de un solo golpe es menos efectiva que una campaña.',
    whenToUse: 'Cuando el cliente entra al segmento de inactivos.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: inactivo'],
    conditions: ['Sin actividad > período configurado'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'benefit', 'promotion', 'automation', 'analytics'],
    flow: ['Se detecta inactividad', 'Se lanza la campaña de recuperación', 'Se coordina beneficio + promo + recordatorios', 'Se mide'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.RUN_WORKFLOW, ACTION_TYPES.SEND_WHATSAPP],
    esperas: ['Secuencia de la campaña (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CLIENT_RECOVERED],
    exceptions: ['Cliente activo', 'Opt-out'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['WINBACK'],
    compatibleCampaigns: ['recuperacion'],
    dependencies: ['Campaign Engine', 'Automation Engine (recuperación E1.5)'],
    compatibleTemplates: [],
    examples: ['Inactivo → beneficio + promo + serie de recuperación (REC-*)'],
    notes: 'Orquesta la biblioteca de recuperación (E1.5) como parte de la campaña.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'inactivo' } },
      variables: ['cliente.nombre'],
      channels: ['whatsapp', 'email', 'push'],
      limits: { maxPerSubject: 1, perPeriod: 'MONTH' },
      steps: [
        {
          label: 'Orquestar recuperación',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } },
            { type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.REC-002' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-009',
    name: 'Campaña para promover membresías',
    objective: 'Impulsar la adquisición de membresías con oferta + prueba.',
    problem: 'Las membresías no se venden solas; requieren una campaña dedicada.',
    whenToUse: 'Para clientes activos sin membresía.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: activo sin membresía'],
    conditions: ['Cliente sin membresía activa', 'Actividad suficiente'],
    variables: ['cliente.nombre', 'membresia.planSugerido'],
    engines: ['rule', 'action', 'campaign', 'membership', 'promotion', 'analytics'],
    flow: ['Se selecciona el segmento', 'Se recomienda una membresía con prueba/oferta', 'Se comunica', 'Se mide la conversión'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_EMAIL],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.MEMBERSHIP_CREATED],
    exceptions: ['Ya tiene membresía', 'Sin planes publicados'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['MEMBERSHIP', 'MEMBERSHIP_TRIAL'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con planes'],
    compatibleTemplates: [],
    examples: ['“Prueba el plan ilimitado 7 días” a clientes activos'],
    notes: 'Orquesta Membership + Promotion; la recomendación la calcula el Membership Engine.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'activo_sin_membresia' } },
      variables: ['cliente.nombre', 'membresia.planSugerido'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Promover membresía',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'membership', action: 'recommend' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Una membresía para ti, {{cliente.nombre}}', body: 'Prueba {{membresia.planSugerido}} con una oferta especial.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-010',
    name: 'Campaña de upgrades',
    objective: 'Impulsar upgrades de plan en el segmento adecuado.',
    problem: 'Los upgrades no ocurren sin una campaña que muestre el valor.',
    whenToUse: 'Para miembros candidatos a un plan superior.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: candidato a upgrade'],
    conditions: ['Uso/gasto sugiere beneficio de un plan superior'],
    variables: ['cliente.nombre', 'membresia.planSugerido'],
    engines: ['rule', 'action', 'campaign', 'membership', 'promotion', 'analytics'],
    flow: ['Se identifica al candidato', 'Se lanza la oferta de upgrade', 'Se comunica el valor extra', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.MEMBERSHIP_UPGRADED],
    exceptions: ['Ya en el plan máximo'],
    compatibleMembershipModels: [M.TIER, M.HYBRID, M.PREMIUM, M.VIP, M.CREDITS, M.CUSTOM],
    compatibleGamification: ['niveles'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['UPGRADE'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con planes superiores'],
    compatibleTemplates: [],
    examples: ['“Con el plan Plus tendrías estos beneficios extra”'],
    notes: 'Reutiliza MEM-010 en clave de campaña coordinada.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'candidato_upgrade' } },
      variables: ['cliente.nombre', 'membresia.planSugerido'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Campaña de upgrade',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'membership', action: 'recommend_upgrade' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Mejora tu plan, {{cliente.nombre}}', body: '{{membresia.planSugerido}} se ajusta mejor a ti.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-011',
    name: 'Campaña de referidos',
    objective: 'Activar el programa de referidos como campaña coordinada.',
    problem: 'El referido rinde más cuando se impulsa con una campaña, no en silencio.',
    whenToUse: 'Para impulsar recomendaciones en un segmento activo/satisfecho.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: clientes satisfechos/activos'],
    conditions: ['Programa de referidos activo'],
    variables: ['cliente.nombre', 'referido.codigo'],
    engines: ['rule', 'action', 'campaign', 'referral', 'benefit', 'analytics'],
    flow: ['Se selecciona el segmento', 'Se lanza la invitación a referir con incentivo', 'Se coordina con el Referral Engine', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_WHATSAPP],
    esperas: [],
    events: [EV.CAMPAIGN_LAUNCHED, EV.REFERRAL_SHARED],
    exceptions: ['Programa de referidos inactivo'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'ranking'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['REFERRAL'],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Referral Engine (journey E1.7)'],
    compatibleTemplates: [],
    examples: ['“Invita a un amigo esta semana y ambos ganan” al segmento satisfecho'],
    notes: 'Orquesta la biblioteca de referidos (E1.7) como campaña.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'clientes_satisfechos' } },
      variables: ['cliente.nombre', 'referido.codigo'],
      channels: ['whatsapp', 'push'],
      steps: [
        {
          label: 'Impulsar referidos',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'boost_campaign' } },
            { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, invita a un amigo con {{referido.codigo}} y ambos ganan.' } },
          ],
          chain: { event: EV.REFERRAL_SHARED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-012',
    name: 'Campaña de puntos (multiplicadores)',
    objective: 'Estimular el consumo con multiplicadores de puntos por tiempo limitado.',
    problem: 'La acumulación de puntos se estanca sin campañas de impulso.',
    whenToUse: 'En ventanas de multiplicador (ej. fin de semana de puntos dobles).',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (ventana de multiplicador)'],
    conditions: ['Programa de puntos activo', 'Ventana vigente'],
    variables: ['cliente.nombre', 'puntos.multiplicador'],
    engines: ['rule', 'action', 'campaign', 'reward', 'gamification', 'analytics'],
    flow: ['Comienza la ventana', 'Se comunica el multiplicador', 'Las compras acumulan más puntos', 'Al cerrar, se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración del multiplicador (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Programa de puntos desactivado'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'xp'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['POINTS_BOOST'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Reward/Gamification Engine con multiplicadores'],
    compatibleTemplates: [],
    examples: ['“Este fin de semana, puntos dobles en todo”'],
    notes: 'XP ≠ puntos; el multiplicador y la vigencia son editables.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 * * 6' },
      variables: ['cliente.nombre', 'puntos.multiplicador'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Activar multiplicador',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'reward', action: 'set_points_multiplier' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Puntos x{{puntos.multiplicador}}!', body: '{{cliente.nombre}}, aprovecha este fin de semana.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-013',
    name: 'Campaña por objetivos (misiones)',
    objective: 'Movilizar al cliente hacia objetivos con misiones y recompensas.',
    problem: 'Sin objetivos claros, el cliente no tiene motivo para volver más.',
    whenToUse: 'Para impulsar comportamientos concretos con gamificación.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado / segmento objetivo'],
    conditions: ['Gamificación activa', 'Objetivo definido'],
    variables: ['cliente.nombre', 'objetivo.meta'],
    engines: ['rule', 'action', 'campaign', 'gamification', 'reward', 'analytics'],
    flow: ['Se lanza la misión con su meta', 'Se comunica el progreso', 'Al cumplir, se recompensa', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración de la misión (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CLIENT_MISSION_COMPLETED],
    exceptions: ['Gamificación desactivada'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['misiones', 'xp', 'insignias', 'rachas'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['MISSION'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification Engine con misiones'],
    compatibleTemplates: [],
    examples: ['“Completa 3 visitas este mes y gana una insignia + beneficio”'],
    notes: 'Orquesta el Gamification Engine; la meta y recompensa son editables.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'objetivo_frecuencia' } },
      variables: ['cliente.nombre', 'objetivo.meta'],
      channels: ['push'],
      steps: [
        {
          label: 'Lanzar misión',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'start_mission' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Nuevo reto, {{cliente.nombre}}', body: 'Cumple {{objetivo.meta}} y gana una recompensa.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-014',
    name: 'Campaña de lanzamiento (nuevo servicio/producto)',
    objective: 'Coordinar el lanzamiento de un servicio con anuncio + oferta introductoria.',
    problem: 'Los lanzamientos sin campaña pasan desapercibidos.',
    whenToUse: 'Al lanzar un nuevo servicio, producto o sucursal.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (fecha de lanzamiento)'],
    conditions: ['Fecha de lanzamiento alcanzada'],
    variables: ['cliente.nombre', 'lanzamiento.nombre'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'benefit', 'analytics'],
    flow: ['Llega el lanzamiento', 'Se anuncia con oferta introductoria', 'Se coordina promo + beneficio', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Ventana introductoria (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_CONVERTED],
    exceptions: ['Antes de la fecha'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['LAUNCH'],
    compatibleCampaigns: ['lanzamiento'],
    dependencies: ['Promotion/Benefit Engine'],
    compatibleTemplates: [],
    examples: ['“Estrenamos servicio premium: pruébalo con 30% esta semana”'],
    notes: 'Orquesta anuncio + oferta introductoria; ideal para nuevos servicios/sucursales.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 15 * *', params: { launch: 'editable' } },
      variables: ['cliente.nombre', 'lanzamiento.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Anunciar lanzamiento',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_launch_promo' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Estrenamos {{lanzamiento.nombre}}', body: '{{cliente.nombre}}, pruébalo con una oferta introductoria.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-015',
    name: 'Campaña Flash / oferta relámpago',
    objective: 'Generar urgencia con una oferta de muy corta duración.',
    problem: 'Sin urgencia, muchas decisiones de compra se posponen.',
    whenToUse: 'En ventanas cortas de alta intención (horas).',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (ventana flash)'],
    conditions: ['Ventana flash vigente'],
    variables: ['cliente.nombre', 'flash.horasRestantes'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'analytics'],
    flow: ['Comienza la ventana flash', 'Se comunica con urgencia', 'La oferta caduca en horas', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración corta (ej. 3-6h) editable'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_FINISHED],
    exceptions: ['Fuera de la ventana'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['FLASH'],
    compatibleCampaigns: ['flash'],
    dependencies: ['Promotion Engine con vigencia corta'],
    compatibleTemplates: [],
    examples: ['“Solo por 3 horas: 40% en tu próximo servicio”'],
    notes: 'La urgencia (horas restantes) se comunica con variable; caduca sola.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 12 * * *' },
      variables: ['cliente.nombre', 'flash.horasRestantes'],
      channels: ['push'],
      steps: [
        {
          label: 'Lanzar flash',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_flash_promo' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Solo por {{flash.horasRestantes}}h, {{cliente.nombre}}!', body: 'Aprovecha antes de que termine.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-016',
    name: 'Campaña Happy Hour (por franja horaria)',
    objective: 'Llenar horas valle con una oferta activa solo en cierta franja.',
    problem: 'Las horas de baja demanda quedan ociosas.',
    whenToUse: 'En franjas horarias específicas y recurrentes.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (franja horaria)'],
    conditions: ['Dentro de la franja happy hour'],
    variables: ['cliente.nombre', 'happyhour.franja'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'analytics'],
    flow: ['Comienza la franja', 'Se comunica la oferta', 'Válida solo en ese horario', 'Se mide el llenado'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Solo dentro de la franja (schedule.hours editable)'],
    events: [EV.CAMPAIGN_LAUNCHED],
    exceptions: ['Fuera de la franja'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['HAPPY_HOUR', 'TIME_BASED'],
    compatibleCampaigns: ['flash'],
    dependencies: ['Promotion Engine con restricción horaria'],
    compatibleTemplates: [],
    examples: ['Restaurante: 3-5pm 2x1', 'Car Wash: descuento entre semana al mediodía'],
    notes: 'Usa schedule.hours para acotar la franja; recurrente y editable.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 15 * * 1-5' },
      variables: ['cliente.nombre', 'happyhour.franja'],
      channels: ['push'],
      schedule: { hours: { from: '15:00', to: '17:00' } },
      steps: [
        {
          label: 'Activar happy hour',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_happy_hour' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Happy Hour, {{cliente.nombre}}', body: 'Oferta activa {{happyhour.franja}}. ¡Ven ahora!' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-017',
    name: 'Campaña de fecha comercial (Black Friday / Navidad / Verano)',
    objective: 'Orquestar grandes fechas comerciales con oferta + gamificación.',
    problem: 'Las grandes fechas exigen coordinación multi-motor, no un aviso suelto.',
    whenToUse: 'En fechas comerciales clave del calendario.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (fecha comercial)'],
    conditions: ['Fecha comercial activa'],
    variables: ['cliente.nombre', 'evento.nombre'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'gamification', 'benefit', 'analytics'],
    flow: ['Llega la fecha comercial', 'Se lanza promo destacada + misión', 'Se comunica a todos los segmentos', 'Se mide el ROI'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración del evento comercial (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_FINISHED],
    exceptions: ['Fuera de fecha'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['misiones', 'puntos', 'ranking'],
    compatibleBenefits: ['CAR-004', 'CAR-001'],
    compatiblePromotions: ['BLACK_FRIDAY', 'SEASONAL'],
    compatibleCampaigns: ['estacional', 'lanzamiento'],
    dependencies: ['Promotion/Gamification Engine'],
    compatibleTemplates: [],
    examples: ['Black Friday, Navidad, Verano, Regreso a clases'],
    notes: 'El nombre y las fechas del evento son editables; una sola plantilla sirve para todas las fechas.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 8 25 11 *', params: { event: 'editable' } },
      variables: ['cliente.nombre', 'evento.nombre'],
      channels: ['push', 'email', 'whatsapp'],
      steps: [
        {
          label: 'Orquestar fecha comercial',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'create_event_promo' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'start_mission' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡{{evento.nombre}} llegó, {{cliente.nombre}}!', body: 'Ofertas especiales por tiempo limitado.' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-018',
    name: 'Campaña de fidelización continua',
    objective: 'Sostener el enganche de clientes activos con beneficios recurrentes.',
    problem: 'Los clientes leales se pierden si no se les cultiva de forma continua.',
    whenToUse: 'De forma recurrente para el segmento fiel.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (ciclo de fidelización)'],
    conditions: ['Segmento fiel/activo'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'campaign', 'benefit', 'reward', 'gamification', 'analytics'],
    flow: ['Comienza el ciclo', 'Se entrega un beneficio de fidelidad + puntos', 'Se comunica', 'Se mide la retención'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: ['Cadencia del ciclo (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Segmento no fiel'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'niveles', 'rachas'],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['LOYALTY'],
    compatibleCampaigns: ['fidelizacion'],
    dependencies: ['Benefit/Reward Engine'],
    compatibleTemplates: [],
    examples: ['Beneficio mensual para clientes fieles + puntos de reconocimiento'],
    notes: 'Coordina beneficio + puntos de forma recurrente; refuerza el hábito ya adquirido.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 10 1 * *' },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Fidelizar',
          condition: 'cliente.segmento == "fiel"',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 40 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Gracias por tu lealtad, {{cliente.nombre}}', body: 'Un beneficio de este mes para ti.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-019',
    name: 'Optimización de campaña (pausa/reanuda/clona)',
    objective: 'Ajustar la campaña en marcha según su rendimiento.',
    problem: 'Las campañas que no se optimizan desperdician presupuesto.',
    whenToUse: 'Durante la ejecución, para reaccionar al rendimiento.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (evaluación de rendimiento)'],
    conditions: ['Campaña activa con métricas disponibles'],
    variables: ['campana.nombre', 'campana.roi', 'campana.presupuestoRestante'],
    engines: ['rule', 'action', 'campaign', 'analytics'],
    flow: ['Se evalúa el rendimiento', 'Si bajo ROI o sin presupuesto: pausar; si alto ROI: escalar/clonar', 'Se registra la decisión'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Evaluación periódica (editable)'],
    events: [EV.CAMPAIGN_PAUSED, EV.CAMPAIGN_RESUMED],
    exceptions: ['Sin métricas suficientes'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: [],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: [],
    dependencies: ['Campaign/Analytics Engine con métricas en vivo'],
    compatibleTemplates: [],
    examples: ['ROI bajo o presupuesto agotado → pausa; ROI alto → clonar a otro segmento'],
    notes: 'Cierra el ciclo de vida (optimización): pausar/reanudar/finalizar/duplicar según datos.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 */6 * * *' },
      variables: ['campana.nombre', 'campana.roi', 'campana.presupuestoRestante'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Pausar si bajo rendimiento',
          condition: 'campana.roi < 1 OR campana.presupuestoRestante <= 0',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'campaign', action: 'pause' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'campana.pausada_por_rendimiento' } },
          ],
          chain: { event: EV.CAMPAIGN_PAUSED },
        },
        {
          label: 'Escalar si alto rendimiento',
          condition: 'campana.roi >= 3 AND campana.presupuestoRestante > 0',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'campaign', action: 'clone_to_segment' } },
          ],
          chain: { event: EV.CAMPAIGN_CHILD_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'CAMP-020',
    name: 'Campaña automática basada en IA',
    objective: 'Dejar que la IA elija segmento, oferta y momento óptimos.',
    problem: 'La orquestación manual no escala ni optimiza como un modelo.',
    whenToUse: 'Cuando la arquitectura de IA esté disponible.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (planificación por IA)'],
    conditions: ['Modelo disponible', 'Oportunidad detectada por el modelo'],
    variables: ['cliente.nombre', 'ia.segmento', 'ia.oferta', 'ia.mejorMomento'],
    engines: ['rule', 'action', 'campaign', 'promotion', 'benefit', 'analytics'],
    flow: ['La IA identifica la oportunidad', 'Selecciona segmento + oferta + momento', 'Se orquesta la campaña', 'Se mide y retroalimenta al modelo'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Planificación recurrente (editable)'],
    events: [EV.CAMPAIGN_LAUNCHED, EV.CAMPAIGN_CONVERTED],
    exceptions: ['Modelo no disponible (se omite sin error)'],
    compatibleMembershipModels: [ANY],
    compatibleGamification: ['puntos', 'misiones'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['PREDICTIVE'],
    compatibleCampaigns: ['ia'],
    dependencies: ['Motor de IA (integrable vía INVOKE_MODULE sin cambiar la lógica)'],
    compatibleTemplates: [],
    examples: ['La IA lanza la mejor campaña para cada micro-segmento automáticamente'],
    notes: 'Diseñado para conectar con la futura IA sin modificar el motor: segmento/oferta/momento por INVOKE_MODULE.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 7 * * *' },
      variables: ['cliente.nombre', 'ia.oferta'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Orquestar por IA',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'ai', action: 'plan_campaign' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Algo pensado para ti, {{cliente.nombre}}', body: '{{ia.oferta}}' } },
          ],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),
]

/** Lista mutable de los playbooks de campañas (para composición). */
export function campaignPlaybooks(): AutomationPlaybook[] {
  return [...CAMPAIGN_PLAYBOOKS]
}

/** Busca un playbook de campañas por su ID (ej. "CAMP-001"). */
export function getCampaignPlaybook(id: string): AutomationPlaybook | undefined {
  return CAMPAIGN_PLAYBOOKS.find((p) => p.id === id)
}
