/**
 * Biblioteca de Automation Playbooks de DECISIONES INTELIGENTES (Fase E1.10). No
 * integra IA: instala automatizaciones que TOMAN DECISIONES usando la
 * arquitectura desacoplada `src/lib/decision` (Decision Engine → Recommendation
 * Engine → Prediction → Optimization, servida por Decision Providers). Hoy el
 * único proveedor es `rule_based`; mañana se añade un AI/ML Provider sin tocar
 * estos playbooks ni el resto del sistema, y las empresas nunca ven "IA": solo
 * funcionalidades inteligentes.
 *
 * Regla de oro: el Decision Engine DECIDE (paso "Decidir", vía `INVOKE_MODULE`
 * al módulo `decision`); el Action Engine EJECUTA (paso "Ejecutar"). Nunca al
 * revés. Toda decisión pasa por el Decision Engine, toda recomendación por el
 * Recommendation Engine y toda acción por el Action Engine.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa (24 apartados, incl. "Decision Provider utilizado", "Acciones
 * sugeridas" y "Acciones ejecutadas"). Universal por diseño; nada hardcodeado.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'triggers', 'reglas', 'variables', 'segmentos',
  'prioridad', 'umbrales', 'decisionProvider', 'horarios', 'idioma', 'sucursales',
  'limites',
] as const

// KPIs típicos de decisiones/recomendaciones.
const DEC_KPIS = [
  'precision_recomendacion', 'aceptacion_recomendacion', 'conversion_recomendada',
  'oportunidades_detectadas', 'riesgos_detectados', 'churn_evitado',
  'renovaciones_previstas', 'roi_por_decision', 'acciones_priorizadas', 'cobertura',
] as const

/** Helper: completa los apartados comunes de un playbook de decisiones. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines' | 'decisionProvider'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable' | 'decisionProvider'>>,
): AutomationPlaybook {
  return {
    category: 'decisiones',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? DEC_KPIS,
    engines: p.engines ?? ['rule', 'action', 'analytics'],
    decisionProvider: p.decisionProvider ?? 'rule_based',
    ...p,
  }
}

// Paso reutilizable: "Decidir" (Decision Engine) — NO ejecuta acciones.
function decideStep(kind: string, label = 'Decidir') {
  return {
    label,
    actions: [
      { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'decision', action: kind } },
      { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'decision.tomada', kind } },
    ],
    chain: { event: EV.DECISION_MADE },
  }
}

export const DECISION_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'DEC-001',
    name: 'Recomendación de promoción',
    objective: 'Elegir la promoción con mayor probabilidad de conversión para el cliente.',
    problem: 'Ofrecer promociones genéricas convierte menos que las recomendadas.',
    whenToUse: 'Cuando conviene ofrecer una promoción y hay que elegir cuál.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento/segmento: cliente elegible para promoción'],
    conditions: ['Hay datos de historial/frecuencia/segmento'],
    variables: ['cliente.nombre', 'cliente.segmento', 'cliente.historial'],
    engines: ['rule', 'action', 'analytics', 'promotion'],
    decisionProvider: 'rule_based',
    flow: ['Se solicita decisión al Decision Engine (recommend_promotion)', 'El Recommendation Engine devuelve la mejor promoción', 'El Action Engine la aplica', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE],
    suggestedActions: ['aplicar_promocion_recomendada'],
    executedActions: [ACTION_TYPES.INVOKE_MODULE],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Sin candidatos', 'Sin datos suficientes (se omite sin error)'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['PERSONALIZED'],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Decision Engine (rule_based)', 'Promotion Engine'],
    compatibleTemplates: [],
    examples: ['Cliente premium → promo premium; sensible a precio → promo de descuento'],
    notes: 'El Decision Engine decide; el Action Engine aplica. Cambiar a un AI Provider no altera este playbook.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'elegible_promocion' } },
      variables: ['cliente.nombre', 'cliente.segmento'],
      channels: ['push', 'email'],
      steps: [
        decideStep('recommend_promotion'),
        {
          label: 'Ejecutar promoción recomendada',
          actions: [{ type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'promotion', action: 'apply_recommended' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-002',
    name: 'Recomendación de membresía (upgrade/downgrade/permanencia)',
    objective: 'Sugerir el mejor movimiento de membresía según el comportamiento.',
    problem: 'Los clientes están en el plan equivocado y no lo saben.',
    whenToUse: 'Al evaluar el ajuste del plan de un cliente/miembro.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado / segmento: revisión de plan'],
    conditions: ['Datos de uso/gasto disponibles'],
    variables: ['cliente.nombre', 'membresia.usosPeriodo', 'membresia.limite'],
    engines: ['rule', 'action', 'analytics', 'membership'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine (recommend_membership) compara uso vs planes', 'Recomienda upgrade/downgrade/permanencia', 'El Action Engine ejecuta la sugerencia', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE],
    suggestedActions: ['recomendar_upgrade', 'recomendar_downgrade', 'mantener_plan'],
    executedActions: [ACTION_TYPES.INVOKE_MODULE],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Sin planes alternativos', 'Datos insuficientes'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['UPGRADE'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Decision Engine', 'Membership Engine'],
    compatibleTemplates: [],
    examples: ['Uso alto → upgrade; uso bajo → downgrade/retención; uso ideal → permanencia'],
    notes: 'La comparación con planes existentes la nutre Analytics; el Decision Engine decide el movimiento.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'revision_plan' } },
      variables: ['cliente.nombre', 'membresia.usosPeriodo'],
      channels: ['email', 'push'],
      steps: [
        decideStep('recommend_membership'),
        {
          label: 'Ejecutar recomendación de plan',
          actions: [{ type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'membership', action: 'apply_recommendation' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-003',
    name: 'Recomendación de beneficios',
    objective: 'Seleccionar el beneficio con mayor probabilidad de utilización.',
    problem: 'Entregar beneficios que no se usan desperdicia presupuesto.',
    whenToUse: 'Cuando se va a entregar un beneficio y hay que elegir cuál.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento/segmento: momento de entregar beneficio'],
    conditions: ['Historial de uso de beneficios disponible'],
    variables: ['cliente.nombre', 'cliente.beneficiosUsados'],
    engines: ['rule', 'action', 'analytics', 'benefit'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine (recommend_benefit) rankea beneficios por afinidad', 'Recomienda el mejor', 'El Action Engine lo aplica', 'Se mide el uso'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT],
    suggestedActions: ['aplicar_beneficio_recomendado'],
    executedActions: [ACTION_TYPES.APPLY_BENEFIT],
    events: [EV.DECISION_MADE, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Sin beneficios elegibles'],
    compatibleBenefits: ['CAR-004', 'CAR-011', 'CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Decision Engine', 'Benefit Engine (selector estratégico)'],
    compatibleTemplates: [],
    examples: ['Cliente que usa mucho el aroma → recomendar ese tipo de beneficio'],
    notes: 'El código de beneficio recomendado se aplica por el Action Engine; el Decision Engine solo lo elige.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'entregar_beneficio' } },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        decideStep('recommend_benefit'),
        {
          label: 'Aplicar beneficio recomendado',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: '{{decision.recomendacion}}' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Un beneficio para ti, {{cliente.nombre}}', body: 'Pensamos que te va a encantar.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-004',
    name: 'Recomendación de campaña para un segmento',
    objective: 'Determinar qué campaña tiene mayor probabilidad de éxito para un segmento.',
    problem: 'Elegir mal la campaña por segmento desperdicia alcance y presupuesto.',
    whenToUse: 'Al planificar qué campaña lanzar a un segmento.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (planificación de campañas)'],
    conditions: ['Segmento con historial de campañas'],
    variables: ['segmento.nombre', 'segmento.metricas'],
    engines: ['rule', 'action', 'analytics', 'campaign'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine (recommend_campaign) evalúa candidatos', 'Recomienda la campaña de mayor probabilidad', 'El Action Engine la lanza', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['lanzar_campana_recomendada'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.CAMPAIGN_LAUNCHED],
    exceptions: ['Sin campañas candidatas'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Decision Engine', 'Campaign Engine (E1.8)'],
    compatibleTemplates: [],
    examples: ['Segmento inactivo → campaña de recuperación; segmento fiel → fidelización'],
    notes: 'Elige entre las campañas de E1.8; la ejecución la hace el Campaign/Action Engine.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 8 * * 1' },
      variables: ['segmento.nombre'],
      channels: ['inapp'],
      steps: [
        decideStep('recommend_campaign'),
        {
          label: 'Lanzar campaña recomendada',
          actions: [{ type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: '{{decision.recomendacion}}' } }],
          chain: { event: EV.CAMPAIGN_LAUNCHED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-005',
    name: 'Recomendación de recompensa',
    objective: 'Seleccionar la recompensa más adecuada según el comportamiento.',
    problem: 'Una recompensa poco relevante no refuerza el comportamiento deseado.',
    whenToUse: 'Cuando se va a otorgar una recompensa.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: comportamiento a recompensar'],
    conditions: ['Perfil de recompensas del cliente disponible'],
    variables: ['cliente.nombre', 'cliente.perfilRecompensa'],
    engines: ['rule', 'action', 'analytics', 'reward'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine (recommend_reward) elige la recompensa', 'El Action Engine la otorga', 'Se mide el efecto'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.ADD_POINTS],
    suggestedActions: ['otorgar_recompensa_recomendada'],
    executedActions: [ACTION_TYPES.ADD_POINTS],
    events: [EV.DECISION_MADE, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Sin recompensas elegibles'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Decision Engine', 'Reward Engine'],
    compatibleTemplates: [],
    examples: ['Sensible a estatus → nivel/insignia; sensible a precio → beneficio'],
    notes: 'El tipo de recompensa (puntos, beneficio, nivel…) lo decide el Decision Engine; ejecuta el Action Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_PURCHASE },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        decideStep('recommend_reward'),
        {
          label: 'Otorgar recompensa recomendada',
          actions: [{ type: ACTION_TYPES.ADD_POINTS, params: { rewardCode: '{{decision.recomendacion}}' } }],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-006',
    name: 'Predicción de abandono (churn)',
    objective: 'Estimar el riesgo de abandono para actuar a tiempo.',
    problem: 'Reaccionar tarde al abandono es más caro que anticiparlo.',
    whenToUse: 'De forma recurrente sobre la base de clientes.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (scoring de churn)'],
    conditions: ['Datos de comportamiento disponibles'],
    variables: ['cliente.nombre', 'cliente.diasSinActividad', 'cliente.frecuenciaHabitual'],
    engines: ['rule', 'action', 'analytics', 'automation'],
    decisionProvider: 'rule_based',
    flow: ['Prediction Framework (predict_churn) calcula el riesgo por reglas/umbrales', 'Si riesgo alto, se marca y se dispara recuperación', 'El Action Engine ejecuta'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['marcar_riesgo', 'iniciar_recuperacion'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.RISK_DETECTED],
    exceptions: ['Datos insuficientes (se omite sin error)'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['REACTIVATION'],
    compatibleCampaigns: ['recuperacion'],
    dependencies: ['Decision Engine (Prediction Framework)', 'Automation Engine (recuperación E1.5)'],
    compatibleTemplates: [],
    examples: ['Score de churn alto → iniciar REC-002/REC-003'],
    notes: 'Hoy por reglas/umbrales; mañana un modelo predictivo, sin cambiar el playbook. Los umbrales son editables.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 7 * * *' },
      variables: ['cliente.nombre', 'cliente.diasSinActividad'],
      channels: ['inapp'],
      steps: [
        decideStep('predict_churn', 'Predecir churn'),
        {
          label: 'Actuar sobre riesgo alto',
          condition: 'decision.banda == "high"',
          actions: [
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'riesgo.detectado' } },
            { type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.REC-002' } },
          ],
          chain: { event: EV.RISK_DETECTED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-007',
    name: 'Predicción de renovación',
    objective: 'Estimar la probabilidad de renovación para priorizar esfuerzos.',
    problem: 'No priorizar renovaciones pierde ingresos recurrentes evitables.',
    whenToUse: 'Antes del vencimiento de membresías/suscripciones.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (scoring de renovación)'],
    conditions: ['Membresía activa próxima a vencer'],
    variables: ['cliente.nombre', 'membresia.usosPeriodo', 'membresia.mesesActivo'],
    engines: ['rule', 'action', 'analytics', 'membership', 'automation'],
    decisionProvider: 'rule_based',
    flow: ['Prediction Framework (predict_renewal) estima la probabilidad', 'Baja probabilidad → campaña de renovación reforzada; alta → recordatorio simple', 'El Action Engine ejecuta'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['reforzar_renovacion', 'recordatorio_simple'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Sin membresía próxima a vencer'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['RENEWAL'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Decision Engine (Prediction Framework)', 'Membership/Automation Engine'],
    compatibleTemplates: [],
    examples: ['Prob. baja de renovar → MEM-007 con incentivo; alta → recordatorio estándar'],
    notes: 'Prioriza el esfuerzo donde más se necesita; los umbrales son editables.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 7 * * *' },
      variables: ['cliente.nombre', 'membresia.mesesActivo'],
      channels: ['inapp'],
      steps: [
        decideStep('predict_renewal', 'Predecir renovación'),
        {
          label: 'Reforzar si baja probabilidad',
          condition: 'decision.banda == "low"',
          actions: [{ type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.MEM-007' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-008',
    name: 'Detección de oportunidades',
    objective: 'Detectar clientes con potencial VIP, listos para upgrade o programas especiales.',
    problem: 'Las oportunidades de valor pasan desapercibidas sin detección automática.',
    whenToUse: 'De forma recurrente sobre la base de clientes.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (detección de oportunidades)'],
    conditions: ['Datos de LTV/uso/comportamiento disponibles'],
    variables: ['cliente.nombre', 'cliente.ltv', 'cliente.totalVisitas'],
    engines: ['rule', 'action', 'analytics', 'membership', 'campaign'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine (detect_opportunity) evalúa señales', 'Detecta VIP/upgrade/programa especial', 'El Action Engine dispara la campaña adecuada', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['marcar_oportunidad', 'iniciar_campana_especifica'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.OPPORTUNITY_DETECTED],
    exceptions: ['Sin oportunidades claras'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['VIP', 'UPGRADE'],
    compatibleCampaigns: ['vip', 'membresias'],
    dependencies: ['Decision Engine', 'Campaign/Membership Engine'],
    compatibleTemplates: [],
    examples: ['Alto LTV → potencial VIP; activo sin membresía → listo para plan'],
    notes: 'Cada oportunidad puede encadenar la campaña adecuada (CAMP-009/CAMP-010).',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 6 * * 1' },
      variables: ['cliente.nombre', 'cliente.ltv'],
      channels: ['inapp'],
      steps: [
        decideStep('detect_opportunity', 'Detectar oportunidad'),
        {
          label: 'Actuar sobre la oportunidad',
          actions: [
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'oportunidad.detectada' } },
            { type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: '{{decision.recomendacion}}' } },
          ],
          chain: { event: EV.OPPORTUNITY_DETECTED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-009',
    name: 'Optimización continua de estrategias',
    objective: 'Identificar la estrategia histórica más efectiva y recomendar reutilizarla.',
    problem: 'Repetir estrategias sin comparar resultados desperdicia potencial.',
    whenToUse: 'Periódicamente, comparando resultados históricos.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (revisión de rendimiento)'],
    conditions: ['Hay histórico de estrategias con métricas'],
    variables: ['estrategia.candidatas', 'estrategia.metricas'],
    engines: ['rule', 'action', 'analytics', 'automation'],
    decisionProvider: 'rule_based',
    flow: ['Optimization Engine compara ROI/conversión históricos', 'Recomienda la mejor estrategia', 'El Action Engine la reutiliza/clona', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['reutilizar_mejor_estrategia'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Sin histórico suficiente'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: [],
    dependencies: ['Decision Engine (Optimization Engine)', 'Analytics con histórico'],
    compatibleTemplates: [],
    examples: ['Entre 3 campañas pasadas, reutilizar la de mejor ROI/conversión'],
    notes: 'El Optimization Engine rankea por ROI y conversión (pesos editables) y recomienda reutilizar la ganadora.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 6 1 * *' },
      variables: ['estrategia.candidatas'],
      channels: ['inapp'],
      steps: [
        decideStep('optimize_strategy', 'Optimizar'),
        {
          label: 'Reutilizar la mejor estrategia',
          actions: [{ type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: '{{decision.recomendacion}}' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-010',
    name: 'Next Best Action',
    objective: 'Determinar la siguiente mejor acción para un cliente (o no ejecutar ninguna).',
    problem: 'Actuar sin priorizar genera ruido y desperdicia oportunidades.',
    whenToUse: 'Cuando hay que decidir el siguiente paso con un cliente.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: interacción / segmento a evaluar'],
    conditions: ['Datos del cliente disponibles'],
    variables: ['cliente.nombre', 'cliente.compras', 'cliente.tieneMembresia'],
    engines: ['rule', 'action', 'analytics', 'benefit', 'membership', 'gamification'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine (next_best_action) evalúa la escalera de reglas', 'Devuelve la mejor acción: beneficio, membresía, recompensa, campaña, esperar o no ejecutar', 'El Action Engine ejecuta lo recomendado (o nada)', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE],
    suggestedActions: ['enviar_beneficio', 'recomendar_membresia', 'otorgar_recompensa', 'activar_campana', 'esperar', 'no_ejecutar'],
    executedActions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT],
    events: [EV.DECISION_MADE, EV.NEXT_BEST_ACTION_READY],
    exceptions: ['Sin acción prioritaria → esperar (no ejecutar)'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Decision Engine', 'Action Engine + motores destino'],
    compatibleTemplates: [],
    examples: ['Sin compra → beneficio; riesgo alto → retención; cerca de recompensa → nudge; nada → esperar'],
    notes: 'Puede recomendar EXPLÍCITAMENTE "esperar/no ejecutar". El Decision Engine decide; el Action Engine ejecuta.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_VISIT },
      variables: ['cliente.nombre', 'cliente.compras'],
      channels: ['push'],
      steps: [
        decideStep('next_best_action', 'Decidir mejor acción'),
        {
          label: 'Ejecutar la acción recomendada',
          condition: 'decision.accion != "wait"',
          actions: [{ type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'action', action: 'execute_recommendation' } }],
          chain: { event: EV.NEXT_BEST_ACTION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-011',
    name: 'Priorización de acciones (cola inteligente)',
    objective: 'Ordenar las acciones pendientes por impacto esperado.',
    problem: 'Ejecutar todo a la vez satura al cliente y diluye el impacto.',
    whenToUse: 'Cuando hay varias acciones candidatas para un cliente/segmento.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado / evento: varias acciones candidatas'],
    conditions: ['Existen acciones candidatas con score'],
    variables: ['cliente.nombre', 'acciones.candidatas'],
    engines: ['rule', 'action', 'analytics'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine rankea las acciones candidatas', 'Se ejecuta solo la de mayor prioridad (respetando límites)', 'El resto queda en cola', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE],
    suggestedActions: ['ejecutar_accion_top', 'encolar_resto'],
    executedActions: [ACTION_TYPES.INVOKE_MODULE],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Sin acciones candidatas'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: [],
    dependencies: ['Decision Engine', 'Límites de frecuencia de contacto'],
    compatibleTemplates: [],
    examples: ['Entre beneficio, encuesta y upsell → ejecutar el de mayor impacto hoy'],
    notes: 'Evita la fatiga de contacto respetando límites; prioriza por score del Decision Engine.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'acciones_pendientes' } },
      variables: ['cliente.nombre'],
      channels: ['inapp'],
      limits: { maxPerSubject: 1, perPeriod: 'DAY' },
      steps: [
        decideStep('next_best_action', 'Priorizar'),
        {
          label: 'Ejecutar la acción top',
          actions: [{ type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'action', action: 'execute_top' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-012',
    name: 'Detección de riesgos (multi-señal)',
    objective: 'Detectar riesgos (abandono, no renovación, baja de gasto) y priorizarlos.',
    problem: 'Los riesgos dispersos no se atienden sin una detección unificada.',
    whenToUse: 'De forma recurrente sobre la base de clientes.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (detección de riesgos)'],
    conditions: ['Señales de comportamiento disponibles'],
    variables: ['cliente.nombre', 'cliente.diasSinActividad', 'cliente.gastoALaBaja'],
    engines: ['rule', 'action', 'analytics', 'automation'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine combina señales de riesgo', 'Prioriza los clientes en mayor riesgo', 'El Action Engine dispara la mitigación', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_INTERNAL_NOTIFICATION],
    suggestedActions: ['marcar_riesgo', 'alertar_equipo', 'iniciar_mitigacion'],
    executedActions: [ACTION_TYPES.SEND_INTERNAL_NOTIFICATION, ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.RISK_DETECTED],
    exceptions: ['Sin señales de riesgo'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['REACTIVATION'],
    compatibleCampaigns: ['recuperacion'],
    dependencies: ['Decision Engine', 'Automation Engine'],
    compatibleTemplates: [],
    examples: ['Alto riesgo de churn + alto LTV → alerta al equipo + recuperación prioritaria'],
    notes: 'Combina varias señales; para clientes valiosos alerta al equipo (contacto humano).',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 7 * * *' },
      variables: ['cliente.nombre', 'cliente.diasSinActividad'],
      channels: ['inapp'],
      steps: [
        decideStep('predict_churn', 'Evaluar riesgo'),
        {
          label: 'Mitigar riesgo alto',
          condition: 'decision.banda == "high"',
          actions: [
            { type: ACTION_TYPES.SEND_INTERNAL_NOTIFICATION, params: { title: 'Cliente en riesgo', body: 'Priorizar a {{cliente.nombre}}.' } },
            { type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.REC-004' } },
          ],
          chain: { event: EV.RISK_DETECTED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-013',
    name: 'Recomendación de a quién impulsar a referir',
    objective: 'Detectar los clientes con mayor probabilidad de referir con éxito.',
    problem: 'Pedir referidos a todos por igual rinde menos que enfocarse en los mejores.',
    whenToUse: 'Al planificar una campaña de referidos.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado / segmento: candidatos a referir'],
    conditions: ['Datos de satisfacción/actividad disponibles'],
    variables: ['cliente.nombre', 'cliente.satisfaccion'],
    engines: ['rule', 'action', 'analytics', 'referral'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine detecta a los mejores candidatos a referir', 'El Action Engine les lanza la invitación a referir', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['impulsar_referido'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.REFERRAL_SHARED],
    exceptions: ['Sin candidatos'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['REFERRAL'],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Decision Engine', 'Referral Engine (E1.7)'],
    compatibleTemplates: [],
    examples: ['Clientes satisfechos y activos → priorizar para campaña de referidos (REF/CAMP-011)'],
    notes: 'Enfoca el esfuerzo de referidos donde la probabilidad de éxito es mayor.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'candidatos_referir' } },
      variables: ['cliente.nombre'],
      channels: ['inapp'],
      steps: [
        decideStep('detect_opportunity', 'Detectar candidatos'),
        {
          label: 'Impulsar referido',
          actions: [{ type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.CAMP-011' } }],
          chain: { event: EV.REFERRAL_SHARED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-014',
    name: 'Recomendación de reto/misión ideal',
    objective: 'Elegir la misión de gamificación con mayor probabilidad de completarse.',
    problem: 'Misiones mal ajustadas al cliente no se completan y no cambian el comportamiento.',
    whenToUse: 'Al asignar una misión/reto a un cliente.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado / evento: momento de asignar misión'],
    conditions: ['Historial de misiones/comportamiento disponible'],
    variables: ['cliente.nombre', 'cliente.frecuenciaHabitual'],
    engines: ['rule', 'action', 'analytics', 'gamification'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine elige la misión de mayor probabilidad de éxito', 'El Action Engine la asigna (GAM-002)', 'Se mide la finalización'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RUN_WORKFLOW],
    suggestedActions: ['asignar_mision_recomendada'],
    executedActions: [ACTION_TYPES.RUN_WORKFLOW],
    events: [EV.DECISION_MADE, EV.GAMI_MISSION_STARTED],
    exceptions: ['Gamificación desactivada'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['MISSION'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Decision Engine', 'Gamification Engine (E1.9)'],
    compatibleTemplates: [],
    examples: ['Cliente de baja frecuencia → misión asequible; alta → reto exigente'],
    notes: 'Ajusta la dificultad al cliente para maximizar la finalización (y el cambio de comportamiento).',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'asignar_mision' } },
      variables: ['cliente.nombre'],
      channels: ['inapp'],
      steps: [
        decideStep('recommend_reward', 'Elegir misión'),
        {
          label: 'Asignar misión recomendada',
          actions: [{ type: ACTION_TYPES.RUN_WORKFLOW, params: { workflow: 'playbook.GAM-002' } }],
          chain: { event: EV.GAMI_MISSION_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-015',
    name: 'Selección de mejor canal y momento',
    objective: 'Decidir por qué canal y en qué momento contactar a cada cliente.',
    problem: 'El mensaje correcto en canal/momento equivocado convierte poco.',
    whenToUse: 'Antes de enviar cualquier comunicación relevante.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: comunicación a enviar'],
    conditions: ['Historial de interacción por canal/horario disponible'],
    variables: ['cliente.nombre', 'cliente.mejorCanal', 'cliente.mejorMomento'],
    engines: ['rule', 'action', 'analytics'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine elige canal + momento óptimos', 'El Action Engine programa/envía por ese canal', 'Se mide la apertura/clic'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SCHEDULE_TASK],
    suggestedActions: ['elegir_canal', 'elegir_momento'],
    executedActions: [ACTION_TYPES.SCHEDULE_TASK, ACTION_TYPES.SEND_PUSH],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Sin historial de interacción'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Decision Engine', 'Analytics de interacción'],
    compatibleTemplates: [],
    examples: ['Cliente que abre WhatsApp por la mañana → enviar por WhatsApp a esa hora'],
    notes: 'Optimiza canal y timing; reutilizable por cualquier playbook que envíe comunicaciones.',
    config: {
      trigger: { type: 'EVENT', event: EV.RECOMMENDATION_READY },
      variables: ['cliente.nombre', 'cliente.mejorCanal', 'cliente.mejorMomento'],
      channels: ['push', 'email', 'whatsapp', 'sms'],
      steps: [
        decideStep('next_best_action', 'Elegir canal/momento'),
        {
          label: 'Programar envío óptimo',
          actions: [{ type: ACTION_TYPES.SCHEDULE_TASK, params: { channel: '{{cliente.mejorCanal}}', at: '{{cliente.mejorMomento}}' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-016',
    name: 'Decisión de esperar / no ejecutar (anti-fatiga)',
    objective: 'Evitar la sobre-comunicación decidiendo NO actuar cuando no conviene.',
    problem: 'Comunicar de más quema la base y reduce la efectividad futura.',
    whenToUse: 'Antes de ejecutar cualquier acción hacia el cliente.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: acción candidata a ejecutar'],
    conditions: ['Historial de contactos recientes disponible'],
    variables: ['cliente.nombre', 'cliente.contactosRecientes'],
    engines: ['rule', 'action', 'analytics'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine evalúa fatiga/relevancia', 'Si conviene esperar, NO se ejecuta ninguna acción', 'Si conviene, se ejecuta', 'Se registra la decisión'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RECORD_EVENT],
    suggestedActions: ['esperar', 'ejecutar'],
    executedActions: [ACTION_TYPES.RECORD_EVENT],
    events: [EV.DECISION_MADE],
    exceptions: ['Sin historial de contactos (por defecto, permite ejecutar)'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: [],
    dependencies: ['Decision Engine', 'Límites de contacto'],
    compatibleTemplates: [],
    examples: ['Ya contactado 3 veces esta semana → esperar (no ejecutar)'],
    notes: '"No ejecutar" es una decisión válida y de primera clase; protege la salud de la base.',
    config: {
      trigger: { type: 'EVENT', event: EV.RECOMMENDATION_READY },
      variables: ['cliente.nombre', 'cliente.contactosRecientes'],
      channels: ['inapp'],
      steps: [
        decideStep('next_best_action', 'Decidir esperar/ejecutar'),
        {
          label: 'Registrar decisión de esperar',
          condition: 'decision.accion == "wait"',
          actions: [{ type: ACTION_TYPES.RECORD_EVENT, params: { event: 'decision.esperar' } }],
        },
      ],
    },
  }),

  pb({
    id: 'DEC-017',
    name: 'Segmentación inteligente',
    objective: 'Asignar automáticamente el mejor segmento a cada cliente.',
    problem: 'Segmentos desactualizados degradan todas las estrategias.',
    whenToUse: 'De forma recurrente o tras cambios de comportamiento.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado / evento: recalcular segmento'],
    conditions: ['Datos de comportamiento disponibles'],
    variables: ['cliente.nombre', 'cliente.segmento'],
    engines: ['rule', 'action', 'analytics', 'campaign'],
    decisionProvider: 'rule_based',
    flow: ['Decision Engine calcula el segmento óptimo por reglas', 'El Action Engine actualiza el segmento', 'Se disparan las automatizaciones del nuevo segmento', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.RECORD_EVENT],
    suggestedActions: ['asignar_segmento'],
    executedActions: [ACTION_TYPES.RECORD_EVENT],
    events: [EV.DECISION_MADE, EV.CLIENT_BEHAVIOR_CHANGED],
    exceptions: ['Datos insuficientes'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['personalizacion'],
    dependencies: ['Decision Engine', 'Analytics'],
    compatibleTemplates: [],
    examples: ['Reclasificar a "muy activo" / "en riesgo" según el comportamiento reciente'],
    notes: 'Mantiene los segmentos vivos; alimenta a todas las demás bibliotecas de playbooks.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 5 * * *' },
      variables: ['cliente.nombre', 'cliente.segmento'],
      channels: ['inapp'],
      steps: [
        decideStep('next_best_action', 'Calcular segmento'),
        {
          label: 'Actualizar segmento',
          actions: [{ type: ACTION_TYPES.RECORD_EVENT, params: { event: 'segmento.actualizado' } }],
          chain: { event: EV.CLIENT_BEHAVIOR_CHANGED },
        },
      ],
    },
  }),

  pb({
    id: 'DEC-018',
    name: 'Preparación para IA (proveedor futuro)',
    objective: 'Dejar lista una decisión que hoy resuelve reglas y mañana un AI Provider.',
    problem: 'Cambiar de reglas a IA no debe requerir rehacer las automatizaciones.',
    whenToUse: 'Como patrón de referencia para cualquier decisión inteligente.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento/segmento: decisión requerida'],
    conditions: ['Contexto de negocio disponible'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'analytics'],
    decisionProvider: 'rule_based',
    flow: ['Se solicita al Decision Engine (providerHint opcional)', 'Hoy responde rule_based; mañana un AI Provider registrado', 'El Action Engine ejecuta la recomendación', 'Las empresas nunca ven "IA"'],
    actions: [ACTION_TYPES.INVOKE_MODULE],
    suggestedActions: ['ejecutar_recomendacion'],
    executedActions: [ACTION_TYPES.INVOKE_MODULE],
    events: [EV.DECISION_MADE, EV.RECOMMENDATION_READY],
    exceptions: ['Ningún proveedor soporta el tipo (se omite sin error)'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: [],
    dependencies: ['Decision Engine (registro multi-proveedor)'],
    compatibleTemplates: [],
    examples: ['El día que se registre un AI Provider, este playbook lo usa sin cambios'],
    notes: 'El `decisionProvider` es editable: `rule_based` hoy, `ai`/`ml`/`custom` en el futuro, sin tocar el playbook.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'decision_requerida' } },
      variables: ['cliente.nombre'],
      channels: ['inapp'],
      steps: [
        decideStep('next_best_action', 'Decidir (proveedor configurable)'),
        {
          label: 'Ejecutar recomendación',
          actions: [{ type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'action', action: 'execute_recommendation' } }],
          chain: { event: EV.RECOMMENDATION_READY },
        },
      ],
    },
  }),
]

/** Lista mutable de los playbooks de decisiones (para composición). */
export function decisionPlaybooks(): AutomationPlaybook[] {
  return [...DECISION_PLAYBOOKS]
}

/** Busca un playbook de decisiones por su ID (ej. "DEC-001"). */
export function getDecisionPlaybook(id: string): AutomationPlaybook | undefined {
  return DECISION_PLAYBOOKS.find((p) => p.id === id)
}
