/**
 * Biblioteca de Automation Playbooks de GAMIFICACIÓN CONDUCTUAL (Fase E1.9). No
 * es "solo puntos/insignias/rankings": es un sistema de CAMBIO DE COMPORTAMIENTO
 * al servicio de objetivos comerciales (frecuencia, visitas, consumo, referidos,
 * renovaciones, uso de beneficios, hábito, retención, LTV). La gamificación
 * nunca existe por entretenimiento: cada mecánica impulsa una meta de negocio.
 *
 * Se integra de forma nativa con el resto de motores: una misión puede activar
 * promociones, una racha otorgar beneficios, un logro iniciar campañas y un nivel
 * desbloquear membresías — todo por eventos/reglas/acciones reutilizables
 * (`INVOKE_MODULE`/`RUN_WORKFLOW`/`APPLY_BENEFIT`/chaining). Los NIVELES son
 * completamente configurables: la arquitectura no depende de nombres concretos
 * (Bronce/Plata/…); se referencian por variable.
 *
 * Estrategias probadas (Duolingo/Strava/Starbucks/Nike Run Club/videojuegos)
 * convertidas en playbooks UNIVERSALES instalables sobre el Automation Engine
 * (E1). Car Wash es solo la primera industria que las usa.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa (25 apartados, incl. "Recompensas compatibles"). Nada hardcodeado por
 * industria ni por nivel: todo por variable/código.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'triggers', 'reglas', 'objetivos', 'niveles',
  'recompensas', 'variables', 'segmentos', 'horarios', 'fechas', 'duracion',
  'prioridad', 'limites', 'idioma', 'sucursales',
] as const

// KPIs típicos de gamificación conductual (siempre atados a negocio).
const GAM_KPIS = [
  'frecuencia_visitas', 'misiones_completadas', 'rachas_activas', 'retencion',
  'ltv', 'uso_beneficios', 'referidos_generados', 'renovaciones',
  'engagement', 'conversion', 'participacion_retos', 'ranking_actividad',
] as const

// Tipos de recompensa reutilizables (referencia, no hardcode).
const REWARDS = ['puntos', 'xp', 'insignias', 'niveles', 'beneficios', 'cupones', 'promociones', 'accesos', 'membresias'] as const

/** Helper: completa los apartados comunes de un playbook de gamificación. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines' | 'compatibleRewards'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable' | 'compatibleRewards'>>,
): AutomationPlaybook {
  return {
    category: 'gamificacion',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? GAM_KPIS,
    engines: p.engines ?? ['rule', 'action', 'gamification', 'analytics'],
    compatibleRewards: p.compatibleRewards ?? [...REWARDS],
    ...p,
  }
}

export const GAMIFICATION_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'GAM-001',
    name: 'Objetivos iniciales (arranque gamificado)',
    objective: 'Asignar los primeros objetivos para crear hábito desde el inicio.',
    problem: 'Sin metas iniciales, el cliente no sabe qué comportamiento repetir.',
    whenToUse: 'Al completar el onboarding o la primera compra.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: onboarding completado', 'Evento: primera compra'],
    conditions: ['Cliente sin objetivos activos'],
    variables: ['cliente.nombre', 'objetivo.meta'],
    engines: ['rule', 'action', 'gamification', 'analytics'],
    flow: ['El cliente arranca', 'Se asignan objetivos iniciales', 'Se registra el progreso base', 'Se comunica la primera meta'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.GAMI_MISSION_STARTED, EV.CLIENT_REGISTERED],
    exceptions: ['Ya tiene objetivos activos', 'Gamificación desactivada'],
    compatibleRewards: ['puntos', 'xp', 'insignias'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion', 'onboarding'],
    dependencies: ['Gamification Engine con objetivos'],
    compatibleTemplates: [],
    examples: ['“Tu primer objetivo: 3 visitas este mes”'],
    notes: 'Arranca el journey conductual; encadena hacia misiones (GAM-002).',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_ONBOARDING_COMPLETED },
      variables: ['cliente.nombre', 'objetivo.meta'],
      channels: ['push', 'inapp'],
      steps: [
        {
          label: 'Asignar objetivos iniciales',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'assign_initial_goals' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu primer reto, {{cliente.nombre}}', body: 'Cumple {{objetivo.meta}} y gana tu primera recompensa.' } },
          ],
          chain: { event: EV.GAMI_MISSION_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-002',
    name: 'Inicio de misión (diaria/semanal/mensual/estacional)',
    objective: 'Lanzar misiones que dirijan un comportamiento comercial concreto.',
    problem: 'Sin misiones, el cliente no tiene un motivo estructurado para volver.',
    whenToUse: 'Al comenzar un ciclo (día/semana/mes/temporada).',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (ciclo de misión)'],
    conditions: ['Gamificación activa', 'Segmento objetivo'],
    variables: ['cliente.nombre', 'mision.tipo', 'mision.meta'],
    engines: ['rule', 'action', 'gamification', 'promotion', 'analytics'],
    flow: ['Comienza el ciclo', 'Se crea la misión con su meta', 'Se comunica', 'Se registra el inicio'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración de la misión (editable)'],
    events: [EV.GAMI_MISSION_STARTED],
    exceptions: ['Misión ya activa', 'Gamificación desactivada'],
    compatibleRewards: ['puntos', 'xp', 'beneficios', 'insignias'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['MISSION'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification Engine con misiones'],
    compatibleTemplates: [],
    examples: ['Misión diaria: “Visita hoy”; semanal: “3 servicios”; estacional: reto de temporada'],
    notes: 'El tipo, meta y duración son editables; una misión puede activar promociones.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 8 * * 1', params: { missionType: 'editable' } },
      variables: ['cliente.nombre', 'mision.tipo', 'mision.meta'],
      channels: ['push', 'inapp'],
      steps: [
        {
          label: 'Lanzar misión',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'start_mission' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Nueva misión {{mision.tipo}}, {{cliente.nombre}}', body: 'Cumple {{mision.meta}} y gana.' } },
          ],
          chain: { event: EV.GAMI_MISSION_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-003',
    name: 'Misión completada (recompensa + siguiente meta)',
    objective: 'Recompensar el logro y encadenar el siguiente objetivo para sostener el hábito.',
    problem: 'Si la misión no se recompensa ni continúa, el impulso se pierde.',
    whenToUse: 'Cuando el cliente completa una misión.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: misión completada'],
    conditions: ['Misión cumplida'],
    variables: ['cliente.nombre', 'mision.recompensa'],
    engines: ['rule', 'action', 'gamification', 'reward', 'benefit', 'analytics'],
    flow: ['Se completa la misión', 'Se entrega la recompensa configurada', 'Se felicita', 'Se asigna la siguiente meta'],
    actions: [ACTION_TYPES.ADD_POINTS, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CLIENT_MISSION_COMPLETED, EV.GAMI_MISSION_STARTED],
    exceptions: ['Misión no cumplida'],
    compatibleRewards: ['puntos', 'xp', 'beneficios', 'insignias', 'cupones'],
    compatibleBenefits: ['CAR-004', 'CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification/Reward Engine'],
    compatibleTemplates: [],
    examples: ['Completa 3 visitas → puntos + beneficio + nueva misión'],
    notes: 'Encadena a una nueva misión para mantener el bucle conductual.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_MISSION_COMPLETED },
      variables: ['cliente.nombre', 'mision.recompensa'],
      channels: ['push', 'inapp'],
      steps: [
        {
          label: 'Recompensar y continuar',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 50 } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: '{{mision.recompensa}}' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Misión cumplida, {{cliente.nombre}}!', body: 'Ganaste tu recompensa. Aquí va tu siguiente reto.' } },
          ],
          chain: { event: EV.GAMI_MISSION_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-004',
    name: 'Racha iniciada (visitas/compras/consumo/referidos)',
    objective: 'Registrar y reforzar una racha para consolidar el hábito.',
    problem: 'Los hábitos nacientes se abandonan sin refuerzo de continuidad.',
    whenToUse: 'Cuando el cliente inicia una racha.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: alcanzó racha'],
    conditions: ['Racha activa recién formada'],
    variables: ['cliente.nombre', 'racha.tipo', 'racha.actual'],
    engines: ['rule', 'action', 'gamification', 'analytics'],
    flow: ['Se detecta la racha', 'Se registra el progreso', 'Se motiva a continuar', 'Se muestra el próximo hito'],
    actions: [ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CLIENT_STREAK_REACHED],
    exceptions: ['Gamificación desactivada'],
    compatibleRewards: ['puntos', 'xp', 'insignias'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion', 'frecuencia'],
    dependencies: ['Gamification Engine con rachas'],
    compatibleTemplates: [],
    examples: ['Racha de visitas / de compras / de referidos'],
    notes: 'El tipo de racha es una variable; sirve a frecuencia, consumo o referidos.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_STREAK_REACHED },
      variables: ['cliente.nombre', 'racha.tipo', 'racha.actual'],
      channels: ['push'],
      steps: [
        {
          label: 'Reforzar racha',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 10 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Racha de {{racha.tipo}}, {{cliente.nombre}}!', body: 'Llevas {{racha.actual}}. Sigue para el próximo premio.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-005',
    name: 'Racha perdida (recuperación temprana)',
    objective: 'Recuperar al cliente que rompe una racha antes de que abandone.',
    problem: 'Romper una racha suele preceder la caída de frecuencia.',
    whenToUse: 'Cuando el cliente pierde una racha activa.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: perdió racha'],
    conditions: ['Tenía una racha activa y la rompió'],
    variables: ['cliente.nombre', 'racha.previa'],
    engines: ['rule', 'action', 'gamification', 'benefit', 'analytics'],
    flow: ['Se detecta racha rota', 'Se ofrece retomarla con un incentivo', 'Al volver, se recupera la racha'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['Aviso inmediato y recordatorio a 48h (editable)'],
    events: [EV.CLIENT_STREAK_LOST, EV.GAMI_STREAK_RECOVERED],
    exceptions: ['Sin racha previa', 'Gamificación desactivada'],
    compatibleRewards: ['puntos', 'beneficios'],
    compatibleBenefits: ['CAR-011', 'CAR-004'],
    compatiblePromotions: ['REACTIVATION'],
    compatibleCampaigns: ['gamificacion', 'retencion'],
    dependencies: ['Gamification Engine con rachas'],
    compatibleTemplates: [],
    examples: ['“Tu racha se pausó: recupérala hoy y conserva tu progreso”'],
    notes: 'Recuperación temprana específica de racha; complementa REC/FREQ.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_STREAK_LOST },
      variables: ['cliente.nombre', 'racha.previa'],
      channels: ['push', 'whatsapp'],
      steps: [
        {
          label: 'Ofrecer recuperar racha',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu racha se pausó, {{cliente.nombre}}', body: 'Recupérala hoy y no pierdas tu progreso.' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } },
          ],
          chain: { event: EV.GAMI_STREAK_RECOVERED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-006',
    name: 'Subida de nivel (desbloqueos)',
    objective: 'Reconocer el ascenso de nivel y desbloquear beneficios/accesos.',
    problem: 'Sin recompensas al subir de nivel, el progreso pierde valor.',
    whenToUse: 'Cuando el cliente sube de nivel según reglas configurables.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: subió de nivel'],
    conditions: ['Nivel nuevo alcanzado (reglas configurables)'],
    variables: ['cliente.nombre', 'nivel.nuevo'],
    engines: ['rule', 'action', 'gamification', 'benefit', 'membership', 'analytics'],
    flow: ['Se detecta la subida', 'Se desbloquean beneficios/accesos del nivel', 'Se felicita', 'Se muestra el siguiente nivel'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.RECORD_EVENT],
    esperas: [],
    events: [EV.CLIENT_LEVEL_UP, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Nivel máximo', 'Niveles no configurados'],
    compatibleRewards: ['niveles', 'beneficios', 'accesos', 'membresias'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['LEVEL_UP'],
    compatibleCampaigns: ['gamificacion', 'fidelizacion'],
    dependencies: ['Gamification Engine con niveles configurables'],
    compatibleTemplates: [],
    examples: ['Sube a nivel superior → beneficios exclusivos + posible acceso a membresía'],
    notes: 'Niveles configurables por variable (sin nombres fijos); un nivel puede desbloquear membresías.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_LEVEL_UP },
      variables: ['cliente.nombre', 'nivel.nuevo'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Desbloquear nivel',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Nivel {{nivel.nuevo}}, {{cliente.nombre}}!', body: 'Desbloqueaste nuevos beneficios.' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'gamificacion.nivel_desbloqueado' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-007',
    name: 'Descenso de nivel (retención por reglas)',
    objective: 'Gestionar el descenso de nivel motivando a recuperarlo.',
    problem: 'Un descenso mal comunicado frustra y acelera el abandono.',
    whenToUse: 'Cuando el cliente baja de nivel por inactividad/reglas.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: descenso de nivel'],
    conditions: ['Reglas de descenso cumplidas'],
    variables: ['cliente.nombre', 'nivel.actual', 'nivel.anterior'],
    engines: ['rule', 'action', 'gamification', 'benefit', 'campaign', 'analytics'],
    flow: ['Se aplica el descenso', 'Se comunica con tono motivador', 'Se ofrece una vía rápida para recuperar el nivel', 'Se registra'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['Ventana para recuperar el nivel (editable)'],
    events: [EV.GAMI_LEVEL_DOWN, EV.CLIENT_RECOVERED],
    exceptions: ['Nivel mínimo', 'Reglas de descenso desactivadas'],
    compatibleRewards: ['niveles', 'beneficios', 'puntos'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: ['REACTIVATION'],
    compatibleCampaigns: ['gamificacion', 'retencion'],
    dependencies: ['Gamification Engine con reglas de descenso'],
    compatibleTemplates: [],
    examples: ['Baja de nivel por inactividad → “Recupéralo con 2 visitas esta semana”'],
    notes: 'El descenso es opcional y editable; siempre ofrece una vía de recuperación.',
    config: {
      trigger: { type: 'EVENT', event: EV.GAMI_LEVEL_DOWN },
      variables: ['cliente.nombre', 'nivel.actual'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Motivar recuperación de nivel',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Recupera tu nivel, {{cliente.nombre}}', body: 'Estás a poco de volver a {{nivel.anterior}}. ¡Tú puedes!' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } },
          ],
          chain: { event: EV.CLIENT_RECOVERED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-008',
    name: 'Insignia/logro desbloqueado',
    objective: 'Reconocer logros para reforzar comportamientos valiosos.',
    problem: 'Los hitos sin reconocimiento no consolidan el comportamiento.',
    whenToUse: 'Cuando el cliente cumple la condición de un logro.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: primera compra', 'Evento: meta alcanzada', 'Evento: alcanzó racha'],
    conditions: ['Condición del logro cumplida', 'Logro no otorgado antes'],
    variables: ['cliente.nombre', 'logro.nombre'],
    engines: ['rule', 'action', 'gamification', 'reward', 'analytics'],
    flow: ['Se cumple la condición del logro', 'Se otorga la insignia', 'Se felicita', 'Se registra el logro'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.GAMI_BADGE_UNLOCKED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Logro ya otorgado'],
    compatibleRewards: ['insignias', 'xp', 'puntos'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification Engine con logros'],
    compatibleTemplates: [],
    examples: ['Primera compra, 10 visitas, 5 referidos, consumo acumulado, permanencia'],
    notes: 'Los logros y sus condiciones son configurables; un logro puede iniciar una campaña.',
    config: {
      trigger: { type: 'EVENT', event: EV.GAMI_GOAL_REACHED },
      variables: ['cliente.nombre', 'logro.nombre'],
      channels: ['push', 'inapp'],
      steps: [
        {
          label: 'Otorgar insignia',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'unlock_badge' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Logro desbloqueado, {{cliente.nombre}}!', body: 'Ganaste la insignia “{{logro.nombre}}”.' } },
          ],
          chain: { event: EV.GAMI_BADGE_UNLOCKED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-009',
    name: 'Ranking actualizado (competitividad sana)',
    objective: 'Comunicar la posición en el ranking para estimular la actividad.',
    problem: 'La actividad no se maximiza sin visibilidad competitiva.',
    whenToUse: 'De forma recurrente, con rankings configurables.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (actualización de ranking)'],
    conditions: ['Ranking activo'],
    variables: ['cliente.nombre', 'ranking.posicion', 'ranking.tipo'],
    engines: ['rule', 'action', 'gamification', 'analytics'],
    flow: ['Se recalcula el ranking', 'Se comunica la posición y cómo subir', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Actualización periódica (editable)'],
    events: [EV.GAMI_RANKING_UPDATED],
    exceptions: ['Ranking desactivado', 'Notificaciones off'],
    compatibleRewards: ['puntos', 'xp', 'insignias'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification Engine con rankings'],
    compatibleTemplates: [],
    examples: ['Más visitas / más puntos / más referidos / más retos completados'],
    notes: 'El tipo de ranking es configurable; siempre orientado a un comportamiento de negocio.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 18 * * 5' },
      variables: ['cliente.nombre', 'ranking.posicion', 'ranking.tipo'],
      channels: ['push'],
      steps: [
        {
          label: 'Comunicar ranking',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'update_ranking' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Vas #{{ranking.posicion}} en {{ranking.tipo}}', body: '{{cliente.nombre}}, sube posiciones esta semana.' } },
          ],
          chain: { event: EV.GAMI_RANKING_UPDATED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-010',
    name: 'Desafío completado (recompensa mayor)',
    objective: 'Premiar la finalización de desafíos exigentes con recompensas de alto valor.',
    problem: 'Los desafíos sin buena recompensa no motivan el esfuerzo extra.',
    whenToUse: 'Cuando el cliente completa un desafío.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: desafío completado'],
    conditions: ['Desafío cumplido'],
    variables: ['cliente.nombre', 'desafio.recompensa'],
    engines: ['rule', 'action', 'gamification', 'reward', 'benefit', 'analytics'],
    flow: ['Se completa el desafío', 'Se entrega la recompensa mayor', 'Se felicita', 'Se registra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.GAMI_CHALLENGE_COMPLETED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Desafío no cumplido'],
    compatibleRewards: ['beneficios', 'cupones', 'puntos', 'promociones', 'accesos'],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['CHALLENGE'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification/Reward Engine'],
    compatibleTemplates: [],
    examples: ['Desafío mensual completo → beneficio premium + puntos extra'],
    notes: 'Los desafíos y sus recompensas son editables; recompensa proporcional al esfuerzo.',
    config: {
      trigger: { type: 'EVENT', event: EV.GAMI_CHALLENGE_COMPLETED },
      variables: ['cliente.nombre', 'desafio.recompensa'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Premiar desafío',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: '{{desafio.recompensa}}' } },
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 200 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Desafío superado, {{cliente.nombre}}!', body: 'Te ganaste una recompensa especial.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-011',
    name: 'Competencia iniciada',
    objective: 'Lanzar una competencia por tiempo limitado para elevar la actividad.',
    problem: 'La actividad se estanca sin picos competitivos.',
    whenToUse: 'Al comenzar una competencia (evento o temporada).',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (inicio de competencia)'],
    conditions: ['Competencia configurada'],
    variables: ['cliente.nombre', 'competencia.nombre', 'competencia.premio'],
    engines: ['rule', 'action', 'gamification', 'campaign', 'analytics'],
    flow: ['Comienza la competencia', 'Se inscribe/anuncia a los participantes', 'Se comunica el premio y las reglas', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración de la competencia (editable)'],
    events: [EV.GAMI_COMPETITION_STARTED],
    exceptions: ['Competencia ya activa'],
    compatibleRewards: ['puntos', 'insignias', 'beneficios', 'promociones'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['CONTEST'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification Engine con competencias'],
    compatibleTemplates: [],
    examples: ['“Competencia de la semana: quien más visite gana un premio”'],
    notes: 'El premio, reglas y duración son editables; encadena con GAM-012 al cierre.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 * * 1' },
      variables: ['cliente.nombre', 'competencia.nombre', 'competencia.premio'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Iniciar competencia',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'start_competition' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Comienza {{competencia.nombre}}!', body: '{{cliente.nombre}}, compite por {{competencia.premio}}.' } },
          ],
          chain: { event: EV.GAMI_COMPETITION_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-012',
    name: 'Competencia finalizada (premiación)',
    objective: 'Cerrar la competencia y premiar a los ganadores.',
    problem: 'Una competencia sin cierre y premiación clara desmotiva a futuro.',
    whenToUse: 'Al terminar una competencia.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado (fin de competencia)'],
    conditions: ['Competencia finalizada'],
    variables: ['cliente.nombre', 'competencia.posicion', 'competencia.premio'],
    engines: ['rule', 'action', 'gamification', 'reward', 'benefit', 'campaign', 'analytics'],
    flow: ['Termina la competencia', 'Se calculan los ganadores', 'Se entregan los premios', 'Se comunica y se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.GAMI_COMPETITION_FINISHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Competencia aún activa'],
    compatibleRewards: ['beneficios', 'puntos', 'insignias', 'promociones', 'accesos'],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['CONTEST'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification/Reward Engine'],
    compatibleTemplates: [],
    examples: ['Cierre semanal → top 3 reciben premios y reconocimiento'],
    notes: 'La premiación se define por reglas; motiva la participación en la próxima competencia.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 20 * * 0' },
      variables: ['cliente.nombre', 'competencia.posicion', 'competencia.premio'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Premiar ganadores',
          condition: 'competencia.posicion <= 3',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Top {{competencia.posicion}}, {{cliente.nombre}}!', body: 'Ganaste {{competencia.premio}}.' } },
          ],
          chain: { event: EV.GAMI_COMPETITION_FINISHED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-013',
    name: 'Bonificación por actividad',
    objective: 'Recompensar picos de actividad para reforzar el comportamiento.',
    problem: 'Los picos de actividad no siempre se reconocen ni se sostienen.',
    whenToUse: 'Cuando el cliente concentra alta actividad en un período.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: alta actividad'],
    conditions: ['Actividad por encima del umbral'],
    variables: ['cliente.nombre', 'actividad.reciente'],
    engines: ['rule', 'action', 'gamification', 'reward', 'analytics'],
    flow: ['Se detecta alta actividad', 'Se otorga un bono (puntos/XP)', 'Se comunica', 'Se registra'],
    actions: [ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CLIENT_HIGH_ACTIVITY, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Actividad dentro de lo normal'],
    compatibleRewards: ['puntos', 'xp', 'insignias'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion', 'frecuencia'],
    dependencies: ['Analytics con conteo de actividad', 'Reward Engine'],
    compatibleTemplates: [],
    examples: ['3 visitas en una semana → bono de puntos'],
    notes: 'El umbral y el bono son editables; convierte picos en hábito.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_HIGH_ACTIVITY },
      variables: ['cliente.nombre', 'actividad.reciente'],
      channels: ['push'],
      steps: [
        {
          label: 'Bonificar actividad',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 30 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Estás imparable, {{cliente.nombre}}!', body: 'Bono de puntos por tu actividad.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-014',
    name: 'Recompensa sorpresa (refuerzo variable)',
    objective: 'Sorprender con recompensas ocasionales para mantener el interés.',
    problem: 'Las recompensas 100% predecibles pierden poder motivador con el tiempo.',
    whenToUse: 'De forma ocasional/aleatoria tras una acción valiosa.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: visita', 'Evento: compra'],
    conditions: ['Regla de sorpresa (probabilidad/condición configurable)'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'gamification', 'reward', 'benefit', 'analytics'],
    flow: ['Ocurre la acción', 'La regla decide si hay sorpresa', 'Se entrega la recompensa sorpresa', 'Se registra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['No aplica la sorpresa esta vez'],
    compatibleRewards: ['beneficios', 'puntos', 'cupones', 'xp'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['SURPRISE'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification/Reward Engine', 'Regla de probabilidad'],
    compatibleTemplates: [],
    examples: ['“¡Sorpresa! Hoy tu servicio incluye un extra gratis”'],
    notes: 'Refuerzo de intervalo variable (mecánica de hábito); la probabilidad es editable.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_VISIT },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        {
          label: 'Sorpresa condicional',
          condition: 'cliente.sorpresaElegible == true',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Sorpresa, {{cliente.nombre}}!', body: 'Hoy tienes un regalo inesperado.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-015',
    name: 'Evento especial / reto de temporada',
    objective: 'Lanzar retos temporales atados a fechas comerciales.',
    problem: 'Las fechas clave se desaprovechan sin un reto que las active.',
    whenToUse: 'En Navidad, Black Friday, Semana Santa, Verano, aniversario, etc.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Programado (evento/temporada)'],
    conditions: ['Evento/temporada activo'],
    variables: ['cliente.nombre', 'evento.nombre', 'evento.meta'],
    engines: ['rule', 'action', 'gamification', 'promotion', 'campaign', 'analytics'],
    flow: ['Llega el evento', 'Se lanza el reto de temporada', 'Se comunica el premio', 'Se mide'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración del evento (editable)'],
    events: [EV.GAMI_MISSION_STARTED, EV.CAMPAIGN_LAUNCHED],
    exceptions: ['Fuera de fecha'],
    compatibleRewards: ['puntos', 'insignias', 'beneficios', 'promociones'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['SEASONAL', 'CHALLENGE'],
    compatibleCampaigns: ['gamificacion', 'estacional'],
    dependencies: ['Gamification/Promotion Engine'],
    compatibleTemplates: [],
    examples: ['Reto navideño: “5 visitas en diciembre → insignia + beneficio”'],
    notes: 'El evento, meta y fechas son editables; una plantilla sirve para todas las temporadas.',
    config: {
      trigger: { type: 'SCHEDULE', schedule: '0 9 1 12 *', params: { event: 'editable' } },
      variables: ['cliente.nombre', 'evento.nombre', 'evento.meta'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Lanzar reto de temporada',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'start_seasonal_challenge' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Reto de {{evento.nombre}}, {{cliente.nombre}}', body: 'Cumple {{evento.meta}} y gana.' } },
          ],
          chain: { event: EV.GAMI_MISSION_STARTED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-016',
    name: 'Meta alcanzada (hito de negocio)',
    objective: 'Reconocer metas que representan un objetivo comercial cumplido.',
    problem: 'Las metas de negocio no se refuerzan si no se celebran.',
    whenToUse: 'Cuando el cliente alcanza una meta configurada.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: meta alcanzada', 'Evento: alcanzó meta de frecuencia'],
    conditions: ['Meta cumplida'],
    variables: ['cliente.nombre', 'meta.nombre'],
    engines: ['rule', 'action', 'gamification', 'reward', 'benefit', 'campaign', 'analytics'],
    flow: ['Se alcanza la meta', 'Se recompensa y reconoce', 'Se propone la siguiente meta', 'Opcional: inicia una campaña'],
    actions: [ACTION_TYPES.ADD_POINTS, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH],
    esperas: [],
    events: [EV.GAMI_GOAL_REACHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Meta no configurada'],
    compatibleRewards: ['puntos', 'xp', 'beneficios', 'insignias', 'niveles'],
    compatibleBenefits: ['CAR-001', 'CAR-004'],
    compatiblePromotions: ['MILESTONE'],
    compatibleCampaigns: ['gamificacion', 'fidelizacion'],
    dependencies: ['Gamification Engine con metas'],
    compatibleTemplates: [],
    examples: ['Meta de consumo acumulado / permanencia / objetivos alcanzados'],
    notes: 'Un logro/meta puede iniciar una campaña (integración nativa con Campaign Engine).',
    config: {
      trigger: { type: 'EVENT', event: EV.GAMI_GOAL_REACHED },
      variables: ['cliente.nombre', 'meta.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Celebrar meta',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 100 } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Meta cumplida, {{cliente.nombre}}!', body: 'Lograste “{{meta.nombre}}”. Aquí va tu recompensa.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-017',
    name: 'Meta compartida (viralidad + referidos)',
    objective: 'Convertir un logro en recomendación al invitar a compartirlo.',
    problem: 'Los logros generan orgullo que no se aprovecha para crecer.',
    whenToUse: 'Tras desbloquear un logro/meta destacable.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: insignia desbloqueada', 'Evento: meta alcanzada'],
    conditions: ['Logro destacable', 'Programa de referidos activo'],
    variables: ['cliente.nombre', 'logro.nombre', 'referido.codigo'],
    engines: ['rule', 'action', 'gamification', 'referral', 'analytics'],
    flow: ['Se desbloquea un logro', 'Se invita a compartirlo con el código de referido', 'Al compartir, se refuerza', 'Se mide'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.INVOKE_MODULE],
    esperas: [],
    events: [EV.REFERRAL_SHARED, EV.AUTOMATION_FINISHED],
    exceptions: ['Programa de referidos inactivo'],
    compatibleRewards: ['puntos', 'insignias'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['REFERRAL'],
    compatibleCampaigns: ['gamificacion', 'referidos'],
    dependencies: ['Gamification + Referral Engine'],
    compatibleTemplates: [],
    examples: ['“¡Desbloqueaste un logro! Compártelo e invita a un amigo”'],
    notes: 'Une gamificación y referidos: el orgullo del logro impulsa la recomendación.',
    config: {
      trigger: { type: 'EVENT', event: EV.GAMI_BADGE_UNLOCKED },
      variables: ['cliente.nombre', 'logro.nombre', 'referido.codigo'],
      channels: ['push'],
      steps: [
        {
          label: 'Invitar a compartir el logro',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Presume tu logro, {{cliente.nombre}}', body: 'Comparte “{{logro.nombre}}” con {{referido.codigo}} e invita a un amigo.' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'referral', action: 'share_achievement' } },
          ],
          chain: { event: EV.REFERRAL_SHARED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-018',
    name: 'Objetivo grupal / de equipo',
    objective: 'Movilizar a un grupo hacia una meta colectiva.',
    problem: 'Las metas individuales no capturan la fuerza del esfuerzo colectivo.',
    whenToUse: 'Para equipos, familias, flotas o comunidades.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Programado / evento: progreso grupal'],
    conditions: ['Grupo configurado', 'Meta colectiva definida'],
    variables: ['grupo.nombre', 'grupo.progreso', 'grupo.meta'],
    engines: ['rule', 'action', 'gamification', 'reward', 'campaign', 'analytics'],
    flow: ['Se define la meta grupal', 'Se agrega el progreso del grupo', 'Al alcanzarla, se recompensa a todos', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.SEND_PUSH],
    esperas: ['Duración del objetivo grupal (editable)'],
    events: [EV.GAMI_GROUP_GOAL_REACHED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Grupo no configurado', 'Meta no alcanzada'],
    compatibleRewards: ['puntos', 'beneficios', 'insignias', 'accesos'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['GROUP'],
    compatibleCampaigns: ['gamificacion'],
    dependencies: ['Gamification Engine con metas grupales'],
    compatibleTemplates: [],
    examples: ['Familia/flota alcanza X visitas juntas → beneficio para todos'],
    notes: 'Aprovecha la presión social positiva; útil para membresías familiares/flota.',
    config: {
      trigger: { type: 'EVENT', event: EV.GAMI_GROUP_GOAL_REACHED },
      variables: ['grupo.nombre', 'grupo.progreso', 'grupo.meta'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Recompensar al grupo',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'gamification', action: 'reward_group' } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡{{grupo.nombre}} lo logró!', body: 'Alcanzaron la meta juntos. Recompensa para todos.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-019',
    name: 'Programa VIP gamificado',
    objective: 'Reconocer a los clientes de más alto nivel con estatus y accesos.',
    problem: 'Los mejores clientes esperan un trato diferenciado que fidelice.',
    whenToUse: 'Cuando el cliente alcanza el nivel más alto configurado.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: subió de nivel (nivel VIP)'],
    conditions: ['Nivel máximo/VIP alcanzado'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'gamification', 'membership', 'benefit', 'campaign', 'analytics'],
    flow: ['Se alcanza el nivel VIP', 'Se otorgan accesos/beneficios permanentes', 'Se comunica el estatus', 'Se registra'],
    actions: [ACTION_TYPES.INVOKE_MODULE, ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_EMAIL],
    esperas: [],
    events: [EV.CLIENT_LEVEL_UP, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['No es nivel VIP'],
    compatibleRewards: ['niveles', 'accesos', 'beneficios', 'membresias'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['VIP'],
    compatibleCampaigns: ['gamificacion', 'vip'],
    dependencies: ['Gamification + Membership Engine'],
    compatibleTemplates: [],
    examples: ['Nivel máximo → acceso VIP, beneficios permanentes, eventos exclusivos'],
    notes: 'Un nivel puede desbloquear una membresía VIP (integración nativa con Membership).',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_LEVEL_UP },
      variables: ['cliente.nombre'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Otorgar estatus VIP',
          condition: 'nivel.esVip == true',
          actions: [
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'membership', action: 'unlock_vip' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-001' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Bienvenido al club VIP, {{cliente.nombre}}', body: 'Desbloqueaste beneficios y accesos exclusivos.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'GAM-020',
    name: 'Progreso hacia la próxima recompensa (near-miss)',
    objective: 'Empujar al cliente que está a poco de una recompensa a completar la acción.',
    problem: 'Muchos clientes abandonan justo antes de conseguir la recompensa.',
    whenToUse: 'Cuando el cliente está cerca de un hito/recompensa.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: cerca de recompensa'],
    conditions: ['Progreso dentro del rango “casi lo logras”'],
    variables: ['cliente.nombre', 'progreso.faltante', 'progreso.recompensa'],
    engines: ['rule', 'action', 'gamification', 'analytics'],
    flow: ['Se detecta el near-miss', 'Se recuerda lo que falta y el premio', 'Al completar, se recompensa', 'Se registra'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.INVOKE_MODULE],
    esperas: ['Recordatorio único (editable)'],
    events: [EV.GAMI_GOAL_REACHED],
    exceptions: ['Ya alcanzó la recompensa', 'Notificaciones off'],
    compatibleRewards: ['puntos', 'xp', 'beneficios', 'insignias'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion', 'frecuencia'],
    dependencies: ['Gamification Engine con progreso por cliente'],
    compatibleTemplates: [],
    examples: ['“Te falta 1 visita para tu recompensa: ¡ven hoy!”'],
    notes: 'Efecto “near-miss”: la cercanía a la meta es un potente motivador; el umbral es editable.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'cerca_de_recompensa' } },
      variables: ['cliente.nombre', 'progreso.faltante', 'progreso.recompensa'],
      channels: ['push', 'whatsapp'],
      limits: { maxPerSubject: 1, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Empujar near-miss',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Casi lo logras, {{cliente.nombre}}!', body: 'Te falta {{progreso.faltante}} para {{progreso.recompensa}}.' } },
          ],
          chain: { event: EV.GAMI_GOAL_REACHED },
        },
      ],
    },
  }),
]

/** Lista mutable de los playbooks de gamificación (para composición). */
export function gamificationPlaybooks(): AutomationPlaybook[] {
  return [...GAMIFICATION_PLAYBOOKS]
}

/** Busca un playbook de gamificación por su ID (ej. "GAM-001"). */
export function getGamificationPlaybook(id: string): AutomationPlaybook | undefined {
  return GAMIFICATION_PLAYBOOKS.find((p) => p.id === id)
}
