/**
 * Biblioteca de Automation Playbooks de ONBOARDING (Fase E1.2). Convierte a un
 * usuario recién registrado en un cliente activo y comprometido durante sus
 * primeros días. Estrategias probadas de activación (Klaviyo/HubSpot/Braze/
 * Intercom/Appcues) convertidas en playbooks UNIVERSALES instalables sobre el
 * Automation Engine (E1). Reutilizan Rule Engine (condiciones), Action Engine
 * (acciones) y referencian Benefit/Reward/Membership/Gamification/Referral/
 * Campaign/Analytics por código. Car Wash es solo la primera industria que las
 * usa.
 *
 * Cada Playbook es una automatización real (`config`) + su documentación
 * completa (24 apartados). Nada hardcodeado por industria: beneficios/promos por
 * código y textos con variables `{{...}}`.
 */

import { ACTION_TYPES } from '@/lib/rule-engine'
import { AUTOMATION_EVENTS as EV } from '../domain/events'
import { INDUSTRIES as I } from './types'
import type { AutomationPlaybook } from './types'

const U = I.UNIVERSAL

// Configuración editable mínima (Documento Maestro): común a todos.
const EDITABLE = [
  'nombre', 'descripcion', 'trigger', 'reglas', 'horarios', 'dias', 'fechas',
  'prioridad', 'segmentos', 'beneficios', 'promociones', 'limites', 'expiracion',
  'espera', 'sucursales', 'canales', 'idioma', 'variables',
] as const

// KPIs típicos de onboarding / activación temprana.
const ONB_KPIS = [
  'tasa_activacion', 'perfil_completado', 'cuentas_verificadas',
  'primera_visita', 'primera_compra', 'tasa_retencion_temprana',
  'time_to_first_value', 'abandono_temprano', 'tasa_apertura', 'tasa_clic',
] as const

/** Helper: completa los apartados comunes de un playbook de onboarding. */
function pb(
  p: Omit<AutomationPlaybook, 'category' | 'editable' | 'kpis' | 'engines'> &
    Partial<Pick<AutomationPlaybook, 'engines' | 'kpis' | 'editable'>>,
): AutomationPlaybook {
  return {
    category: 'onboarding',
    editable: p.editable ?? EDITABLE,
    kpis: p.kpis ?? ONB_KPIS,
    engines: p.engines ?? ['rule', 'action', 'analytics'],
    ...p,
  }
}

export const ONBOARDING_PLAYBOOKS: readonly AutomationPlaybook[] = [
  pb({
    id: 'ONB-001',
    name: 'Bienvenida y activación inicial',
    objective: 'Dar la bienvenida y guiar los primeros pasos tras el registro.',
    problem: 'Los usuarios se registran pero no saben qué hacer después y se enfrían.',
    whenToUse: 'Inmediatamente después de que un cliente crea su cuenta.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Cuenta recién creada'],
    variables: ['cliente.nombre', 'empresa.nombre'],
    engines: ['rule', 'action', 'analytics'],
    flow: ['Cliente se registra', 'Se envía bienvenida con próximos pasos', 'Se registra el inicio del onboarding', 'Se emite evento para encadenar'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_EVENT],
    esperas: [],
    events: [EV.CLIENT_REGISTERED, EV.AUTOMATION_FINISHED],
    exceptions: ['Cliente sin canal de contacto', 'Cuenta creada por importación masiva'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['WELCOME'],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Canal de notificación configurado'],
    compatibleTemplates: ['universal.bienvenida'],
    examples: ['Car Wash: “Bienvenido, así funciona tu programa de lavados”', 'Gimnasio: “Bienvenido, agenda tu primera clase”'],
    notes: 'Punto de entrada del onboarding; encadena con completar perfil y descubrimiento.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre', 'empresa.nombre'],
      channels: ['push', 'email'],
      priority: 10,
      steps: [
        {
          label: 'Bienvenida',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Bienvenido, {{cliente.nombre}}!', body: 'Te acompañamos en tus primeros pasos con {{empresa.nombre}}.' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Bienvenido a {{empresa.nombre}}', body: 'Estos son tus próximos pasos.' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'onboarding.iniciado' } },
          ],
          chain: { event: EV.CLIENT_REGISTERED },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-002',
    name: 'Completar perfil con incentivo',
    objective: 'Lograr que el cliente complete la información clave de su perfil.',
    problem: 'Perfiles incompletos impiden segmentar y personalizar.',
    whenToUse: 'Cuando pasa un tiempo y el perfil sigue incompleto.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado', 'Segmento: perfil incompleto'],
    conditions: ['El perfil no está completo'],
    variables: ['cliente.nombre', 'cliente.perfilCompleto'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['Se detecta perfil incompleto', 'Se espera', 'Se recuerda completar', 'Al completar, se entrega un beneficio opcional', 'Se emite evento de perfil completado'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['24h antes del primer recordatorio'],
    events: [EV.CLIENT_PROFILE_COMPLETED, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Perfil ya completo', 'Cliente sin canal de contacto'],
    compatibleBenefits: ['CAR-011', 'CAR-004'],
    compatiblePromotions: ['PROFILE_COMPLETE'],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Indicador de perfil completo en el contexto', 'Benefit Engine (beneficio opcional)'],
    compatibleTemplates: [],
    examples: ['Car Wash: “Agrega tu vehículo y recibe un aroma gratis”', 'Salón: “Completa tus preferencias y recibe 10% en tu primer servicio”'],
    notes: 'El beneficio es opcional y editable; la espera y el número de recordatorios son configurables.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      limits: { maxPerSubject: 3, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Recordar completar perfil',
          condition: 'cliente.perfilCompleto == false',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Te falta un paso, {{cliente.nombre}}', body: 'Completa tu perfil para personalizar tu experiencia.' } },
          ],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Beneficio por completar',
          condition: 'cliente.perfilCompleto == true',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } },
          ],
          chain: { event: EV.CLIENT_PROFILE_COMPLETED },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-003',
    name: 'Verificación de cuenta pendiente',
    objective: 'Conseguir que el cliente confirme su cuenta (correo/teléfono).',
    problem: 'Cuentas sin verificar reducen la entregabilidad y la confianza.',
    whenToUse: 'Cuando la cuenta no ha sido verificada tras el registro.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Cuenta no verificada'],
    variables: ['cliente.nombre', 'cliente.verificado'],
    engines: ['rule', 'action', 'analytics'],
    flow: ['Se detecta cuenta sin verificar', 'Se envían recordatorios espaciados', 'Expiración configurable', 'Al verificar, se emite evento'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_SMS],
    esperas: ['Recordatorios a 1h, 24h y 72h (editable)'],
    events: [EV.CLIENT_VERIFIED],
    exceptions: ['Cuenta ya verificada', 'Sin correo ni teléfono'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Flujo de verificación de la plataforma'],
    compatibleTemplates: [],
    examples: ['Recordatorio: “Confirma tu correo para activar tu cuenta”'],
    notes: 'La ventana de expiración y el número de recordatorios son editables; no entrega beneficios.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email', 'sms'],
      limits: { maxPerSubject: 3, perPeriod: 'WEEK' },
      steps: [
        {
          label: 'Primer recordatorio',
          condition: 'cliente.verificado == false',
          actions: [
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Confirma tu cuenta, {{cliente.nombre}}', body: 'Verifica tu cuenta para activarla.' } },
          ],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Segundo recordatorio',
          condition: 'cliente.verificado == false',
          actions: [
            { type: ACTION_TYPES.SEND_SMS, params: { body: 'Aún no confirmas tu cuenta. Verifícala para no perder tus beneficios.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ONB-004',
    name: 'Primer beneficio de bienvenida con expiración',
    objective: 'Entregar un primer beneficio y motivar su uso antes de expirar.',
    problem: 'Los beneficios de bienvenida caducan sin usarse.',
    whenToUse: 'Al registrarse, con un beneficio de uso limitado en el tiempo.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['El cliente no ha usado el beneficio de bienvenida'],
    variables: ['cliente.nombre', 'beneficio.expira'],
    engines: ['rule', 'action', 'benefit', 'reward', 'analytics'],
    flow: ['Se entrega el beneficio', 'Se espera', 'Si no se usó, se recuerda antes de expirar', 'Al usarse, se registra'],
    actions: [ACTION_TYPES.APPLY_BENEFIT, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.REGISTER_QR_USE],
    esperas: ['Recordatorio 48h antes de expirar (editable)'],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.CLIENT_COUPON_USED],
    exceptions: ['Beneficio ya usado', 'Beneficio sin stock'],
    compatibleBenefits: ['CAR-004', 'CAR-003', 'CAR-001'],
    compatiblePromotions: ['WELCOME'],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Benefit Engine con beneficio publicado y expiración'],
    compatibleTemplates: ['universal.bienvenida'],
    examples: ['Car Wash: lavado exprés gratis válido 7 días', 'Restaurante: postre gratis válido esta semana'],
    notes: 'La expiración y el recordatorio son editables; el uso se registra por el Action Engine.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'whatsapp'],
      steps: [
        {
          label: 'Entregar beneficio',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004', expiresInDays: 7 }, required: true },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Un regalo para ti, {{cliente.nombre}}', body: 'Úsalo antes de que expire.' } },
          ],
          wait: { ms: 432_000_000 },
        },
        {
          label: 'Recordatorio por vencer',
          condition: 'cliente.usoBeneficioBienvenida == false',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tu regalo está por expirar', body: 'Aprovéchalo antes de que termine.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ONB-005',
    name: 'Descubrimiento de funcionalidades (tour de valor)',
    objective: 'Que el cliente conozca beneficios, membresías, puntos y referidos.',
    problem: 'Los clientes no usan funciones que desconocen.',
    whenToUse: 'Durante los primeros días tras el registro.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Cliente en fase de onboarding'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'benefit', 'membership', 'referral', 'analytics'],
    flow: ['Día 1: presentar beneficios', 'Día 2: presentar membresías', 'Día 3: presentar puntos y referidos', 'Se registra el progreso'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_EVENT],
    esperas: ['Un mensaje por día durante 3 días (editable)'],
    events: [EV.CLIENT_REGISTERED, EV.AUTOMATION_FINISHED],
    exceptions: ['Cliente ya activo', 'Cliente desactivó notificaciones'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['WELCOME'],
    compatibleCampaigns: ['onboarding', 'descubrimiento'],
    dependencies: ['Contenido de cada función configurado'],
    compatibleTemplates: [],
    examples: ['Serie de 3 días presentando el programa completo'],
    notes: 'Los tiempos y el contenido de cada día son editables; ideal como drip multicanal.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Día 1 — Beneficios',
          actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Descubre tus beneficios', body: '{{cliente.nombre}}, mira todo lo que puedes disfrutar.' } }],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Día 2 — Membresías',
          actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Ahorra más con una membresía', body: 'Conoce los planes disponibles.' } }],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Día 3 — Puntos y referidos',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Gana puntos e invita amigos', body: 'Acumula recompensas y comparte.' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'onboarding.descubrimiento_completo' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ONB-006',
    name: 'Primera visita pendiente (incentivo)',
    objective: 'Convertir el registro en la primera visita/compra real.',
    problem: 'Clientes registrados que nunca llegan a visitar el negocio.',
    whenToUse: 'Cuando pasan días sin que el cliente visite tras registrarse.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Segmento: registrado sin primera visita'],
    conditions: ['Cliente sin visitas', 'Han pasado N días desde el registro'],
    variables: ['cliente.nombre', 'cliente.visitas'],
    engines: ['rule', 'action', 'benefit', 'promotion', 'analytics'],
    flow: ['Se detecta ausencia de primera visita', 'Se espera', 'Se envía incentivo para la primera visita', 'Al visitar, se emite evento'],
    actions: [ACTION_TYPES.SEND_WHATSAPP, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['3 días desde el registro (editable)'],
    events: [EV.CLIENT_FIRST_VISIT, EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Cliente ya visitó', 'Sin canal de contacto'],
    compatibleBenefits: ['CAR-003', 'CAR-004'],
    compatiblePromotions: ['FIRST_VISIT', 'FIRST_PURCHASE'],
    compatibleCampaigns: ['onboarding', 'primera_visita'],
    dependencies: ['Registro de visitas en el contexto'],
    compatibleTemplates: [],
    examples: ['Car Wash: “Ven esta semana y tu lavado tiene 30% off”', 'Veterinaria: “Primera consulta con regalo de bienvenida”'],
    notes: 'La ventana previa al incentivo y el beneficio son editables.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'registrado_sin_visita' } },
      variables: ['cliente.nombre'],
      channels: ['whatsapp', 'push'],
      limits: { maxPerSubject: 2, perPeriod: 'MONTH' },
      steps: [
        {
          label: 'Incentivar primera visita',
          condition: 'cliente.visitas == 0',
          actions: [
            { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, te esperamos: tu primera visita tiene un beneficio especial.' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-003' } },
          ],
          chain: { event: EV.CLIENT_FIRST_VISIT },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-007',
    name: 'Presentación de membresías (prueba)',
    objective: 'Presentar las membresías y ofrecer una prueba para convertir.',
    problem: 'Clientes nuevos desconocen o dudan del valor de una membresía.',
    whenToUse: 'Tras las primeras interacciones, cuando el cliente ve valor.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: primera visita', 'Segmento: activo sin membresía'],
    conditions: ['Cliente sin membresía activa'],
    variables: ['cliente.nombre', 'cliente.tieneMembresia'],
    engines: ['rule', 'action', 'membership', 'promotion', 'analytics'],
    flow: ['Cliente muestra actividad', 'Se recomienda una membresía', 'Se ofrece una prueba', 'Al activar, se emite evento'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.INVOKE_MODULE],
    esperas: ['Tras la primera visita (editable)'],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.AUTOMATION_FINISHED],
    exceptions: ['Cliente ya tiene membresía', 'Sin planes publicados'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: ['MEMBERSHIP_TRIAL'],
    compatibleCampaigns: ['membresias'],
    dependencies: ['Membership Engine con planes publicados'],
    compatibleTemplates: [],
    examples: ['Car Wash: “Prueba el plan ilimitado 7 días”', 'Gimnasio: “Primer mes con precio de prueba”'],
    notes: 'La recomendación usa el Membership Engine; la oferta de prueba es editable.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_FIRST_VISIT },
      variables: ['cliente.nombre'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Recomendar membresía',
          condition: 'cliente.tieneMembresia == false',
          actions: [
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Ahorra con una membresía, {{cliente.nombre}}', body: 'Descubre el plan ideal para ti con una prueba.' } },
            { type: ACTION_TYPES.INVOKE_MODULE, params: { module: 'membership', action: 'recommend' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ONB-008',
    name: 'Preferencias del cliente',
    objective: 'Recoger preferencias opcionales para personalizar la experiencia.',
    problem: 'Sin preferencias, la comunicación es genérica y menos efectiva.',
    whenToUse: 'Durante el onboarding, tras la bienvenida.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Preferencias no configuradas'],
    variables: ['cliente.nombre', 'cliente.preferencias'],
    engines: ['rule', 'action', 'analytics', 'template'],
    flow: ['Se solicita configurar preferencias', 'Al guardarlas, se segmenta y se emite evento'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.RECORD_EVENT],
    esperas: ['48h tras la bienvenida (editable)'],
    events: [EV.CLIENT_PREFERENCES_SET],
    exceptions: ['Preferencias ya configuradas', 'Cliente desactivó notificaciones'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Formulario de preferencias', 'Template Engine para campos por industria'],
    compatibleTemplates: [],
    examples: ['Car Wash: vehículo, sucursal y horario', 'Salón: servicios favoritos y estilista'],
    notes: 'Los campos de preferencia se adaptan por industria con el Template Engine; nada hardcodeado.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Pedir preferencias',
          condition: 'cliente.preferencias == false',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Personaliza tu experiencia', body: '{{cliente.nombre}}, cuéntanos tus preferencias.' } },
          ],
          wait: { ms: 172_800_000 },
          chain: { event: EV.CLIENT_PREFERENCES_SET },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-009',
    name: 'Consentimientos y preferencias de comunicación',
    objective: 'Obtener aceptación de términos, políticas y canales de contacto.',
    problem: 'Sin consentimiento no se puede comunicar de forma cumplida.',
    whenToUse: 'Cuando falta aceptar términos o definir canales.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Consentimiento pendiente'],
    variables: ['cliente.nombre', 'cliente.consentimiento'],
    engines: ['rule', 'action', 'analytics'],
    flow: ['Se detecta consentimiento pendiente', 'Se solicita aceptación', 'Al aceptar, se registra y se emite evento'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.RECORD_HISTORY],
    esperas: ['Recordatorio a 24h (editable)'],
    events: [EV.CLIENT_CONSENT_GIVEN],
    exceptions: ['Consentimiento ya otorgado'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['onboarding', 'cumplimiento'],
    dependencies: ['Registro de consentimientos'],
    compatibleTemplates: [],
    examples: ['“Acepta recibir novedades por WhatsApp/email”'],
    notes: 'Registra evidencia con RECORD_HISTORY para auditoría/cumplimiento.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email'],
      steps: [
        {
          label: 'Solicitar consentimiento',
          condition: 'cliente.consentimiento == false',
          actions: [
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Elige cómo quieres que te contactemos', body: 'Acepta y personaliza tus preferencias de comunicación.' } },
            { type: ACTION_TYPES.RECORD_HISTORY, params: { event: 'consentimiento.solicitado' } },
          ],
          chain: { event: EV.CLIENT_CONSENT_GIVEN },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-010',
    name: 'Encuesta inicial de intereses',
    objective: 'Conocer intereses del cliente para segmentarlo correctamente.',
    problem: 'Sin datos de interés, la personalización es limitada.',
    whenToUse: 'En los primeros días, tras la bienvenida.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Encuesta no respondida'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'analytics', 'campaign'],
    flow: ['Se invita a responder una encuesta corta', 'Con las respuestas, se segmenta', 'Se registra el resultado'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.RECORD_EVENT],
    esperas: ['72h tras la bienvenida (editable)'],
    events: [EV.CLIENT_PREFERENCES_SET, EV.AUTOMATION_FINISHED],
    exceptions: ['Encuesta ya respondida'],
    compatibleBenefits: ['CAR-011'],
    compatiblePromotions: [],
    compatibleCampaigns: ['segmentacion'],
    dependencies: ['Módulo de encuestas o formulario'],
    compatibleTemplates: [],
    examples: ['“¿Qué servicios te interesan más?” para segmentar la comunicación'],
    notes: 'Las respuestas alimentan segmentos usados por otras automatizaciones.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Enviar encuesta',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Cuéntanos qué te interesa', body: '2 preguntas para personalizar tu experiencia, {{cliente.nombre}}.' } },
          ],
          wait: { ms: 259_200_000 },
          chain: { event: EV.CLIENT_PREFERENCES_SET },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-011',
    name: 'Tutorial interactivo in-app',
    objective: 'Guiar al cliente por las funciones principales dentro de la app.',
    problem: 'Los usuarios no descubren funciones clave por sí solos.',
    whenToUse: 'En las primeras aperturas de la aplicación.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Tutorial no completado'],
    variables: ['cliente.nombre', 'cliente.tutorialPaso'],
    engines: ['rule', 'action', 'analytics'],
    flow: ['Se muestra el tutorial paso a paso', 'Se registra el avance', 'Al completarlo, se emite evento'],
    actions: [ACTION_TYPES.SEND_INTERNAL_NOTIFICATION, ACTION_TYPES.RECORD_EVENT],
    esperas: ['Entre pasos según interacción (editable)'],
    events: [EV.CLIENT_ONBOARDING_COMPLETED],
    exceptions: ['Tutorial ya completado'],
    compatibleBenefits: [],
    compatiblePromotions: [],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Componente de tutorial in-app'],
    compatibleTemplates: [],
    examples: ['Guía in-app: perfil → beneficios → QR → puntos'],
    notes: 'Usa notificación interna (in-app); el avance se persiste para reanudar.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['inapp'],
      steps: [
        {
          label: 'Mostrar tutorial',
          condition: 'cliente.tutorialCompleto == false',
          actions: [
            { type: ACTION_TYPES.SEND_INTERNAL_NOTIFICATION, params: { title: 'Conoce tu app', body: 'Te mostramos lo esencial en 4 pasos.' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'tutorial.mostrado' } },
          ],
          chain: { event: EV.CLIENT_ONBOARDING_COMPLETED },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-012',
    name: 'Primer hito cumplido (reconocimiento)',
    objective: 'Reconocer y reforzar cuando el cliente cumple su primer hito.',
    problem: 'La falta de refuerzo temprano reduce el compromiso.',
    whenToUse: 'Cuando el cliente completa su primera acción valiosa.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: primera visita', 'Evento: misión completada'],
    conditions: ['Es el primer hito del cliente'],
    variables: ['cliente.nombre', 'cliente.puntos'],
    engines: ['rule', 'action', 'gamification', 'reward', 'analytics'],
    flow: ['El cliente cumple su primer hito', 'Se otorga reconocimiento (puntos/insignia)', 'Se felicita', 'Se registra el progreso'],
    actions: [ACTION_TYPES.ADD_POINTS, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.RECORD_EVENT],
    esperas: [],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.CLIENT_MISSION_COMPLETED],
    exceptions: ['No es el primer hito', 'Gamificación desactivada'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['gamificacion', 'onboarding'],
    dependencies: ['Gamification/Reward Engine para puntos o insignias'],
    compatibleTemplates: [],
    examples: ['Car Wash: primera visita → insignia + puntos', 'Retail: primera compra → nivel inicial'],
    notes: 'El reconocimiento (puntos/insignia) es editable; refuerza el hábito temprano.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_FIRST_VISIT },
      variables: ['cliente.nombre'],
      channels: ['push'],
      steps: [
        {
          label: 'Reconocer primer hito',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 50 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Bien hecho, {{cliente.nombre}}!', body: 'Ganaste tu primer reconocimiento.' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'onboarding.primer_hito' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-013',
    name: 'Onboarding multicanal configurable',
    objective: 'Ejecutar la serie de bienvenida por los canales que la empresa habilite.',
    problem: 'Un solo canal limita el alcance y la activación.',
    whenToUse: 'Como serie de activación con canales configurables.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Cliente en onboarding con canales habilitados'],
    variables: ['cliente.nombre', 'empresa.canales'],
    engines: ['rule', 'action', 'campaign', 'analytics'],
    flow: ['Día 0: in-app + push', 'Día 1: email', 'Día 3: WhatsApp/SMS si está habilitado', 'Se registra el resultado por canal'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_WHATSAPP],
    esperas: ['Escalonado en 3 días (editable)'],
    events: [EV.CLIENT_REGISTERED, EV.AUTOMATION_FINISHED],
    exceptions: ['Canal deshabilitado por la empresa', 'Cliente sin datos de contacto'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: ['WELCOME'],
    compatibleCampaigns: ['onboarding', 'multicanal'],
    dependencies: ['Canales habilitados por la empresa'],
    compatibleTemplates: [],
    examples: ['Serie de bienvenida por push, email y WhatsApp según configuración'],
    notes: 'Los canales se leen de la configuración de la empresa; nada fijo. Cada empresa habilita/deshabilita.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email', 'whatsapp', 'sms', 'inapp'],
      steps: [
        {
          label: 'Día 0 — App + push',
          actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Bienvenido, {{cliente.nombre}}', body: 'Empecemos.' } }],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Día 1 — Email',
          actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Tu guía para empezar', body: 'Todo lo que necesitas saber.' } }],
          wait: { ms: 172_800_000 },
        },
        {
          label: 'Día 3 — WhatsApp (si habilitado)',
          actions: [{ type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, ¿te ayudamos a dar el primer paso?' } }],
        },
      ],
    },
  }),

  pb({
    id: 'ONB-014',
    name: 'Serie de bienvenida (drip 3 días)',
    objective: 'Mantener el contacto temprano con una secuencia de valor.',
    problem: 'Un único mensaje no basta para activar; hace falta cadencia.',
    whenToUse: 'Como secuencia estándar de bienvenida.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente registrado'],
    conditions: ['Cliente aún no ha comprado'],
    variables: ['cliente.nombre', 'cliente.compras'],
    engines: ['rule', 'action', 'benefit', 'analytics'],
    flow: ['Día 1: bienvenida', 'Día 2: valor y beneficios', 'Día 3: incentivo a la primera compra', 'Se registra la conversión'],
    actions: [ACTION_TYPES.SEND_EMAIL, ACTION_TYPES.SEND_PUSH, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['Un mensaje por día durante 3 días (editable)'],
    events: [EV.CLIENT_REWARD_OBTAINED, EV.AUTOMATION_FINISHED],
    exceptions: ['Cliente ya compró (se corta la serie)', 'Sin canal de contacto'],
    compatibleBenefits: ['CAR-004', 'CAR-011'],
    compatiblePromotions: ['WELCOME', 'FIRST_PURCHASE'],
    compatibleCampaigns: ['onboarding'],
    dependencies: ['Benefit Engine para el incentivo final'],
    compatibleTemplates: ['universal.bienvenida'],
    examples: ['Drip clásico de 3 correos/push de bienvenida'],
    notes: 'La serie se corta si el cliente compra antes; tiempos y contenido editables.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REGISTERED },
      variables: ['cliente.nombre'],
      channels: ['email', 'push'],
      steps: [
        {
          label: 'Día 1 — Bienvenida',
          actions: [{ type: ACTION_TYPES.SEND_EMAIL, params: { subject: '¡Bienvenido, {{cliente.nombre}}!', body: 'Gracias por unirte.' } }],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Día 2 — Valor',
          condition: 'cliente.compras == 0',
          actions: [{ type: ACTION_TYPES.SEND_PUSH, params: { title: 'Todo lo que puedes disfrutar', body: 'Descubre tus beneficios.' } }],
          wait: { ms: 86_400_000 },
        },
        {
          label: 'Día 3 — Incentivo',
          condition: 'cliente.compras == 0',
          actions: [
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-004' } },
            { type: ACTION_TYPES.SEND_EMAIL, params: { subject: 'Un empujón para tu primera compra', body: 'Te dejamos un beneficio.' } },
          ],
        },
      ],
    },
  }),

  pb({
    id: 'ONB-015',
    name: 'Presentar el programa de puntos',
    objective: 'Explicar cómo ganar y canjear puntos para fomentar el hábito.',
    problem: 'Clientes no acumulan puntos porque no entienden el programa.',
    whenToUse: 'En la primera semana, idealmente tras la primera visita.',
    complexity: 'basic',
    industries: [U],
    triggers: ['Evento: primera visita'],
    conditions: ['Programa de puntos activo'],
    variables: ['cliente.nombre', 'cliente.puntos'],
    engines: ['rule', 'action', 'reward', 'gamification', 'analytics'],
    flow: ['El cliente acumula sus primeros puntos', 'Se explica cómo ganarlos y canjearlos', 'Se registra el evento'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.ADD_POINTS],
    esperas: [],
    events: [EV.CLIENT_REWARD_OBTAINED],
    exceptions: ['Programa de puntos desactivado'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['fidelizacion', 'onboarding'],
    dependencies: ['Reward/Gamification Engine con programa de puntos'],
    compatibleTemplates: [],
    examples: ['“Ganaste tus primeros puntos: así puedes canjearlos”'],
    notes: 'XP ≠ puntos; usa el programa de puntos del Reward Engine, editable por empresa.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_FIRST_VISIT },
      variables: ['cliente.nombre', 'cliente.puntos'],
      channels: ['push'],
      steps: [
        {
          label: 'Explicar puntos',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 20 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Tus primeros puntos, {{cliente.nombre}}', body: 'Tienes {{cliente.puntos}} puntos. Así los canjeas.' } },
          ],
          chain: { event: EV.CLIENT_REWARD_OBTAINED },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-016',
    name: 'Invitación temprana a referidos',
    objective: 'Aprovechar el entusiasmo inicial para activar el referral.',
    problem: 'El mejor momento para referir se pierde si no se pide temprano.',
    whenToUse: 'Tras el primer hito positivo del cliente.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: cliente obtuvo recompensa', 'Evento: primera visita'],
    conditions: ['Cliente con experiencia positiva reciente'],
    variables: ['cliente.nombre', 'cliente.codigoReferido'],
    engines: ['rule', 'action', 'referral', 'analytics'],
    flow: ['El cliente vive una experiencia positiva', 'Se le invita a referir con su enlace', 'Al referir, se emite evento'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.SEND_WHATSAPP],
    esperas: ['Poco después del hito (editable)'],
    events: [EV.CLIENT_REFERRED_FRIEND],
    exceptions: ['Programa de referidos desactivado', 'Cliente sin código'],
    compatibleBenefits: ['CAR-004'],
    compatiblePromotions: [],
    compatibleCampaigns: ['referidos'],
    dependencies: ['Referral Engine con programa activo'],
    compatibleTemplates: [],
    examples: ['“¿Te gustó? Invita a un amigo y ambos ganan”'],
    notes: 'Usa el código del Referral Engine; la recompensa la gestiona ese motor.',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_REWARD_OBTAINED },
      variables: ['cliente.nombre', 'cliente.codigoReferido'],
      channels: ['push', 'whatsapp'],
      steps: [
        {
          label: 'Invitar a referir',
          actions: [
            { type: ACTION_TYPES.SEND_PUSH, params: { title: 'Invita y gana, {{cliente.nombre}}', body: 'Comparte tu código {{cliente.codigoReferido}} y ambos ganan.' } },
          ],
          chain: { event: EV.CLIENT_REFERRED_FRIEND },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-017',
    name: 'Rescate de onboarding estancado',
    objective: 'Reactivar a quien inició el onboarding y no avanzó.',
    problem: 'Clientes que quedan a mitad del onboarding y se abandonan.',
    whenToUse: 'Cuando el cliente no completa el onboarding en N días.',
    complexity: 'advanced',
    industries: [U],
    triggers: ['Segmento: onboarding incompleto'],
    conditions: ['Onboarding sin completar', 'Sin actividad reciente'],
    variables: ['cliente.nombre', 'cliente.onboardingCompleto'],
    engines: ['rule', 'action', 'benefit', 'campaign', 'analytics'],
    flow: ['Se detecta onboarding estancado', 'Se envía un empujón con beneficio', 'Si sigue sin avanzar, se cierra el intento'],
    actions: [ACTION_TYPES.SEND_WHATSAPP, ACTION_TYPES.APPLY_BENEFIT],
    esperas: ['Recordatorio a los 5 y 10 días (editable)'],
    events: [EV.CLIENT_ONBOARDING_COMPLETED, EV.AUTOMATION_FINISHED],
    exceptions: ['Onboarding ya completo', 'Cliente sin canal de contacto'],
    compatibleBenefits: ['CAR-011', 'CAR-004'],
    compatiblePromotions: ['WELCOME'],
    compatibleCampaigns: ['recuperacion', 'onboarding'],
    dependencies: ['Segmentación de onboarding incompleto'],
    compatibleTemplates: [],
    examples: ['“Te quedaste a un paso: completa y llévate un beneficio”'],
    notes: 'Complementa a los playbooks de recuperación (E1.4); aquí es específico del onboarding.',
    config: {
      trigger: { type: 'SEGMENT_ENTER', params: { segment: 'onboarding_incompleto' } },
      variables: ['cliente.nombre'],
      channels: ['whatsapp', 'email'],
      limits: { maxPerSubject: 2, perPeriod: 'MONTH' },
      steps: [
        {
          label: 'Empujón con beneficio',
          condition: 'cliente.onboardingCompleto == false',
          actions: [
            { type: ACTION_TYPES.SEND_WHATSAPP, params: { body: '{{cliente.nombre}}, te quedaste a un paso. Completa y llévate un beneficio.' } },
            { type: ACTION_TYPES.APPLY_BENEFIT, params: { benefitCode: 'CAR-011' } },
          ],
          wait: { ms: 432_000_000 },
          chain: { event: EV.CLIENT_ONBOARDING_COMPLETED },
        },
      ],
    },
  }),

  pb({
    id: 'ONB-018',
    name: 'Graduación de onboarding (próximos pasos)',
    objective: 'Cerrar el onboarding, celebrar y preparar la fidelización.',
    problem: 'Sin un cierre claro, el cliente no sabe cómo continuar.',
    whenToUse: 'Cuando el cliente completa su proceso de activación.',
    complexity: 'intermediate',
    industries: [U],
    triggers: ['Evento: onboarding completado'],
    conditions: ['Onboarding completado'],
    variables: ['cliente.nombre'],
    engines: ['rule', 'action', 'reward', 'campaign', 'analytics'],
    flow: ['El cliente completa el onboarding', 'Se felicita y entrega un reconocimiento', 'Se presentan los próximos pasos', 'Se marca como cliente activo'],
    actions: [ACTION_TYPES.SEND_PUSH, ACTION_TYPES.ADD_POINTS, ACTION_TYPES.RECORD_EVENT],
    esperas: [],
    events: [EV.CLIENT_ONBOARDING_COMPLETED, EV.AUTOMATION_FINISHED],
    exceptions: ['Onboarding no completado'],
    compatibleBenefits: ['CAR-001'],
    compatiblePromotions: [],
    compatibleCampaigns: ['fidelizacion'],
    dependencies: ['Eventos previos de onboarding'],
    compatibleTemplates: [],
    examples: ['“Completaste tu activación: esto es lo que sigue”'],
    notes: 'Marca el fin del onboarding y el inicio de la fase de fidelización (E1.3+).',
    config: {
      trigger: { type: 'EVENT', event: EV.CLIENT_ONBOARDING_COMPLETED },
      variables: ['cliente.nombre'],
      channels: ['push', 'email'],
      steps: [
        {
          label: 'Graduar y encaminar',
          actions: [
            { type: ACTION_TYPES.ADD_POINTS, params: { points: 100 } },
            { type: ACTION_TYPES.SEND_PUSH, params: { title: '¡Listo, {{cliente.nombre}}!', body: 'Completaste tu activación. Esto es lo que sigue.' } },
            { type: ACTION_TYPES.RECORD_EVENT, params: { event: 'onboarding.graduado' } },
          ],
        },
      ],
    },
  }),
]

/** Lista mutable de los playbooks de onboarding (para composición). */
export function onboardingPlaybooks(): AutomationPlaybook[] {
  return [...ONBOARDING_PLAYBOOKS]
}

/** Busca un playbook de onboarding por su ID (ej. "ONB-001"). */
export function getOnboardingPlaybook(id: string): AutomationPlaybook | undefined {
  return ONBOARDING_PLAYBOOKS.find((p) => p.id === id)
}
