/**
 * Car Wash Promotion Strategy Library (Fase F1.2).
 *
 * Catálogo profesional de ESTRATEGIAS promocionales organizadas por objetivo
 * comercial (no por tipo de descuento), documentadas según el estándar F1.2
 * (25 campos). Cada estrategia apunta a sus VARIANTES instalables
 * (`PromotionTemplate` en `carwash.ts`). Datos, no lógica: el Promotion
 * Framework y los demás motores no cambian.
 */

import type { PromotionSegment } from './taxonomy'
import type { PromotionStrategyCategory } from './strategy-taxonomy'
import type { PromotionStrategy } from './strategy-types'
import type { PromotionTemplate } from './template-types'
import { getCarwashPromo } from './carwash'

export const CARWASH_PROMOTION_STRATEGIES: readonly PromotionStrategy[] = [
  {
    id: 'carwash.promo.captacion',
    industry: 'carwash',
    category: 'captacion',
    name: 'Captación de nuevos clientes',
    description: 'Estrategias para atraer y registrar clientes nuevos con una primera oferta de bajo riesgo.',
    objective: 'Aumentar el flujo de clientes nuevos y su registro en la plataforma.',
    problemSolved: 'Base de clientes estancada y bajo flujo de nuevos: crea un incentivo de primer contacto.',
    expectedResult: 'Más registros y primeras visitas de clientes que no conocían el negocio.',
    whenToUse: 'Al abrir, entrar a una zona nueva o cuando el flujo de nuevos cae.',
    whenNotToUse: 'Cuando el problema es retención y no adquisición, o falta capacidad para atender más volumen.',
    recommendedSegment: ['nuevo'],
    compatibleServices: ['lavado_exterior', 'lavado_premium', 'aspirado'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    recommendedDuration: '2 a 4 semanas por campaña',
    recommendedFrequency: 'Continua para nuevos; picos en aperturas',
    complexity: 'baja',
    enginesUsed: ['promotion', 'rule', 'action', 'automation', 'referral'],
    automationPlaybooks: ['bienvenida_nuevo_cliente', 'secuencia_primera_visita'],
    compatibleBenefits: ['descuento_primera_visita', 'servicio_gratis_bienvenida'],
    compatibleMemberships: ['carwash.membership.trial', 'carwash.membership.pay_per_visit'],
    compatibleGamification: ['racha_visitas'],
    compatibleCampaigns: ['captacion_suscripcion'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'ventas_generadas', 'roi'],
    bestPractices: ['Limitar la oferta a 1 uso por cliente nuevo', 'Capturar datos y consentimiento en el registro', 'Difundir por QR en el local y redes'],
    commonMistakes: ['Descuento tan alto que atrae solo cazadores de ofertas', 'No pedir registro y perder el dato', 'No dar seguimiento a la segunda visita'],
    risks: ['Canibalizar clientes que igual habrían venido', 'Sobrecosto de adquisición sin retorno'],
    variantKeys: ['carwash.CAR-001', 'carwash.CAR-002', 'carwash.CAR-037'],
    version: '1.0.0',
    technicalNotes: 'Trigger ON_SIGNUP/ON_FIRST_VISIT; beneficio como acción del Action Engine; restricción PER_CLIENT=1. Condiciones de elegibilidad como BEL.',
  },
  {
    id: 'carwash.promo.activacion',
    industry: 'carwash',
    category: 'activacion',
    name: 'Activación de registros a primera visita',
    description: 'Estrategias para convertir un registro sin visitas en su primer lavado mediante urgencia, valor agregado y acompañamiento.',
    objective: 'Convertir clientes registrados inactivos en su primera visita real al local.',
    problemSolved: 'Registros que nunca llegan a visitar: cierra la brecha entre el alta y el primer consumo.',
    expectedResult: 'Mayor tasa de conversión de registro a primera visita y menor caída tras el alta.',
    whenToUse: 'Cuando hay muchos registros sin primera visita o tras campañas de captación con baja conversión.',
    whenNotToUse: 'Cuando el cliente ya visitó y el objetivo es frecuencia o retención, o si no hubo captación previa que activar.',
    recommendedSegment: ['nuevo', 'convertido'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    recommendedDuration: '1 a 2 semanas desde el registro',
    recommendedFrequency: 'Continua sobre registros nuevos',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'automation', 'campaign'],
    automationPlaybooks: ['activacion_registro_sin_visita', 'recordatorio_oferta_vence'],
    compatibleBenefits: ['descuento_primera_visita', 'upgrade_gratis_bienvenida'],
    compatibleMemberships: ['carwash.membership.trial', 'carwash.membership.pay_per_visit'],
    compatibleGamification: ['racha_visitas'],
    compatibleCampaigns: ['activacion_bienvenida'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'ventas_generadas', 'roi'],
    bestPractices: ['Poner fecha de vencimiento visible a la oferta de bienvenida', 'Secuenciar 2 a 3 recordatorios con urgencia creciente', 'Facilitar el canje con QR o link directo a reservar'],
    commonMistakes: ['Dejar la oferta abierta sin vencimiento y perder urgencia', 'Un solo mensaje sin seguimiento', 'Pedir demasiados pasos para canjear la primera visita'],
    risks: ['Fatiga por exceso de recordatorios y bajas', 'Activar solo por el incentivo sin intención de repetir'],
    variantKeys: ['carwash.CAR-003', 'carwash.CAR-021', 'carwash.CAR-038', 'carwash.CAR-039'],
    version: '1.0.0',
    technicalNotes: 'Trigger ON_SIGNUP con delay y condición BEL visits_count=0; recordatorios por Automation con ventana de expiración; beneficio vía Action Engine PER_CLIENT=1.',
  },
  {
    id: 'carwash.promo.frecuencia',
    industry: 'carwash',
    category: 'frecuencia',
    name: 'Aumento de frecuencia de visitas',
    description: 'Estrategias para que el cliente activo lave más seguido usando bundles, metas de visitas y recompensas escalonadas.',
    objective: 'Incrementar el número de visitas por cliente en un período dado.',
    problemSolved: 'Clientes que visitan de forma esporádica: acorta el intervalo entre lavados.',
    expectedResult: 'Mayor cantidad de visitas por cliente y aumento del ticket recurrente.',
    whenToUse: 'Cuando la base ya visita pero con baja frecuencia, o para elevar el uso en temporada.',
    whenNotToUse: 'Con clientes nuevos aún sin hábito o inactivos que primero deben reactivarse.',
    recommendedSegment: ['frecuente', 'miembro', 'convertido'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero'],
    recommendedDuration: '4 a 8 semanas por ciclo',
    recommendedFrequency: 'Continua o mensual',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'reward', 'gamification', 'membership'],
    automationPlaybooks: ['meta_visitas_mensual', 'recordatorio_intervalo_lavado'],
    compatibleBenefits: ['sello_visita_acumulable', 'lavado_gratis_por_meta'],
    compatibleMemberships: ['carwash.membership.unlimited', 'carwash.membership.credits', 'carwash.membership.loyalty'],
    compatibleGamification: ['racha_visitas', 'tarjeta_sellos'],
    compatibleCampaigns: ['frecuencia_visitas'],
    kpis: ['uso', 'ventas_generadas', 'beneficio_entregado', 'costo', 'roi'],
    bestPractices: ['Fijar metas alcanzables por ciclo (ej. 3 lavados al mes)', 'Recordar según el intervalo típico de suciedad del vehículo', 'Recompensar el hábito, no solo la compra puntual'],
    commonMistakes: ['Metas inalcanzables que desmotivan', 'Premiar visitas que igual habrían ocurrido', 'No comunicar el progreso hacia la meta'],
    risks: ['Erosionar margen si el premio supera el valor incremental', 'Saturar capacidad operativa en horas pico'],
    variantKeys: ['carwash.CAR-004', 'carwash.CAR-005', 'carwash.CAR-006'],
    version: '1.0.0',
    technicalNotes: 'Reward Engine acumula por evento ON_VISIT; metas y progreso como BEL sobre visits_count en ventana; Automation dispara recordatorio según last_visit + intervalo.',
  },
  {
    id: 'carwash.promo.retencion',
    industry: 'carwash',
    category: 'retencion',
    name: 'Retención de clientes activos',
    description: 'Estrategias para mantener activos y fieles a los clientes de valor con reconocimiento, beneficios exclusivos y membresías.',
    objective: 'Sostener la actividad de los clientes valiosos y reducir la tasa de abandono.',
    problemSolved: 'Riesgo de fuga de clientes buenos hacia la competencia por falta de valor percibido.',
    expectedResult: 'Menor churn, mayor vida útil del cliente y aumento del valor recurrente.',
    whenToUse: 'De forma permanente sobre clientes frecuentes, VIP o miembros con actividad sostenida.',
    whenNotToUse: 'Cuando el cliente ya está inactivo (usar recuperación) o aún no tiene hábito de compra.',
    recommendedSegment: ['frecuente', 'vip', 'miembro', 'alto_valor'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    recommendedDuration: 'Permanente con hitos periódicos',
    recommendedFrequency: 'Continua',
    complexity: 'alta',
    enginesUsed: ['membership', 'benefit', 'reward', 'rule', 'automation', 'analytics'],
    automationPlaybooks: ['alerta_riesgo_abandono', 'reconocimiento_aniversario_cliente'],
    compatibleBenefits: ['beneficio_exclusivo_miembro', 'upgrade_preferente_vip'],
    compatibleMemberships: ['carwash.membership.vip', 'carwash.membership.unlimited', 'carwash.membership.tier', 'carwash.membership.loyalty'],
    compatibleGamification: ['niveles_fidelidad', 'racha_visitas'],
    compatibleCampaigns: ['fidelizacion_vip'],
    kpis: ['uso', 'ventas_generadas', 'beneficio_entregado', 'rentabilidad', 'roi'],
    bestPractices: ['Segmentar por valor y riesgo de fuga con analítica', 'Dar beneficios exclusivos no replicables por descuento', 'Reconocer hitos como aniversario o cambio de nivel'],
    commonMistakes: ['Tratar igual a todos los clientes sin segmentar', 'Reaccionar solo cuando el cliente ya se fue', 'Competir solo con precio y no con valor percibido'],
    risks: ['Regalar margen a clientes ya fieles sin efecto incremental', 'Generar expectativa de beneficios difícil de sostener'],
    variantKeys: ['carwash.CAR-019', 'carwash.CAR-020'],
    version: '1.0.0',
    technicalNotes: 'Analytics calcula score de riesgo/valor; BEL define umbrales de inactividad; Automation dispara reconocimiento y beneficios exclusivos vía Benefit/Action Engine.',
  },
  {
    id: 'carwash.promo.recuperacion',
    industry: 'carwash',
    category: 'recuperacion',
    name: 'Recuperación de clientes inactivos',
    description: 'Estrategias para reactivar clientes que dejaron de visitar mediante ofertas de regreso con urgencia y motivo de volver.',
    objective: 'Reactivar clientes inactivos y devolverlos a un patrón de visita.',
    problemSolved: 'Clientes que dejaron de venir y no se recuperan solos: dispara un reenganche dirigido.',
    expectedResult: 'Recuperación de clientes dormidos y retorno de ingresos de una base ya conocida.',
    whenToUse: 'Cuando un cliente supera su intervalo normal sin visitar o crece el segmento inactivo.',
    whenNotToUse: 'Con clientes aún activos (evitar canibalizar) o registros que nunca visitaron (usar activación).',
    recommendedSegment: ['inactivo'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'motocicleta', 'van'],
    recommendedDuration: '2 a 3 semanas por ola',
    recommendedFrequency: 'Mensual o por oleadas segmentadas',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'automation', 'campaign', 'analytics'],
    automationPlaybooks: ['reactivacion_cliente_dormido', 'oferta_regreso_con_vencimiento'],
    compatibleBenefits: ['descuento_regreso', 'servicio_gratis_reactivacion'],
    compatibleMemberships: ['carwash.membership.pay_per_visit', 'carwash.membership.credits'],
    compatibleGamification: ['racha_visitas'],
    compatibleCampaigns: ['reactivacion_inactivos'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'ventas_generadas', 'roi'],
    bestPractices: ['Definir inactividad por el intervalo real de cada segmento', 'Dar un motivo claro de volver y un plazo corto para actuar', 'Escalonar la oferta según profundidad de la inactividad'],
    commonMistakes: ['Ofrecer descuentos a quien igual iba a volver', 'Usar el mismo mensaje para dormidos recientes y muy antiguos', 'No poner límite de tiempo y diluir la urgencia'],
    risks: ['Costo de reactivar clientes de bajo valor sin retorno', 'Entrenar al cliente a esperar la oferta de regreso'],
    variantKeys: ['carwash.CAR-007', 'carwash.CAR-008', 'carwash.CAR-009'],
    version: '1.0.0',
    technicalNotes: 'BEL marca inactivo por last_visit > umbral del segmento; Automation lanza olas por Campaign Engine; beneficio de regreso vía Action Engine con expiración y PER_CLIENT=1.',
  },
  {
    id: 'carwash.promo.ticket_promedio',
    industry: 'carwash',
    category: 'ticket_promedio',
    name: 'Aumento de ticket promedio',
    description: 'Estrategias de valor agregado y paquetes para elevar el gasto por visita sin depender de descuentos.',
    objective: 'Incrementar el valor promedio de cada compra por cliente.',
    problemSolved: 'Tickets bajos y márgenes ajustados: agrupa servicios y ofrece complementos de alto valor percibido.',
    expectedResult: 'Mayor gasto por visita y más ventas generadas por transacción.',
    whenToUse: 'Cuando el flujo es sano pero el gasto por visita es bajo.',
    whenNotToUse: 'Cuando el problema es falta de tráfico o captación.',
    recommendedSegment: ['frecuente', 'miembro', 'alto_valor', 'todos'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero', 'lujo'],
    recommendedDuration: '4 a 8 semanas',
    recommendedFrequency: 'Continua con revisión mensual',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'benefit', 'analytics', 'decision'],
    automationPlaybooks: ['sugerencia_paquete_en_caja', 'combo_valor_agregado'],
    compatibleBenefits: ['paquete_combo', 'servicio_adicional_valor', 'upgrade_gratis_por_umbral'],
    compatibleMemberships: ['carwash.membership.credits', 'carwash.membership.tier', 'carwash.membership.hybrid'],
    compatibleGamification: ['umbral_gasto', 'sellos_por_monto'],
    compatibleCampaigns: ['combos_temporada', 'valor_agregado_mensual'],
    kpis: ['ventas_generadas', 'uso', 'beneficio_entregado', 'costo', 'roi', 'rentabilidad'],
    bestPractices: ['Ofrecer combos con ahorro percibido, no rebaja directa', 'Anclar precio con opción premium visible', 'Entrenar al personal en sugerencia en caja'],
    commonMistakes: ['Bajar precio en lugar de agregar valor', 'Combos sin lógica de margen', 'Sobrecargar al cliente con demasiadas opciones'],
    risks: ['Erosionar margen si el combo descuenta de más', 'Percepción de venta forzada'],
    variantKeys: ['carwash.CAR-010', 'carwash.CAR-011', 'carwash.CAR-012', 'carwash.CAR-023'],
    version: '1.0.0',
    technicalNotes: 'Trigger ON_CHECKOUT; Decision Engine evalúa umbral de monto para activar combo; Benefit Engine aplica paquete como bundle.',
  },
  {
    id: 'carwash.promo.upselling',
    industry: 'carwash',
    category: 'upselling',
    name: 'Upselling a servicios de mayor valor',
    description: 'Escalona al cliente del servicio básico al premium o detailing mediante incentivos y prueba de valor.',
    objective: 'Incentivar la migración a servicios de mayor valor (básico a premium a detailing).',
    problemSolved: 'Clientes anclados en el servicio más barato: crea puente hacia niveles superiores.',
    expectedResult: 'Mayor mezcla de servicios premium y aumento del margen por visita.',
    whenToUse: 'Cuando muchos clientes solo consumen el servicio de entrada.',
    whenNotToUse: 'Cuando la capacidad operativa premium está saturada.',
    recommendedSegment: ['frecuente', 'vip', 'alto_valor', 'miembro'],
    compatibleServices: ['lavado_exterior', 'lavado_premium', 'detailing', 'lavado_interior'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    recommendedDuration: '3 a 6 semanas',
    recommendedFrequency: 'Continua con campañas puntuales',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'benefit', 'decision', 'analytics'],
    automationPlaybooks: ['upgrade_primera_prueba_premium', 'recordatorio_beneficio_detailing'],
    compatibleBenefits: ['prueba_premium_descuento', 'upgrade_por_puntos', 'garantia_satisfaccion_premium'],
    compatibleMemberships: ['carwash.membership.tier', 'carwash.membership.premium', 'carwash.membership.hybrid'],
    compatibleGamification: ['nivel_servicio', 'racha_premium'],
    compatibleCampaigns: ['prueba_premium', 'temporada_detailing'],
    kpis: ['clientes_convertidos', 'ventas_generadas', 'uso', 'beneficio_entregado', 'roi', 'rentabilidad'],
    bestPractices: ['Ofrecer prueba del nivel superior a precio de entrada una vez', 'Mostrar diferencia tangible del resultado premium', 'Segmentar la oferta por tipo y valor de vehículo'],
    commonMistakes: ['Forzar upsell sin demostrar valor', 'Ofrecer premium a quien busca rapidez', 'No dar seguimiento tras la primera prueba'],
    risks: ['Saturar capacidad premium', 'Descontar de más y volver el premium el nuevo básico'],
    variantKeys: ['carwash.CAR-013', 'carwash.CAR-044', 'carwash.CAR-045', 'carwash.CAR-035'],
    version: '1.0.0',
    technicalNotes: 'Decision Engine recomienda nivel según historial; Action Engine dispara oferta de upgrade en el punto de venta o post-visita.',
  },
  {
    id: 'carwash.promo.cross_selling',
    industry: 'carwash',
    category: 'cross_selling',
    name: 'Venta cruzada de servicios complementarios',
    description: 'Añade servicios complementarios (aspirado, protección, interior) al servicio principal para completar la experiencia.',
    objective: 'Vender servicios complementarios que amplían el ticket y la satisfacción.',
    problemSolved: 'Clientes que solo compran un servicio aislado desconocen o no consideran los complementos.',
    expectedResult: 'Mayor adopción de servicios complementarios y ticket más completo.',
    whenToUse: 'Cuando existe catálogo de complementos poco utilizado.',
    whenNotToUse: 'Cuando el complemento no aporta valor real al servicio contratado.',
    recommendedSegment: ['frecuente', 'miembro', 'nuevo', 'todos'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero', 'lujo'],
    recommendedDuration: '4 a 8 semanas',
    recommendedFrequency: 'Continua',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'benefit', 'decision', 'analytics'],
    automationPlaybooks: ['sugerencia_complemento_relacionado', 'combo_interior_exterior'],
    compatibleBenefits: ['complemento_descuento_combinado', 'proteccion_gratis_por_umbral', 'aspirado_incluido_promo'],
    compatibleMemberships: ['carwash.membership.credits', 'carwash.membership.hybrid', 'carwash.membership.tier'],
    compatibleGamification: ['coleccion_servicios', 'sellos_por_monto'],
    compatibleCampaigns: ['combos_temporada', 'proteccion_estacional'],
    kpis: ['ventas_generadas', 'uso', 'clientes_convertidos', 'beneficio_entregado', 'costo', 'roi'],
    bestPractices: ['Ofrecer el complemento lógico al servicio elegido', 'Empaquetar interior y exterior con ahorro claro', 'Recomendar protección según clima o temporada'],
    commonMistakes: ['Ofrecer complementos irrelevantes', 'Saturar al cliente con muchos add-ons', 'No mostrar el beneficio del complemento'],
    risks: ['Percepción de venta agresiva', 'Complejidad operativa al sumar servicios'],
    variantKeys: ['carwash.CAR-011', 'carwash.CAR-046', 'carwash.CAR-047', 'carwash.CAR-012'],
    version: '1.0.0',
    technicalNotes: 'Decision Engine mapea servicio principal a complemento relacionado; Action Engine sugiere en caja o en confirmación de reserva.',
  },
  {
    id: 'carwash.promo.membresias',
    industry: 'carwash',
    category: 'membresias',
    name: 'Venta y renovación de membresías',
    description: 'Convierte clientes recurrentes en miembros de suscripción y asegura renovaciones con valor continuo.',
    objective: 'Vender nuevas membresías y renovar las existentes.',
    problemSolved: 'Ingresos irregulares y baja recurrencia: la membresía crea ingreso predecible y hábito.',
    expectedResult: 'Más miembros activos, ingreso recurrente y mayor frecuencia de visita.',
    whenToUse: 'Cuando hay base de clientes frecuentes sin plan de suscripción.',
    whenNotToUse: 'Cuando la operación no puede sostener el uso ilimitado o recurrente.',
    recommendedSegment: ['frecuente', 'vip', 'alto_valor', 'convertido', 'miembro'],
    compatibleServices: ['lavado_exterior', 'lavado_premium', 'aspirado', 'lavado_interior'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    recommendedDuration: 'Continua con campañas de renovación',
    recommendedFrequency: 'Mensual y en fin de ciclo',
    complexity: 'alta',
    enginesUsed: ['promotion', 'membership', 'rule', 'action', 'benefit', 'automation', 'analytics'],
    automationPlaybooks: ['conversion_frecuente_a_miembro', 'recordatorio_renovacion', 'recuperacion_membresia_vencida'],
    compatibleBenefits: ['primer_mes_promocional', 'beneficio_exclusivo_miembro', 'lavado_extra_por_renovacion'],
    compatibleMemberships: ['carwash.membership.unlimited', 'carwash.membership.tier', 'carwash.membership.premium', 'carwash.membership.vip', 'carwash.membership.subscription_box'],
    compatibleGamification: ['racha_visitas', 'nivel_membresia'],
    compatibleCampaigns: ['captacion_suscripcion', 'renovacion_membresia'],
    kpis: ['clientes_convertidos', 'ventas_generadas', 'uso', 'beneficio_entregado', 'costo', 'roi', 'rentabilidad'],
    bestPractices: ['Convertir tras umbral de visitas que ya justifica el plan', 'Comunicar el ahorro frente al pago por visita', 'Automatizar recordatorios antes del vencimiento'],
    commonMistakes: ['Vender membresía a clientes de baja frecuencia', 'No gestionar la renovación con anticipación', 'Prometer uso ilimitado sin controlar costo'],
    risks: ['Sobreuso que erosiona el margen', 'Cancelaciones si el valor percibido baja', 'Presión sobre capacidad operativa'],
    variantKeys: ['carwash.CAR-016', 'carwash.CAR-017', 'carwash.CAR-018'],
    version: '1.0.0',
    technicalNotes: 'Membership Engine gestiona alta y ciclo; Automation dispara recordatorios de renovación por fecha; Decision Engine detecta candidatos por frecuencia.',
  },
  {
    id: 'carwash.promo.referidos',
    industry: 'carwash',
    category: 'referidos',
    name: 'Programa de referidos',
    description: 'Incentiva a clientes satisfechos a recomendar con recompensa de doble vía para quien refiere y quien llega.',
    objective: 'Incentivar recomendaciones que traigan clientes nuevos de bajo costo.',
    problemSolved: 'Adquisición cara y poco boca a boca estructurado: convierte clientes en canal de captación.',
    expectedResult: 'Nuevos clientes referidos a menor costo y mayor lealtad de quien refiere.',
    whenToUse: 'Cuando hay base satisfecha y buen NPS.',
    whenNotToUse: 'Cuando la calidad de servicio aún es inestable.',
    recommendedSegment: ['frecuente', 'vip', 'miembro', 'alto_valor'],
    compatibleServices: ['lavado_exterior', 'lavado_premium', 'aspirado', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    recommendedDuration: 'Continua',
    recommendedFrequency: 'Permanente con impulsos estacionales',
    complexity: 'media',
    enginesUsed: ['promotion', 'referral', 'rule', 'action', 'reward', 'automation', 'analytics'],
    automationPlaybooks: ['invitacion_referido', 'recompensa_doble_via', 'seguimiento_referido_convertido'],
    compatibleBenefits: ['recompensa_por_referir', 'beneficio_bienvenida_referido', 'lavado_gratis_por_referido'],
    compatibleMemberships: ['carwash.membership.tier', 'carwash.membership.credits', 'carwash.membership.premium'],
    compatibleGamification: ['ranking_referidores', 'metas_referidos'],
    compatibleCampaigns: ['referidos_temporada', 'trae_un_amigo'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'ventas_generadas', 'beneficio_entregado', 'roi'],
    bestPractices: ['Recompensar a ambas partes solo tras visita válida del referido', 'Facilitar compartir con enlace o código simple', 'Premiar más a quien refiere clientes que se vuelven recurrentes'],
    commonMistakes: ['Recompensar antes de la conversión real', 'Proceso de referir complicado', 'No comunicar el estado de la recompensa'],
    risks: ['Fraude o autorreferidos', 'Costo si el referido no retiene', 'Saturar a los clientes con pedidos de referir'],
    variantKeys: ['carwash.CAR-025', 'carwash.CAR-026'],
    version: '1.0.0',
    technicalNotes: 'Referral Engine genera código único y atribuye conversión; Reward Engine libera beneficio tras visita válida del referido; antifraude por PER_CLIENT y validación de visita.',
  },
  {
    id: 'carwash.promo.horarios_baja_demanda',
    industry: 'carwash',
    category: 'horarios_baja_demanda',
    name: 'Happy Hour y horas valle',
    description: 'Estrategias para desplazar demanda hacia franjas de baja ocupación con incentivos de tiempo limitado (Happy Hour, días lentos, primeras horas).',
    objective: 'Nivelar la carga operativa moviendo visitas de horas pico a horas valle.',
    problemSolved: 'Colas y saturación en pico frente a bahías vacías en horas muertas: aprovecha capacidad ociosa sin ampliar recursos.',
    expectedResult: 'Mayor uso en franjas valle, menor congestión en pico y mejor ingreso por hora-bahía.',
    whenToUse: 'Cuando hay contraste claro entre horas llenas y vacías, o entre días fuertes y flojos.',
    whenNotToUse: 'Cuando la demanda ya es pareja o cuando el negocio opera al límite todo el día.',
    recommendedSegment: ['frecuente', 'miembro', 'todos'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'motocicleta'],
    recommendedDuration: 'Permanente con revisión mensual',
    recommendedFrequency: 'Diaria en franjas definidas',
    complexity: 'media',
    enginesUsed: ['promotion', 'rule', 'action', 'automation', 'analytics', 'decision'],
    automationPlaybooks: ['recordatorio_happy_hour', 'reactivacion_horas_valle'],
    compatibleBenefits: ['descuento_horario_valle', 'servicio_extra_gratis_valle'],
    compatibleMemberships: ['carwash.membership.unlimited', 'carwash.membership.loyalty'],
    compatibleGamification: ['racha_visitas'],
    compatibleCampaigns: ['activacion_horas_valle'],
    kpis: ['clientes_alcanzados', 'uso', 'ventas_generadas', 'rentabilidad', 'roi'],
    bestPractices: ['Definir franjas con datos reales de ocupación', 'Comunicar la ventana con claridad y urgencia', 'Ofrecer valor agregado en vez de solo descuento'],
    commonMistakes: ['Aplicar Happy Hour en horas que ya están llenas', 'Franjas demasiado amplias que erosionan el ticket'],
    risks: ['Trasladar sin sumar visitas nuevas', 'Acostumbrar al cliente a esperar la hora barata'],
    variantKeys: ['carwash.CAR-006', 'carwash.CAR-040', 'carwash.CAR-041', 'carwash.CAR-042', 'carwash.CAR-043'],
    version: '1.0.0',
    technicalNotes: 'Trigger por ventana horaria (Rule Engine con condiciones de tiempo); Decision Engine para elegir franjas según analytics de ocupación.',
  },
  {
    id: 'carwash.promo.temporadas',
    industry: 'carwash',
    category: 'temporadas',
    name: 'Fechas especiales y temporadas',
    description: 'Promociones ligadas a estacionalidad y fechas comerciales de alto tráfico (fin de semana, aniversario del local, Black Friday, Navidad, clima adverso).',
    objective: 'Capturar picos de intención de compra en fechas y climas de alta demanda.',
    problemSolved: 'Ventas planas fuera de eventos y oportunidades perdidas en fechas comerciales fuertes.',
    expectedResult: 'Aumento de ventas y ticket promedio en las ventanas de temporada activadas.',
    whenToUse: 'En fechas comerciales, aniversarios del negocio o tras lluvias/polvo que disparan la necesidad.',
    whenNotToUse: 'Fuera de contexto estacional o cuando la capacidad ya está saturada en esa fecha.',
    recommendedSegment: ['todos', 'frecuente', 'miembro', 'inactivo'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'camion_ligero', 'lujo'],
    recommendedDuration: '3 a 10 días por evento',
    recommendedFrequency: 'Por calendario de temporadas',
    complexity: 'media',
    enginesUsed: ['promotion', 'campaign', 'rule', 'action', 'automation', 'analytics'],
    automationPlaybooks: ['lanzamiento_temporada', 'recordatorio_fin_promo'],
    compatibleBenefits: ['paquete_temporada', 'descuento_estacional'],
    compatibleMemberships: ['carwash.membership.seasonal', 'carwash.membership.unlimited'],
    compatibleGamification: ['reto_temporada'],
    compatibleCampaigns: ['campana_estacional', 'black_friday_carwash'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'ventas_generadas', 'roi', 'rentabilidad'],
    bestPractices: ['Preparar la campaña con antelación al pico', 'Reforzar la urgencia con fecha de cierre', 'Ligar la promo al motivo estacional (clima, fiesta)'],
    commonMistakes: ['Lanzar tarde y perder el pico', 'Descontar en fechas que ya venden solas'],
    risks: ['Sobredemanda que degrada el servicio', 'Márgenes bajos si el descuento es excesivo'],
    variantKeys: ['carwash.CAR-027', 'carwash.CAR-028', 'carwash.CAR-029', 'carwash.CAR-030', 'carwash.CAR-031'],
    version: '1.0.0',
    technicalNotes: 'Campaign Engine con ventana de vigencia por fecha; Rule Engine puede disparar por señal de clima o calendario.',
  },
  {
    id: 'carwash.promo.eventos',
    industry: 'carwash',
    category: 'eventos',
    name: 'Promociones por eventos',
    description: 'Ofertas puntuales ligadas a eventos locales o comerciales (ferias, partidos, conciertos, alianzas con comercios cercanos).',
    objective: 'Aprovechar la afluencia y el contexto de un evento para atraer visitas.',
    problemSolved: 'Falta de motivo de visita en días normales y desconexión con la actividad local.',
    expectedResult: 'Repunte de tráfico y visibilidad durante y alrededor del evento.',
    whenToUse: 'Cuando hay un evento con audiencia relevante cerca o una alianza comercial activable.',
    whenNotToUse: 'Sin evento pertinente o cuando el público del evento no coincide con el cliente objetivo.',
    recommendedSegment: ['nuevo', 'todos', 'convertido'],
    compatibleServices: ['lavado_exterior', 'aspirado', 'lavado_premium'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'motocicleta'],
    recommendedDuration: '1 a 5 días por evento',
    recommendedFrequency: 'Puntual según calendario de eventos',
    complexity: 'media',
    enginesUsed: ['promotion', 'campaign', 'rule', 'action', 'referral'],
    automationPlaybooks: ['activacion_evento_local'],
    compatibleBenefits: ['descuento_evento', 'beneficio_alianza'],
    compatibleMemberships: ['carwash.membership.seasonal'],
    compatibleGamification: ['reto_temporada'],
    compatibleCampaigns: ['campana_evento_local'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'ventas_generadas', 'roi'],
    bestPractices: ['Coordinar la oferta con el organizador o el comercio aliado', 'Usar un código o distintivo del evento para medir'],
    commonMistakes: ['Elegir eventos sin relación con el cliente', 'No medir el retorno del esfuerzo'],
    risks: ['Costo logístico mayor al retorno', 'Dependencia de la afluencia real del evento'],
    variantKeys: ['carwash.CAR-048', 'carwash.CAR-049'],
    version: '1.0.0',
    technicalNotes: 'Campaign Engine con vigencia acotada al evento; Referral Engine para alianzas cruzadas con comercios.',
  },
  {
    id: 'carwash.promo.fidelizacion',
    industry: 'carwash',
    category: 'fidelizacion',
    name: 'Fidelización de frecuentes y VIP',
    description: 'Estrategias de valor agregado y reconocimiento para retener clientes frecuentes y VIP (beneficios exclusivos, prioridad, upgrades).',
    objective: 'Aumentar la frecuencia de visita y el valor de vida del cliente leal.',
    problemSolved: 'Fuga silenciosa de buenos clientes y falta de diferenciación para los que más aportan.',
    expectedResult: 'Mayor recurrencia, retención y gasto acumulado de los clientes clave.',
    whenToUse: 'Con una base de recurrentes identificada que se quiere blindar y hacer crecer.',
    whenNotToUse: 'Cuando aún no hay masa de clientes frecuentes o el foco es pura captación.',
    recommendedSegment: ['frecuente', 'vip', 'alto_valor', 'miembro'],
    compatibleServices: ['lavado_exterior', 'lavado_interior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    recommendedDuration: 'Permanente',
    recommendedFrequency: 'Continua con hitos periódicos',
    complexity: 'alta',
    enginesUsed: ['promotion', 'membership', 'benefit', 'reward', 'rule', 'automation', 'analytics'],
    automationPlaybooks: ['upgrade_vip', 'reconocimiento_frecuente'],
    compatibleBenefits: ['prioridad_atencion', 'upgrade_servicio', 'beneficio_exclusivo_vip'],
    compatibleMemberships: ['carwash.membership.vip', 'carwash.membership.loyalty', 'carwash.membership.tier'],
    compatibleGamification: ['niveles_vip', 'racha_visitas'],
    compatibleCampaigns: ['fidelizacion_vip'],
    kpis: ['clientes_alcanzados', 'uso', 'beneficio_entregado', 'ventas_generadas', 'rentabilidad', 'roi'],
    bestPractices: ['Premiar la recurrencia con valor, no solo con descuento', 'Hacer visible el estatus y los beneficios exclusivos', 'Escalonar beneficios por nivel'],
    commonMistakes: ['Tratar igual al VIP que al ocasional', 'Beneficios que no se perciben ni se usan'],
    risks: ['Regalar margen a quien ya es leal', 'Complejidad operativa de los niveles'],
    variantKeys: ['carwash.CAR-019', 'carwash.CAR-020', 'carwash.CAR-050', 'carwash.CAR-051'],
    version: '1.0.0',
    technicalNotes: 'Membership y Benefit Engine para niveles y beneficios; Reward Engine para hitos; segmentación por analytics de recurrencia.',
  },
  {
    id: 'carwash.promo.celebraciones',
    industry: 'carwash',
    category: 'celebraciones',
    name: 'Celebraciones e hitos del cliente',
    description: 'Detalles personalizados en fechas y logros del cliente (cumpleaños, aniversario de registro, visita número N) con un gesto de valor.',
    objective: 'Fortalecer el vínculo emocional generando visitas en momentos significativos.',
    problemSolved: 'Relación puramente transaccional y baja conexión personal con el cliente.',
    expectedResult: 'Visitas motivadas por el detalle y mayor lealtad percibida.',
    whenToUse: 'Cuando se cuenta con fechas o hitos registrados del cliente para personalizar.',
    whenNotToUse: 'Sin datos personales confiables o sin consentimiento para contactar.',
    recommendedSegment: ['frecuente', 'vip', 'miembro', 'inactivo'],
    compatibleServices: ['lavado_exterior', 'aspirado', 'lavado_premium', 'detailing'],
    compatibleVehicles: ['sedan', 'suv', 'pickup', 'van', 'lujo'],
    recommendedDuration: 'Ventana de 7 a 14 días por hito',
    recommendedFrequency: 'Automática por evento individual',
    complexity: 'media',
    enginesUsed: ['promotion', 'automation', 'rule', 'action', 'benefit', 'reward'],
    automationPlaybooks: ['felicitacion_cumpleanos', 'aniversario_cliente', 'hito_visita_n'],
    compatibleBenefits: ['regalo_cumpleanos', 'servicio_cortesia_hito'],
    compatibleMemberships: ['carwash.membership.loyalty', 'carwash.membership.rewards'],
    compatibleGamification: ['hitos_cliente', 'racha_visitas'],
    compatibleCampaigns: ['celebracion_cliente'],
    kpis: ['clientes_alcanzados', 'clientes_convertidos', 'uso', 'beneficio_entregado', 'roi'],
    bestPractices: ['Enviar el detalle con anticipación y tono personal', 'Dar una ventana de canje cómoda', 'Que el gesto se sienta genuino, no una venta'],
    commonMistakes: ['Ofertas frías sin personalización real', 'Ventana de canje demasiado corta'],
    risks: ['Percepción de intromisión si el dato es sensible', 'Bajo canje si el gesto no aporta valor'],
    variantKeys: ['carwash.CAR-052', 'carwash.CAR-053', 'carwash.CAR-054'],
    version: '1.0.0',
    technicalNotes: 'Automation Engine con triggers por fecha individual (cumpleaños/aniversario) y por contador de visitas; Reward Engine entrega el gesto.',
  },
]

// ── Índices y descubrimiento ────────────────────────────────────────────────

const BY_ID = new Map(CARWASH_PROMOTION_STRATEGIES.map((s) => [s.id, s]))
const BY_CATEGORY = new Map(CARWASH_PROMOTION_STRATEGIES.map((s) => [s.category, s]))

export function getPromotionStrategy(id: string): PromotionStrategy | undefined {
  return BY_ID.get(id)
}

/** Estrategia que cubre una categoría de objetivo comercial. */
export function promotionStrategyForCategory(
  category: PromotionStrategyCategory,
): PromotionStrategy | undefined {
  return BY_CATEGORY.get(category)
}

/** Resuelve las variantes instalables (PromotionTemplate) de una estrategia. */
export function strategyPromotions(strategy: PromotionStrategy): readonly PromotionTemplate[] {
  return strategy.variantKeys
    .map((k) => getCarwashPromo(k))
    .filter((t): t is PromotionTemplate => t !== undefined)
}

/** Estrategias recomendadas para un segmento de cliente. */
export function promotionStrategiesBySegment(
  segment: PromotionSegment,
): readonly PromotionStrategy[] {
  return CARWASH_PROMOTION_STRATEGIES.filter((s) => s.recommendedSegment.includes(segment))
}
